### ISSUE TITLE
gdal install seems to fail for windows

### ISSUE THREAD

**Issue by AngRodrigues** [conda-forge/gdal-feedstock#1027]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### What is the bug?

Apologies in advance if not a bug. 
The installation seems to be failing via conda on windows 11. 

```
conda create -n test2 python=3.11
conda activate test2
conda install -c conda-forge gdal
gdalinfo --version
````

I get an error about a libminizip.dll not found when running `gdalinfo --version`
![image](https://github.com/user-attachments/assets/5ceb4bb5-8e0b-4d15-85bc-4e6e1e1c86b9)

If I open python and import gdal, I get:
`from osgeo import gdal`

```
(test2) [redacted_path]>python
Python 3.11.11 | packaged by conda-forge | (main, Dec  5 2024, 14:06:23) [MSC v.1942 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gdal'
>>> from osgeo import gdal
Traceback (most recent call last):
  File "redacted_path\anaconda3\envs\test2\Lib\site-packages\osgeo\__init__.py", line 30, in swig_import_helper
    return importlib.import_module(mname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "redacted_path\anaconda3\envs\test2\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "redacted_path\anaconda3\envs\test2\Lib\site-packages\osgeo\__init__.py", line 35, in <module>
    _gdal = swig_import_helper()
            ^^^^^^^^^^^^^^^^^^^^
  File "redacted_path\anaconda3\envs\test2\Lib\site-packages\osgeo\__init__.py", line 32, in swig_import_helper
    return importlib.import_module('_gdal')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "redacted_path\anaconda3\envs\test2\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_gdal'
```

### Installed packages

```shell
#
# Name                    Version                   Build  Channel
_libavif_api              1.1.1                h57928b3_2    conda-forge
aom                       3.9.1                he0c23c2_0    conda-forge
aws-c-auth                0.7.20               h6823eb1_0    conda-forge
aws-c-cal                 0.6.12               hc83774a_0    conda-forge
aws-c-common              0.9.17               h2466b09_0    conda-forge
aws-c-compression         0.2.18               hc83774a_4    conda-forge
aws-c-event-stream        0.4.2               hc6c0aac_10    conda-forge
aws-c-http                0.8.1               hced5053_13    conda-forge
aws-c-io                  0.14.8               hebaacdb_0    conda-forge
aws-c-mqtt                0.10.4               hdafd9a4_2    conda-forge
aws-c-s3                  0.5.9                h7a83f0e_0    conda-forge
aws-c-sdkutils            0.1.16               hc83774a_0    conda-forge
aws-checksums             0.1.18               hc83774a_4    conda-forge
aws-crt-cpp               0.26.8              h672a689_11    conda-forge
aws-sdk-cpp               1.11.267             h12f3f85_8    conda-forge
azure-core-cpp            1.11.1               h249a519_1    conda-forge
azure-storage-blobs-cpp   12.10.0              h91493d7_1    conda-forge
azure-storage-common-cpp  12.5.0               h91493d7_4    conda-forge
blosc                     1.21.6               h85f69ea_0    conda-forge
bzip2                     1.0.8                h2466b09_7    conda-forge
c-ares                    1.34.3               h2466b09_1    conda-forge
ca-certificates           2024.8.30            h56e8100_0    conda-forge
cairo                     1.18.0               h91e5215_2    conda-forge
cfitsio                   4.4.0                h9b0cee5_1    conda-forge
dav1d                     1.2.1                hcfcfb64_0    conda-forge
fmt                       10.2.1               h181d51b_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_3    conda-forge
fontconfig                2.15.0               h765892d_1    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
freexl                    2.0.0                h8276f4a_0    conda-forge
gdal                      3.8.4           py311h21a6730_6    conda-forge
geos                      3.12.1               h1537add_0    conda-forge
geotiff                   1.7.3                hd7df778_1    conda-forge
hdf4                      4.2.15               h5557f11_7    conda-forge
hdf5                      1.14.3          nompi_hd5d9e70_108    conda-forge
icu                       73.2                 h63175ca_0    conda-forge
intel-openmp              2024.2.1          h57928b3_1083    conda-forge
kealib                    1.5.3                h6c43f9b_2    conda-forge
krb5                      1.21.3               hdf4eb48_0    conda-forge
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libabseil                 20240116.2      cxx17_he0c23c2_1    conda-forge
libaec                    1.1.3                h63175ca_0    conda-forge
libarchive                3.7.7                h88ece9c_0    conda-forge
libavif16                 1.1.1                h4d049a7_2    conda-forge
libblas                   3.9.0              25_win64_mkl    conda-forge
libcblas                  3.9.0              25_win64_mkl    conda-forge
libcrc32c                 1.1.2                h0e60522_0    conda-forge
libcurl                   8.10.1               h1ee3ff0_0    conda-forge
libde265                  1.0.15               h91493d7_0    conda-forge
libdeflate                1.20                 hcfcfb64_0    conda-forge
libexpat                  2.6.4                he0c23c2_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgdal                   3.8.4                hbda495f_6    conda-forge
libglib                   2.80.2               h0df6a38_0    conda-forge
libgoogle-cloud           2.23.0               h68df31e_1    conda-forge
libgoogle-cloud-storage   2.23.0               hb581fae_1    conda-forge
libgrpc                   1.62.2               h5273850_0    conda-forge
libheif                   1.18.2          gpl_hc631cee_100    conda-forge
libhwloc                  2.11.2          default_ha69328c_1001    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libintl                   0.22.5               h5728263_3    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
libkml                    1.3.0             h538826c_1021    conda-forge
liblapack                 3.9.0              25_win64_mkl    conda-forge
liblzma                   5.6.3                h2466b09_1    conda-forge
liblzma-devel             5.6.3                h2466b09_1    conda-forge
libnetcdf                 4.9.2           nompi_h008f77d_116    conda-forge
libpng                    1.6.44               h3ca93ac_0    conda-forge
libpq                     16.6                 h5b74ccd_1    conda-forge
libprotobuf               4.25.3               h47a098d_1    conda-forge
libre2-11                 2023.09.01           hf8d8778_2    conda-forge
librttopo                 1.1.0               h94c4f80_15    conda-forge
libspatialite             5.1.0                h1b797e6_7    conda-forge
libsqlite                 3.47.2               h67fdade_0    conda-forge
libssh2                   1.11.1               he619c9f_0    conda-forge
libtiff                   4.6.0                hddb2be6_3    conda-forge
libwebp-base              1.4.0                hcfcfb64_0    conda-forge
libwinpthread             12.0.0.r4.gg4f2fc60ca      h57928b3_8    conda-forge
libxml2                   2.13.5               he286e8c_1    conda-forge
libzip                    1.11.2               h3135430_0    conda-forge
libzlib                   1.3.1                h2466b09_2    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
lzo                       2.10              hcfcfb64_1001    conda-forge
minizip                   4.0.7                h9fa1bad_1    conda-forge
mkl                       2024.2.2            h66d3029_14    conda-forge
numpy                     1.26.4          py311h0b4df5a_0    conda-forge
openjpeg                  2.5.2                h3d672ee_0    conda-forge
openssl                   3.4.0                h2466b09_0    conda-forge
pcre2                     10.43                h17e33f8_0    conda-forge
pip                       24.3.1             pyh8b19718_0    conda-forge
pixman                    0.44.2               had0cd8c_0    conda-forge
poppler                   24.03.0              hc2f3c52_0    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                16.6                 h5b59834_1    conda-forge
proj                      9.4.0                hd9569ee_2    conda-forge
python                    3.11.11         h3f84c4b_1_cpython    conda-forge
python_abi                3.11                    5_cp311    conda-forge
rav1e                     0.6.6                h975169c_2    conda-forge
re2                       2023.09.01           hd3b24a8_2    conda-forge
setuptools                75.6.0             pyhff2d567_1    conda-forge
snappy                    1.2.1                h500f7fa_1    conda-forge
spdlog                    1.13.0               h64d2f7d_0    conda-forge
sqlite                    3.47.2               h2466b09_0    conda-forge
svt-av1                   2.3.0                he0c23c2_0    conda-forge
tbb                       2021.13.0            h62715c5_1    conda-forge
tiledb                    2.21.2               hf39fa12_4    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_1    conda-forge
uriparser                 0.9.8                h5a68840_0    conda-forge
vc                        14.3                ha32ba9b_23    conda-forge
vc14_runtime              14.42.34433         he29a5d6_23    conda-forge
vs2015_runtime            14.42.34433         hdffcdeb_23    conda-forge
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xerces-c                  3.2.5                he0c23c2_2    conda-forge
xz                        5.6.3                h208afaa_1    conda-forge
xz-tools                  5.6.3                h2466b09_1    conda-forge
zlib                      1.3.1                h2466b09_2    conda-forge
zstd                      1.5.6                h0ea2cb4_0    conda-forge
```

### Environment info

```shell
active environment : test2
    active env location : redacted_path\anaconda3\envs\test2
            shell level : 2
       user config file : redacted_path\.condarc
 populated config files : redacted_path\.condarc
          conda version : 24.1.2
    conda-build version : 24.1.2
         python version : 3.11.7.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64
                          __conda=24.1.2=0
                          __cuda=12.6=0
                          __win=0=0
       base environment : redacted_path\anaconda3  (writable)
      conda av data dir : redacted_path\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/loop3d/win-64
                          https://conda.anaconda.org/loop3d/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : redacted_path\anaconda3\pkgs
                          redacted_path\.conda\pkgs
                          redacted_path\AppData\Local\conda\conda\pkgs
       envs directories : redacted_path\anaconda3\envs
                          redacted_path\.conda\envs
                          redacted_path\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/24.1.2 requests/2.31.0 CPython/3.11.7 Windows/10 Windows/10.0.22631 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.6 aau/0.4.3 c/c7il5EE9E8zPuMSWolKFkw s/BAP9BXV8QU6GkB3Aj_tjoQ e/KUf1wQOvlPRqmspfavAK4w
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by rouault** [comment]
@conda-forge/gdal maintainers. I've also replicated that locally earlier tonight on my Windows VM, and I can see that current https://github.com/conda-forge/gdal-feedstock/pull/1023 PR is broken in https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1106557&view=logs&j=fe7faf59-69bb-5487-b8fd-a35a7bda3a51&t=55731638-dd49-5144-2129-5101b9dd1960  because of 
```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/win-64::libkml-1.3.0-h538826c_1021, conda-forge/win-64::minizip-4.0.7-h9fa1bad_1
  path: 'library/lib/minizip.lib'
```
I believe the reason is that libspatialite-feedstock needs a rebuild. Its current build has been done against minizip-4.0.6, where minizip was released as libminizip.lib/.dll, but since minizip-4.0.7 it has been renamed as minizip.lib/.dll.

**Comment by rouault** [comment]
> I believe the reason is that libspatialite-feedstock needs a rebuild

==> https://github.com/conda-forge/libspatialite-feedstock/pull/115

**Comment by rouault** [comment]
Actually I'm wrong. The package that needs a rebuild and has a real dependency on minizip is freexl: https://github.com/conda-forge/freexl-feedstock/pull/31

**Comment by akrherz** [comment]
@AngRodrigues This should be fixed now with a more recent `minizip` build.  Could you kindly confirm?

**Comment by AngRodrigues** [comment]
Confirming it works. Thank you for looking into it!
