### ISSUE TITLE
libuuid not getting installed?

### ISSUE THREAD

**Issue by jseabold** [conda-forge/gdal-feedstock#123]
I ran into this installing fiona, but this appears to be a problem with gdal. In a fresh conda environment, containing only ipython.

```
|10112 $ conda --version
conda 4.1.8
```

```
|10105 $ conda install -c conda-forge fiona
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /Users/user/.miniconda3/envs/temp:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgfortran-3.0.0          |                0         465 KB  conda-forge
    mkl-11.3.3                 |                0       101.4 MB  defaults
    ------------------------------------------------------------
                                           Total:       101.9 MB

The following NEW packages will be INSTALLED:

    click:         6.6-py35_1        conda-forge
    click-plugins: 1.0.3-py35_0      conda-forge
    cligj:         0.4.0-py35_0      defaults
    curl:          7.49.1-1          conda-forge
    expat:         2.1.0-2           conda-forge
    fiona:         1.7.0-np111py35_2 conda-forge
    freexl:        1.0.2-1           conda-forge
    gdal:          2.1.1-np111py35_5 conda-forge
    geos:          3.4.2-2           conda-forge
    giflib:        5.1.4-0           conda-forge
    hdf4:          4.2.12-0          conda-forge
    hdf5:          1.8.17-7          conda-forge
    icu:           56.1-4            conda-forge
    jpeg:          9b-0              conda-forge
    json-c:        0.12-0            conda-forge
    kealib:        1.4.6-3           conda-forge
    libdap4:       3.18.0-4          conda-forge
    libgfortran:   3.0.0-0           conda-forge
    libiconv:      1.14-3            conda-forge
    libnetcdf:     4.4.1-0           conda-forge
    libpng:        1.6.24-0          conda-forge
    libpq:         9.5.4-3           conda-forge
    libspatialite: 4.3.0a-10         conda-forge
    libtiff:       4.0.6-6           conda-forge
    libxml2:       2.9.4-2           conda-forge
    mkl:           11.3.3-0          defaults
    munch:         2.0.4-py35_0      conda-forge
    numpy:         1.11.2-py35_0     defaults
    openjpeg:      2.1.2-1           conda-forge
    proj.4:        4.9.3-0           conda-forge
    xerces-c:      3.1.4-2           conda-forge
```

```
>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/.miniconda3/envs/temp/lib/python3.5/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/Users/user/.miniconda3/envs/temp/lib/python3.5/site-packages/fiona/collection.py", line 7, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/user/.miniconda3/envs/temp/lib/python3.5/site-packages/fiona/ogrext.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libuuid.1.dylib
  Referenced from: /Users/user/.miniconda3/envs/temp/lib/libgdal.20.dylib
  Reason: image not found
```

Doing

```
conda install -c conda-forge libuuid
```

Solves the problem. Shouldn't libuuid be a transitive dependency met via gdal? Does it need to be added to the meta.yaml file?

**Comment by ocefpaf** [comment]
@jseabold you got us in the middle of a transition. Hopefully that will go away as soon as we merge https://github.com/conda-forge/gdal-feedstock/pull/122 (and `libuuid` won't be needed).

I am keeping this open until we merge and and test #122.

**Comment by ocefpaf** [comment]
@jseabold let me know if this is fixed for you.

**Comment by jseabold** [comment]
lgtm
