### ISSUE TITLE
Gdal "image not found"

### ISSUE THREAD

**Issue by grantdelozier** [conda-forge/gdal-feedstock#178]
Hi there,

Appreciate your work on this project. I had some trouble installing on Mac OSX 10.12.5

```
Grants-MacBook-Pro:Tampy grantdelozier$ conda config --add channels conda-forge
Grants-MacBook-Pro:Tampy grantdelozier$ conda install gdal
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /usr/local/anaconda3:

The following NEW packages will be INSTALLED:

    gdal: 2.2.2-py36_0 conda-forge

Proceed ([y]/n)? y

Grants-MacBook-Pro:Tampy grantdelozier$ python
Python 3.6.1 |Anaconda custom (x86_64)| (default, May 11 2017, 13:04:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import osgeo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.6/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/usr/local/anaconda3/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/local/anaconda3/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/usr/local/anaconda3/lib/python3.6/site-packages/osgeo/_gdal.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libssh2.1.dylib
  Referenced from: /usr/local/anaconda3/lib/libgdal.20.dylib
  Reason: image not found
>>> 
```

I'm not sure how to parse this error message, any idea how to fix it?

**Comment by grantdelozier** [comment]
Ah it was something with the environment messing it up. I wanted root to be able to run it, but looks like I'll have to use environments

```
conda create -n GDAL python=3.6 gdal
source activate GDAL

```
closing

**Comment by grantdelozier** [comment]
Might be helpful to include those couple lines in the readme
