### ISSUE TITLE
Error importing gdal in root environment

### ISSUE THREAD

**Issue by Auerilas** [conda-forge/gdal-feedstock#182]
Hi,
I just installed conda in my root environment (which I typically use):

`conda install gdal`

Everything installed OK, but when I load python and try to import gdal, I get a strange error:
```
python
Python 3.6.2 |Anaconda custom (64-bit)| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ralien/anaconda3/lib/python3.6/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/ralien/anaconda3/lib/python3.6/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/ralien/anaconda3/lib/python3.6/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/ralien/anaconda3/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ralien/anaconda3/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/ralien/anaconda3/lib/python3.6/site-packages/osgeo/../../../libgdal.so.20: undefined symbol: _ZN9kmlengine4Href5ParseERKSs
```
It seems like there is a dependency issue, because I created a new environment, installed gdal, and everything loaded OK.

```
conda --create gdal_test gdal
source activate gdal_test
(gdal_test): python
Python 3.6.3 | packaged by conda-forge | (default, Oct  5 2017, 14:07:33) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdal
```

Here are the package lists for the root envionment:
```
conda list
# packages in environment at /home/ralien/anaconda3:
#
_ipyw_jlab_nb_ext_conf    0.1.0            py36he11e457_0  
alabaster                 0.7.10                   py36_1    conda-forge
anaconda                  custom                   py36_0  
anaconda-client           1.6.5                      py_0    conda-forge
anaconda-navigator        1.6.8            py36h672ccc7_0  
anaconda-project          0.8.0                    py36_0    conda-forge
asn1crypto                0.22.0                   py36_0    conda-forge
astroid                   1.5.3                    py36_0    conda-forge
astropy                   2.0.2               np113py36_1    conda-forge
babel                     2.4.0                    py36_0    conda-forge
backports                 1.0                      py36_1    conda-forge
backports.functools_lru_cache 1.4                      py36_1    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
beautifulsoup4            4.6.0                    py36_0    conda-forge
bitarray                  0.8.1                    py36_0    conda-forge
bkcharts                  0.2                      py36_0    conda-forge
blas                      1.1                    openblas    conda-forge
blaze                     0.11.3                   py36_0    conda-forge
bleach                    2.0.0                    py36_0    conda-forge
blinker                   1.4                      py36_0    conda-forge
bokeh                     0.12.9                   py36_0    conda-forge
boto                      2.48.0           py36h6e4cd66_1  
bottleneck                1.2.1                    py36_1    conda-forge
bz2file                   0.98                     py36_0  
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
cairo                     1.14.6                        4    conda-forge
certifi                   2017.7.27.1              py36_0    conda-forge
cffi                      1.10.0                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
click                     6.7                      py36_0    conda-forge
cloudpickle               0.4.0                    py36_0    conda-forge
clyent                    1.2.2                    py36_0    conda-forge
colorama                  0.3.9                    py36_0    conda-forge
conda                     4.3.29                   py36_0    conda-forge
conda-build               2.1.17                   py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-verify              2.0.0                    py36_0    conda-forge
contextlib2               0.5.5                    py36_0    conda-forge
cryptography              2.0.3                    py36_0    conda-forge
curl                      7.52.1                        0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
cython                    0.27.1                   py36_0    conda-forge
cytoolz                   0.8.2                    py36_0    conda-forge
dask                      0.15.3                     py_0    conda-forge
dask-core                 0.15.3                     py_0    conda-forge
datashape                 0.5.4                    py36_0    conda-forge
dbus                      1.10.22                       0    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
distributed               1.19.1                   py36_0    conda-forge
docutils                  0.14                     py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
et_xmlfile                1.0.1                    py36_0    conda-forge
expat                     2.2.1                         0    conda-forge
fastcache                 1.0.2                    py36_0    conda-forge
filelock                  2.0.6                    py36_0    conda-forge
flask                     0.12.2                   py36_0    conda-forge
flask-cors                3.0.3                    py36_0    conda-forge
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
freexl                    1.0.2                         2    conda-forge
gdal                      2.2.2                    py36_0    conda-forge
gensim                    3.0.0                    py36_0    conda-forge
geos                      3.5.1                         1    conda-forge
get_terminal_size         1.0.0                haa9412d_0  
gettext                   0.19.7                        1    conda-forge
gevent                    1.2.2                    py36_0    conda-forge
giflib                    5.1.4                         0    conda-forge
glib                      2.51.4                        0    conda-forge
glob2                     0.5                      py36_0    conda-forge
gmp                       6.1.2                         0    conda-forge
gmpy2                     2.0.8                    py36_1    conda-forge
graphite2                 1.3.9                         0    conda-forge
greenlet                  0.4.12                   py36_0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         2    conda-forge
h5py                      2.7.1                    py36_1    conda-forge
harfbuzz                  1.4.3                         0    conda-forge
hdf4                      4.2.12                        0    conda-forge
hdf5                      1.8.18                        0    conda-forge
heapdict                  1.0.0                    py36_0    conda-forge
html5lib                  0.999999999              py36_0    conda-forge
icu                       58.2                 h211956c_0  
idna                      2.6                      py36_1    conda-forge
imageio                   2.2.0                    py36_0    conda-forge
imagesize                 0.7.1                    py36_0    conda-forge
intel-openmp              2018.0.0             h15fc484_7  
ipykernel                 4.6.1                    py36_0    conda-forge
ipython                   6.2.1                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                7.0.1                      py_2    conda-forge
isort                     4.2.15                   py36_0    conda-forge
itsdangerous              0.24                       py_2    conda-forge
jbig                      2.1                           0    conda-forge
jdcal                     1.3                      py36_0    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jinja2                    2.9.6                    py36_0    conda-forge
jpeg                      9b                            1    conda-forge
json-c                    0.12.1                        0    conda-forge
jsonschema                2.6.0                    py36_0    conda-forge
jupyter                   1.0.0                    py36_0    conda-forge
jupyter_client            5.1.0                    py36_0    conda-forge
jupyter_console           5.1.0                    py36_0    conda-forge
jupyter_core              4.3.0                    py36_0    conda-forge
jupyterlab                0.27.0                   py36_1    conda-forge
jupyterlab_launcher       0.5.1                    py36_0    conda-forge
kealib                    1.4.7                         3    conda-forge
krb5                      1.14.2                        0    conda-forge
lazy-object-proxy         1.3.1                    py36_0    conda-forge
libboost                  1.65.1               h4055789_3  
libdap4                   3.18.3                        2    conda-forge
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                         3    conda-forge
libgcc-ng                 7.2.0                hcbc56d2_1  
libgdal                   2.2.2                         3    conda-forge
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                h6fcbd8e_1  
libiconv                  1.14                          4    conda-forge
libkml                    1.3.0                h8777076_2  
libnetcdf                 4.4.1.1                       5    conda-forge
libpng                    1.6.32               hda9c8bc_2  
libpq                     9.6.3                         0    conda-forge
libsodium                 1.0.10                        0    conda-forge
libspatialite             4.3.0a                       15    conda-forge
libssh2                   1.8.0                         1    conda-forge
libstdcxx-ng              7.2.0                h24385c6_1  
libtiff                   4.0.8                h90200ff_9  
libtool                   2.4.6                         0    conda-forge
libxcb                    1.12                          1    conda-forge
libxml2                   2.9.5                         0    conda-forge
libxslt                   1.1.29                        5    conda-forge
llvmlite                  0.20.0                   py36_0  
locket                    0.2.0                    py36_1    conda-forge
lxml                      4.0.0                    py36_0    conda-forge
lzo                       2.10                          0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.1.0                    py36_0    conda-forge
mccabe                    0.6.1                    py36_0    conda-forge
mistune                   0.7.4                    py36_0    conda-forge
mkl                       2018.0.0             hb491cac_4  
mkl-service               1.1.2            py36h17a0993_4  
mpc                       1.0.3                         4    conda-forge
mpfr                      3.1.5                         0    conda-forge
mpmath                    1.0.0                      py_0    conda-forge
msgpack-python            0.4.8                    py36_0    conda-forge
multipledispatch          0.4.9                    py36_0    conda-forge
navigator-updater         0.1.0            py36h14770f7_0  
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
ncurses                   6.0                  h06874d7_1  
networkx                  2.0                      py36_0    conda-forge
nltk                      3.2.5                      py_0    conda-forge
nose                      1.3.7                    py36_2    conda-forge
notebook                  5.1.0                    py36_0    conda-forge
numba                     0.35.0             np113py36_10  
numexpr                   2.6.4                    py36_0    conda-forge
numpy                     1.13.3          py36_blas_openblas_200  [blas_openblas]  conda-forge
numpydoc                  0.7.0                    py36_0    conda-forge
oauthlib                  2.0.4                      py_0    conda-forge
odo                       0.5.1                    py36_0    conda-forge
olefile                   0.44                     py36_0    conda-forge
openblas                  0.2.19                        2    conda-forge
openjpeg                  2.1.2                         3    conda-forge
openpyxl                  2.5.0a3                  py36_0    conda-forge
openssl                   1.0.2l                        0    conda-forge
packaging                 16.8                     py36_0    conda-forge
pandas                    0.20.3                   py36_1    conda-forge
pandoc                    1.19.2                        0    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
pango                     1.40.4                        0    conda-forge
partd                     0.3.8                    py36_0    conda-forge
patchelf                  0.9                           2    conda-forge
path.py                   10.3.1                   py36_0    conda-forge
pathlib2                  2.3.0                    py36_0    conda-forge
patsy                     0.4.1                    py36_0    conda-forge
pcre                      8.39                          0    conda-forge
pep8                      1.7.0                    py36_0    conda-forge
pexpect                   4.2.1                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pillow                    4.2.1                    py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
pixman                    0.34.0                        0    conda-forge
pkginfo                   1.4.1                    py36_0    conda-forge
ply                       3.10                     py36_0    conda-forge
poppler                   0.52.0                        2    conda-forge
poppler-data              0.4.7                         0    conda-forge
proj4                     4.9.3                         4    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.3.1                    py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
py                        1.4.34                   py36_0    conda-forge
pycodestyle               2.3.1                    py36_0    conda-forge
pycosat                   0.6.2                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pycrypto                  2.6.1                    py36_1    conda-forge
pycurl                    7.43.0                   py36_2  
pyflakes                  1.6.0                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pyjwt                     1.5.3                      py_0    conda-forge
pylint                    1.7.1                    py36_0    conda-forge
pyodbc                    4.0.17                   py36_0    conda-forge
pyopenssl                 17.2.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pysocks                   1.6.7                    py36_0    conda-forge
pystan                    2.17.0.0                 py36_0    conda-forge
pytables                  3.4.2            py36hc5f0ea4_2  
pytest                    3.2.2                    py36_1    conda-forge
python                    3.6.2                         0  
python-crfsuite           0.9.2                    py36_0    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2017.2                   py36_0    conda-forge
pywavelets                0.5.2               np113py36_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
pyzmq                     16.0.2                   py36_2    conda-forge
qt                        5.6.2                         3    conda-forge
qtawesome                 0.4.4                    py36_0    conda-forge
qtconsole                 4.3.1                    py36_0    conda-forge
qtpy                      1.3.1                    py36_0    conda-forge
readline                  6.2                           2  
requests                  2.18.4                   py36_1    conda-forge
requests-oauthlib         0.8.0                    py36_1    conda-forge
rope                      0.10.7                   py36_0    conda-forge
ruamel_yaml               0.11.14                  py36_0    conda-forge
scikit-image              0.13.0                   py36_2    conda-forge
scikit-learn              0.19.0          py36_blas_openblas_201  [blas_openblas]  conda-forge
scipy                     0.19.1          py36_blas_openblas_202  [blas_openblas]  conda-forge
seaborn                   0.8.1                    py36_0    conda-forge
setuptools                36.3.0                   py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
singledispatch            3.4.0.3                  py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
smart_open                1.5.3                    py36_0    conda-forge
snowballstemmer           1.2.1                    py36_0    conda-forge
sortedcollections         0.5.3                    py36_0    conda-forge
sortedcontainers          1.5.7                    py36_0    conda-forge
sphinx                    1.6.4                    py36_0    conda-forge
sphinxcontrib             1.0              py36h6d0f590_1  
sphinxcontrib-websupport  1.0.1                    py36_0    conda-forge
spyder                    3.2.3                    py36_0    conda-forge
sqlalchemy                1.1.13                   py36_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
statsmodels               0.8.0                    py36_0    conda-forge
sympy                     1.1.1                    py36_0    conda-forge
tblib                     1.3.2                    py36_0    conda-forge
terminado                 0.6                      py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tk                        8.5.18                        0  
toolz                     0.8.2                      py_2    conda-forge
tornado                   4.5.2                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
twython                   3.6.0                    py36_0    conda-forge
typing                    3.6.2                    py36_0    conda-forge
unicodecsv                0.14.1                   py36_0    conda-forge
unixodbc                  2.3.4                         1    conda-forge
urllib3                   1.22                     py36_0    conda-forge
util-linux                2.21                          0  
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
werkzeug                  0.12.2                     py_1    conda-forge
wheel                     0.30.0                     py_1    conda-forge
widgetsnbextension        3.0.3                    py36_2    conda-forge
wrapt                     1.10.11                  py36_0    conda-forge
xerces-c                  3.1.4                         3    conda-forge
xlrd                      1.0.0                    py36_1    conda-forge
xlsxwriter                0.9.8                    py36_0    conda-forge
xlwt                      1.3.0                    py36_0    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                         0    conda-forge
yaml                      0.1.6                         0    conda-forge
zeromq                    4.2.1                         1    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11                        0    conda-forge
```

and for the test environment;

```
# packages in environment at /home/ralien/anaconda3/envs/gdal_test:
#
boost                     1.64.0                   py36_4    conda-forge
boost-cpp                 1.64.0                        1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
cairo                     1.14.6                        4    conda-forge
certifi                   2017.7.27.1              py36_0    conda-forge
curl                      7.54.1                        0    conda-forge
expat                     2.1.0                         3    conda-forge
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
freexl                    1.0.2                         2    conda-forge
gdal                      2.2.2                    py36_0    conda-forge
geos                      3.5.1                         1    conda-forge
gettext                   0.19.7                        1    conda-forge
giflib                    5.1.4                         0    conda-forge
glib                      2.51.4                        0    conda-forge
hdf4                      4.2.12                        0    conda-forge
hdf5                      1.8.18                        1    conda-forge
icu                       58.1                          1    conda-forge
intel-openmp              2018.0.0             h15fc484_7  
jpeg                      9b                            1    conda-forge
json-c                    0.12.1                        0    conda-forge
kealib                    1.4.7                         3    conda-forge
krb5                      1.14.2                        0    conda-forge
libdap4                   3.18.3                        2    conda-forge
libffi                    3.2.1                         3    conda-forge
libgdal                   2.2.2                         4    conda-forge
libgfortran               3.0.0                         1  
libiconv                  1.14                          4    conda-forge
libkml                    1.3.0                         1    conda-forge
libnetcdf                 4.4.1.1                       7    conda-forge
libpng                    1.6.28                        1    conda-forge
libpq                     9.6.3                         0    conda-forge
libspatialite             4.3.0a                       15    conda-forge
libssh2                   1.8.0                         1    conda-forge
libtiff                   4.0.7                         0    conda-forge
libxml2                   2.9.5                         0    conda-forge
mkl                       2018.0.0             hb491cac_4  
ncurses                   5.9                          10    conda-forge
numpy                     1.13.3           py36ha12f23b_0  
openjpeg                  2.1.2                         3    conda-forge
openssl                   1.0.2l                        0    conda-forge
pcre                      8.39                          0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
pixman                    0.34.0                        0    conda-forge
poppler                   0.52.0                        2    conda-forge
poppler-data              0.4.7                         0    conda-forge
proj4                     4.9.3                         4    conda-forge
python                    3.6.3                         0    conda-forge
readline                  6.2                           0    conda-forge
setuptools                36.6.0                   py36_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        2    conda-forge
util-linux                2.21                          0  
wheel                     0.30.0                     py_1    conda-forge
xerces-c                  3.1.4                         3    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.8                         3    conda-forge
```

I know sometimes there are issues with krb5, but that doesn't seem to be the case here. Thoughts?

I'm running Linux Mint 18.3 (essentially Ubuntu 16.04)

**Comment by ocefpaf** [comment]
For some reason you got `libgdal` build number 3 there and that probably has an issue with a recent change in `kealib`. However, there is no reason why conda chose 3 in instead of 4 :unamused: 

Anyway, I removed all build number but 4 and in theory everything should work now.
Can you try it and report back?

**Comment by Auerilas** [comment]
There's still a dependency conflict with build 4. Attempting to reinstall libgdal dropped me down a version (libgdal 2.2.1, build2), and it still didn't work. When I tried to force an install of libgdal 2.2.2 build 4, I got a conflict.

```
conda install libgdal
Fetching package metadata .............
Solving package specifications: .
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-forge::gdal-2.2.1-np113py36_0
  - conda-forge::gdal-2.2.1-py36_0

Package plan for installation in environment /home/ralien/anaconda3:

The following packages will be SUPERSEDED by a higher-priority channel:

    libgdal: 2.2.2-3      conda-forge --> 2.2.1-2           conda-forge

The following packages will be DOWNGRADED:

    gdal:    2.2.2-py36_0 conda-forge --> 2.2.1-np113py36_0 conda-forge

Proceed ([y]/n)? y

libgdal-2.2.1- 100% |################################| Time: 0:01:20   1.52 MB/s
gdal-2.2.1-np1 100% |################################| Time: 0:00:01   1.47 MB/s
ralien@mint-top ~ $ conda list gdal
# packages in environment at /home/ralien/anaconda3:
#
gdal                      2.2.1               np113py36_0    conda-forge
libgdal                   2.2.1                         2    conda-forge
ralien@mint-top ~ $ python
Python 3.6.2 |Anaconda custom (64-bit)| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ralien/anaconda3/lib/python3.6/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/ralien/anaconda3/lib/python3.6/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/ralien/anaconda3/lib/python3.6/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/ralien/anaconda3/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ralien/anaconda3/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/ralien/anaconda3/lib/python3.6/site-packages/osgeo/../../../libgdal.so.20: undefined symbol: _ZN9kmlengine4Href5ParseERKSs
>>> exit()
ralien@mint-top ~ $ remove libgdal
remove: command not found
ralien@mint-top ~ $ conda remove libgdal
Fetching package metadata .............
Solving package specifications: .

Package plan for package removal in environment /home/ralien/anaconda3:

The following packages will be REMOVED:

    gdal:    2.2.1-np113py36_0 conda-forge
    libgdal: 2.2.1-2           conda-forge

Proceed ([y]/n)? y

ralien@mint-top ~ $ conda install gdal
Fetching package metadata .............
Solving package specifications: .
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-forge::gdal-2.2.1-np113py36_0
  - conda-forge::gdal-2.2.1-py36_0

Package plan for installation in environment /home/ralien/anaconda3:

The following NEW packages will be INSTALLED:

    gdal:    2.2.1-np113py36_0 conda-forge
    libgdal: 2.2.1-2           conda-forge

Proceed ([y]/n)? y

ralien@mint-top ~ $ conda list gdal
# packages in environment at /home/ralien/anaconda3:
#
gdal                      2.2.1               np113py36_0    conda-forge
libgdal                   2.2.1                         2    conda-forge
ralien@mint-top ~ $ python
Python 3.6.2 |Anaconda custom (64-bit)| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ralien/anaconda3/lib/python3.6/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/ralien/anaconda3/lib/python3.6/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/ralien/anaconda3/lib/python3.6/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/ralien/anaconda3/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ralien/anaconda3/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/ralien/anaconda3/lib/python3.6/site-packages/osgeo/../../../libgdal.so.20: undefined symbol: _ZN9kmlengine4Href5ParseERKSs
>>> exit()
ralien@mint-top ~ $ conda install libgdal=4
Fetching package metadata .............

PackageNotFoundError: Packages missing in current channels:
            
  - libgdal 4*

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch
            

ralien@mint-top ~ $ conda install libgdal=2.2=4
Fetching package metadata .............

PackageNotFoundError: Packages missing in current channels:
            
  - libgdal 2.2 4

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch
            

ralien@mint-top ~ $ conda search libgdal
Fetching package metadata .............
libgdal                      1.11.2                        0  defaults        
                             1.11.2                        1  defaults        
                             1.11.2                        2  defaults        
                             2.0.0                         0  defaults        
                             2.0.0                         1  defaults        
                             2.0.0                         2  defaults        
                             2.1.0                         0  defaults        
                             2.1.4                         3  conda-forge     
                             2.2.0                         0  conda-forge     
                             2.2.1                         0  conda-forge     
                             2.2.1                         1  conda-forge     
                          *  2.2.1                         2  conda-forge     
                             2.2.2                         4  conda-forge     
ralien@mint-top ~ $ conda install libgdal=2.2.2=4
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - libboost
  - libgdal 2.2.2 4 -> zlib 1.2.8
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by Auerilas** [comment]
I was able to get it to work by forcing a remove of libboost and reinstalling gdal. This resolved the zlib issue:

```
conda remove libboost
Fetching package metadata .............
Solving package specifications: .

Package plan for package removal in environment /home/ralien/anaconda3:

The following packages will be REMOVED:

    gdal:     2.2.1-np113py36_0 conda-forge
    libboost: 1.65.1-h4055789_3            
    libgdal:  2.2.1-2           conda-forge
    libkml:   1.3.0-h8777076_2             

Proceed ([y]/n)? y

ralien@mint-top ~ $ conda remove zlib
Fetching package metadata .............
Solving package specifications: .

RemoveError: Error: this 'remove' command cannot be executed because it
would require removing 'conda' dependencies

ralien@mint-top ~ $ conda install gdal
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /home/ralien/anaconda3:

The following NEW packages will be INSTALLED:

    boost:     1.64.0-py36_4        conda-forge
    boost-cpp: 1.64.0-1             conda-forge
    gdal:      2.2.2-py36_0         conda-forge
    libgdal:   2.2.2-4              conda-forge
    libkml:    1.3.0-1              conda-forge

The following packages will be UPDATED:

    pytables:  3.4.2-py36hc5f0ea4_2             --> 3.4.2-py36_5 conda-forge

The following packages will be SUPERSEDED by a higher-priority channel:

    libpng:    1.6.32-hda9c8bc_2                --> 1.6.28-1     conda-forge
    libtiff:   4.0.8-h90200ff_9                 --> 4.0.7-0      conda-forge

The following packages will be DOWNGRADED:

    expat:     2.2.1-0              conda-forge --> 2.1.0-3      conda-forge
    zlib:      1.2.11-0             conda-forge --> 1.2.8-3      conda-forge

Proceed ([y]/n)? y

pytables-3.4.2 100% |###################################################################################| Time: 0:00:05   1.40 MB/s
ralien@mint-top ~ $ python
Python 3.6.2 |Anaconda custom (64-bit)| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdal
>>> exit()
```

Seems to have done it, no more import errors.
