### ISSUE TITLE
Import error with undefined symbol

### ISSUE THREAD

**Issue by mccarthyryanc** [conda-forge/gdal-feedstock#189]
I'm getting this error after installing in Ubuntu 16.04:

```
$ python -c 'import gdal'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/miniconda3/envs/gdal-env/lib/python3.5/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/ubuntu/miniconda3/envs/gdal-env/lib/python3.5/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/ubuntu/miniconda3/envs/gdal-env/lib/python3.5/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/ubuntu/miniconda3/envs/gdal-env/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ubuntu/miniconda3/envs/gdal-env/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/ubuntu/miniconda3/envs/gdal-env/lib/python3.5/site-packages/osgeo/../../.././libcurl.so.4: undefined symbol: libssh2_scp_recv2 
```

Installed via conda with:
```
conda create -n gdal-env python=3.5 gdal -c conda-forge
```

**Comment by mccarthyryanc** [comment]
Perhaps this is actually an error with [curl](https://github.com/conda-forge/curl-feedstock/issues/23)?

**Comment by ocefpaf** [comment]
Same answer from https://github.com/conda-forge/rasterio-feedstock/issues/48#issuecomment-346405164 :smile:

**Comment by ocefpaf** [comment]
> Perhaps this is actually an error with curl?

Please see my answer before opening another issue :wink:

**Comment by ocefpaf** [comment]
Closing this and will follow it in the curl feedstock. Thanks for the report @mccarthyryanc!
