### ISSUE TITLE
libgdal error on import gdal with rsgislib

### ISSUE THREAD

**Issue by samfranklin** [conda-forge/gdal-feedstock#216]
Issue:

Hi. I'm getting a libgdal error when trying to use gdal after installing the package `rsgislib`. I've seen a similar type issue before and suspect it's due to a mix of channels between `conda-forge` and `defaults`.

The short version is that I think what is happening is when I install `rsgislib`. I think this package requires gdal `2.2.2` which is not currently in conda-forge. Therefore gets gdal `2.2.2` from the `defaults` channel.

Note, I've followed the conda-forge gotcha regarding the .condarc file in $HOME. Here's my .condarc file:

```
$ cat .condarc
channels:
  - conda-forge
  - defaults
show_channel_urls: true
```

I noticed the other (currently open) issue [#215](https://github.com/conda-forge/gdal-feedstock/issues/215) where you mentioned there were some issues, so if this is related, apologies for a opening a new issue.

Any thoughts or pointers on how I can solve would be greatly appreciated. Thanks!

#### My Error
```
$ conda create -n rsgislibenv rsgislib
$ conda activate rsgislibenv
(rsgislibenv) $ python -c "from osgeo import gdal"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/samfranklin/anaconda3/envs/rsgislibenv/lib/python3.5/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/Users/samfranklin/anaconda3/envs/rsgislibenv/lib/python3.5/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/Users/samfranklin/anaconda3/envs/rsgislibenv/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/samfranklin/anaconda3/envs/rsgislibenv/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/samfranklin/anaconda3/envs/rsgislibenv/lib/python3.5/site-packages/osgeo/_gdal.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libpoppler.71.dylib
  Referenced from: /Users/samfranklin/anaconda3/envs/rsgislibenv/lib/libgdal.20.dylib
  Reason: image not found
```

<br/>
Environment (<code>conda list</code>):
<details>

```
(rsgislibenv) Sams-Air:~ samfranklin$ conda list
# packages in environment at /Users/samfranklin/anaconda3/envs/rsgislibenv:
#
# Name                    Version                   Build  Channel
boost                     1.66.0                   py35_1    conda-forge
boost-cpp                 1.66.0                        1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.12              he56eebe_3    conda-forge
certifi                   2018.4.16                py35_0    conda-forge
cgal                      4.12                     py35_0    conda-forge
clangdev                  6.0.0                 default_0    conda-forge
curl                      7.61.0               h93b3f91_0    conda-forge
expat                     2.2.5                hfc679d8_1    conda-forge
fontconfig                2.13.0               h074f895_3    conda-forge
freetype                  2.8.1                         0    conda-forge
freexl                    1.0.5                hf837533_1    conda-forge
gdal                      2.2.2            py35h7aa31b1_1    defaults
geos                      3.6.2                hfc679d8_2    conda-forge
gettext                   0.19.8.1                      0    conda-forge
giflib                    5.1.4                h470a237_0    conda-forge
glib                      2.55.0                        0    conda-forge
gmp                       6.1.2                hfc679d8_0    conda-forge
gsl                       2.2.1                h002c638_3    defaults
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1                        2    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
intel-openmp              2018.0.3                      0    defaults
jpeg                      9c                   h470a237_0    conda-forge
json-c                    0.12.1                        0    conda-forge
kealib                    1.4.8                hfc679d8_0    conda-forge
krb5                      1.14.6                        0    conda-forge
libcxx                    6.0.0                         0    conda-forge
libdap4                   3.19.1                        0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgdal                   2.2.2                h3559a57_1    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 h470a237_1    conda-forge
libkml                    1.3.0                         6    conda-forge
libnetcdf                 4.4.1.1                      10    conda-forge
libpng                    1.6.34               ha92aebf_1    conda-forge
libpq                     10.3                 hf30b1f0_0    defaults
libspatialite             4.3.0a              h3b29d86_21    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libtiff                   4.0.9                he6b73bb_1    conda-forge
libxml2                   2.9.8                h422b904_2    conda-forge
llvm-meta                 6.0.0                         0    conda-forge
llvmdev                   6.0.0                 default_4    conda-forge
mkl                       2018.0.3                      1    defaults
mkl_fft                   1.0.4                    py35_0    conda-forge
mkl_random                1.0.1                    py35_0    conda-forge
mpfr                      4.0.1                h16a7912_0    conda-forge
muparser                  2.2.5                         3    conda-forge
ncurses                   6.1                           0    conda-forge
numpy                     1.14.2           py35ha9ae307_1    defaults
openjpeg                  2.3.0                h316dc23_3    conda-forge
openssl                   1.0.2o                        0    conda-forge
pcre                      8.41                          1    conda-forge
pip                       18.0                     py35_0    conda-forge
pixman                    0.34.0                        2    conda-forge
poppler                   0.67.0               hb55ee21_0    conda-forge
poppler-data              0.4.9                         0    conda-forge
proj4                     4.9.3                         5    conda-forge
python                    3.5.5                h5001a0f_2    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
rsgislib                  3.5.7                    py35_3    conda-forge
setuptools                40.0.0                   py35_0    conda-forge
sqlite                    3.24.0               h2f33b56_0    conda-forge
tk                        8.6.8                         0    conda-forge
wheel                     0.31.1                   py35_0    conda-forge
xerces-c                  3.2.0                         0    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
(rsgislibenv) Sams-Air:~ samfranklin$ conda info

     active environment : rsgislibenv
    active env location : /Users/samfranklin/anaconda3/envs/rsgislibenv
            shell level : 1
       user config file : /Users/samfranklin/.condarc
 populated config files : /Users/samfranklin/.condarc
          conda version : 4.5.8
    conda-build version : 3.4.1
         python version : 3.6.5.final.0
       base environment : /Users/samfranklin/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/samfranklin/anaconda3/pkgs
                          /Users/samfranklin/.conda/pkgs
       envs directories : /Users/samfranklin/anaconda3/envs
                          /Users/samfranklin/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.8 requests/2.18.4 CPython/3.6.5 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False


```
</details>

**Comment by gillins** [comment]
I think we need to rebuild `rsgislib` against `libgdal` 2.3.x, but we can't currently due to `cgal` not being pinned to the same `boost` as everything else... (see https://github.com/conda-forge/rsgislib-feedstock/pull/13 and https://github.com/conda-forge/spdlib-feedstock/pull/1#issuecomment-407864876)

**Comment by ocefpaf** [comment]
There is a problem with `gdal 2.2.x` that I'm fixing and should probably have an effect here.

Regarding `gdal 2.3.x`, we are held back by `fiona` and `rasterio`, as long as those do not work with the 2.3.x series we cannot update the global pinning. However, if you don't care about `rsgislib` getting installed alongside `fiona` and `rasterio` you can override the global pinning and move to `gdal 2.3.1` ahead of the rest of the stack on conda-forge.

**Comment by samfranklin** [comment]
Hi @ocefpaf and @gillins - thanks so much for coming back. Much appreciated.

You're right. I'm not bothered about getting `rasterio` and `fiona` working within the same environment. However, I do want to use the `arcsi` package though. I stepped back and just tried to get rsgislib and gdal working in the same environment. I understand `arcsi` is closely related to `rsgislib`.

I just tried to follow your suggestion:

> However, if you don't care about rsgislib getting installed alongside fiona and rasterio you can override the global pinning and move to gdal 2.3.1 ahead of the rest of the stack on conda-forge.

by creating a environment and specifying the versions. I get a conflict warning.

```
$ conda create -n test_py35_gdal23x python=3.5 gdal=2.3.1 arcsi
Solving environment: failed
UnsatisfiableError: The following specifications were found to be in conflict:
  - arcsi -> gdal=2.2 -> libgdal[version='>=2.2.2,<2.3.0a0']
  - arcsi -> rsgislib -> boost-cpp==1.65.1
  - gdal=2.3.1
Use "conda info <package>" to see the dependencies for each package.
```

On a different machine, I did manage to get a working environment arcsi environment on linux several weeks ago. Here's `conda info` and `conda list` output to a [textfile](https://www.dropbox.com/s/ove4eu7wnpecojs/env_arcsienv_working.txt?dl=0)

So, based that `conda list` from the working environment the packages and versions that worked were `python=3.5` and `gdal=2.2.4` and `arcsi=3.6.1`  and boost-ccp=1.66.0

So first I tried:

```
$ conda create -n test_py35_gdal224 python=3.5 gdal=2.2.4 arcsi=3.6.1
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - arcsi -> rsgislib -> boost-cpp==1.65.1
  - gdal=2.2.4
Use "conda info <package>" to see the dependencies for each package.
```

Then I tried:

```
$ conda create -n test_py35_gdal224 python=3.5 gdal=2.2.4 boost-ccp=1.66.0 arcsi=3.6.1
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - boost-ccp=1.66.0

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

However, a conda search suggests `boost-ccp=1.66.0` is in conda-forge. So now, I'm a bit lost.

Apologies both, I'm still a newbie! Can you kindly suggest what syntax, if any, I can use to override the global pinning and (hopefully) create a working environment please? Thanks so much!

**Comment by jordanarseno** [comment]
I'm having similar issues as @samfranklin. 

In addition to this, similar reports are being posted in the [rsgislib google groups support channel](https://groups.google.com/forum/#!topic/rsgislib-support/1ixzTz7Ji_w).

My goal is simple. To use `rsgislib` on Ubuntu 16.04, specifically `rsgislib`'s [image registration module](https://www.rsgislib.org/rsgislib_imageregistration.html).

Following the direct `conda` installation instructions from the rsgislib official website:

```sh
root@66e8203f067b:/app# conda install -c conda-forge -c rios rsgislib
Solving environment: done

## Package Plan ##

  environment location: /root/miniconda2

  added / updated specs: 
    - rsgislib


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    gdal-2.2.2                 |   py27hae9aa10_1         778 KB
    freexl-1.0.5               |       hf837533_1          44 KB  conda-forge
    kealib-1.4.8               |       hfc679d8_0         173 KB  conda-forge
    cgal-4.12                  |           py27_0        11.8 MB  conda-forge
    libgdal-2.2.2              |       h804cdde_1        16.1 MB
    libssh2-1.8.0              |       h5b517e9_2         240 KB  conda-forge
    libxml2-2.9.8              |       h422b904_2         1.8 MB  conda-forge
    xerces-c-3.2.0             |                0         3.9 MB  conda-forge
    freetype-2.8.1             |                0         2.9 MB  conda-forge
    intel-openmp-2018.0.3      |                0         705 KB
    numpy-base-1.14.3          |   py27h0ea5e3f_1         4.0 MB
    libiconv-1.15              |       h470a237_1         2.0 MB  conda-forge
    xorg-renderproto-0.11.1    |       h470a237_2           8 KB  conda-forge
    proj4-4.9.3                |                5         4.0 MB  conda-forge
    gsl-2.2.1                  |       h0c605f7_3         2.6 MB
    xorg-libsm-1.2.2           |       h470a237_4          24 KB  conda-forge
    poppler-0.67.0             |       hb55ee21_1         8.5 MB  conda-forge
    fontconfig-2.13.0          |       h074f895_3         281 KB  conda-forge
    xorg-xproto-7.0.31         |       h470a237_7          72 KB  conda-forge
    geos-3.6.2                 |       hfc679d8_2         3.3 MB  conda-forge
    gmp-6.1.2                  |       hfc679d8_0         676 KB  conda-forge
    libxcb-1.13                |       h470a237_2         393 KB  conda-forge
    libspatialite-4.3.0a       |               19         4.6 MB  conda-forge
    poppler-data-0.4.9         |                0         3.5 MB  conda-forge
    pthread-stubs-0.4          |       h470a237_1           5 KB  conda-forge
    libpq-9.6.6                |       h4e02ad2_0         101 KB
    mkl_fft-1.0.4              |           py27_0         497 KB  conda-forge
    libdap4-3.19.1             |                0        15.6 MB  conda-forge
    json-c-0.12.1              |                0          47 KB  conda-forge
    util-linux-2.21            |                0          35 KB
    rsgislib-3.5.7             |           py27_3         4.2 MB  conda-forge
    icu-58.2                   |       hfc679d8_0        22.8 MB  conda-forge
    xorg-libice-1.0.9          |       h470a237_4          55 KB  conda-forge
    libgfortran-ng-7.2.0       |       hdf63c60_3         1.2 MB
    libgfortran-3.0.0          |                1         281 KB
    libboost-1.67.0            |       h46d08c1_4        20.9 MB
    pixman-0.34.0              |                2         1.2 MB  conda-forge
    curl-7.61.0                |       h93b3f91_1         860 KB  conda-forge
    xorg-libxau-1.0.8          |       h470a237_6          12 KB  conda-forge
    pcre-8.41                  |       h470a237_2         244 KB  conda-forge
    cairo-1.14.12              |       he56eebe_3         1.3 MB  conda-forge
    libopenblas-0.2.20         |       h9ac9557_7         8.8 MB
    xorg-libxrender-0.9.10     |       h470a237_2          28 KB  conda-forge
    numpy-1.14.3               |   py27hcd700cb_2          42 KB
    giflib-5.1.4               |       h470a237_0          74 KB  conda-forge
    boost-cpp-1.66.0           |                1        18.8 MB  conda-forge
    bzip2-1.0.6                |       h470a237_2         310 KB  conda-forge
    libnetcdf-4.4.1.1          |               10         2.0 MB  conda-forge
    krb5-1.14.6                |                0         4.0 MB  conda-forge
    xorg-libxext-1.3.3         |       h470a237_4          45 KB  conda-forge
    expat-2.2.5                |       hfc679d8_1         144 KB  conda-forge
    xz-5.2.4                   |       h470a237_0         329 KB  conda-forge
    xorg-libxdmcp-1.1.2        |       h470a237_7          17 KB  conda-forge
    mkl_random-1.0.1           |           py27_0         1.1 MB  conda-forge
    hdf5-1.10.1                |                2         5.0 MB  conda-forge
    mkl-2018.0.3               |                1       198.7 MB
    glib-2.55.0                |                0         8.3 MB  conda-forge
    xorg-xextproto-7.3.0       |       h470a237_2          26 KB  conda-forge
    libtiff-4.0.9              |       he6b73bb_1         521 KB  conda-forge
    libuuid-1.0.3              |                1          34 KB  conda-forge
    hdf4-4.2.13                |                0         969 KB  conda-forge
    muparser-2.2.5             |       hfc679d8_4         162 KB  conda-forge
    openjpeg-2.3.0             |       h0e734dc_3         375 KB  conda-forge
    jpeg-9c                    |       h470a237_0         230 KB  conda-forge
    mpfr-4.0.1                 |       h16a7912_0         602 KB  conda-forge
    libkml-1.3.0               |       h590aaf7_4         633 KB
    libpng-1.6.34              |       ha92aebf_1         304 KB  conda-forge
    xorg-kbproto-1.0.7         |       h470a237_2          25 KB  conda-forge
    xorg-libx11-1.6.5          |       h470a237_2         888 KB  conda-forge
    gettext-0.19.8.1           |                0         6.3 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       400.4 MB

The following NEW packages will be INSTALLED:

    boost-cpp:        1.66.0-1              conda-forge
    bzip2:            1.0.6-h470a237_2      conda-forge
    cairo:            1.14.12-he56eebe_3    conda-forge
    cgal:             4.12-py27_0           conda-forge
    curl:             7.61.0-h93b3f91_1     conda-forge
    expat:            2.2.5-hfc679d8_1      conda-forge
    fontconfig:       2.13.0-h074f895_3     conda-forge
    freetype:         2.8.1-0               conda-forge
    freexl:           1.0.5-hf837533_1      conda-forge
    gdal:             2.2.2-py27hae9aa10_1             
    geos:             3.6.2-hfc679d8_2      conda-forge
    gettext:          0.19.8.1-0            conda-forge
    giflib:           5.1.4-h470a237_0      conda-forge
    glib:             2.55.0-0              conda-forge
    gmp:              6.1.2-hfc679d8_0      conda-forge
    gsl:              2.2.1-h0c605f7_3                 
    hdf4:             4.2.13-0              conda-forge
    hdf5:             1.10.1-2              conda-forge
    icu:              58.2-hfc679d8_0       conda-forge
    intel-openmp:     2018.0.3-0                       
    jpeg:             9c-h470a237_0         conda-forge
    json-c:           0.12.1-0              conda-forge
    kealib:           1.4.8-hfc679d8_0      conda-forge
    krb5:             1.14.6-0              conda-forge
    libboost:         1.67.0-h46d08c1_4                
    libdap4:          3.19.1-0              conda-forge
    libgdal:          2.2.2-h804cdde_1                 
    libgfortran:      3.0.0-1                          
    libgfortran-ng:   7.2.0-hdf63c60_3                 
    libiconv:         1.15-h470a237_1       conda-forge
    libkml:           1.3.0-h590aaf7_4                 
    libnetcdf:        4.4.1.1-10            conda-forge
    libopenblas:      0.2.20-h9ac9557_7                
    libpng:           1.6.34-ha92aebf_1     conda-forge
    libpq:            9.6.6-h4e02ad2_0                 
    libspatialite:    4.3.0a-19             conda-forge
    libssh2:          1.8.0-h5b517e9_2      conda-forge
    libtiff:          4.0.9-he6b73bb_1      conda-forge
    libuuid:          1.0.3-1               conda-forge
    libxcb:           1.13-h470a237_2       conda-forge
    libxml2:          2.9.8-h422b904_2      conda-forge
    mkl:              2018.0.3-1                       
    mkl_fft:          1.0.4-py27_0          conda-forge
    mkl_random:       1.0.1-py27_0          conda-forge
    mpfr:             4.0.1-h16a7912_0      conda-forge
    muparser:         2.2.5-hfc679d8_4      conda-forge
    numpy:            1.14.3-py27hcd700cb_2            
    numpy-base:       1.14.3-py27h0ea5e3f_1            
    openjpeg:         2.3.0-h0e734dc_3      conda-forge
    pcre:             8.41-h470a237_2       conda-forge
    pixman:           0.34.0-2              conda-forge
    poppler:          0.67.0-hb55ee21_1     conda-forge
    poppler-data:     0.4.9-0               conda-forge
    proj4:            4.9.3-5               conda-forge
    pthread-stubs:    0.4-h470a237_1        conda-forge
    rsgislib:         3.5.7-py27_3          conda-forge
    util-linux:       2.21-0                           
    xerces-c:         3.2.0-0               conda-forge
    xorg-kbproto:     1.0.7-h470a237_2      conda-forge
    xorg-libice:      1.0.9-h470a237_4      conda-forge
    xorg-libsm:       1.2.2-h470a237_4      conda-forge
    xorg-libx11:      1.6.5-h470a237_2      conda-forge
    xorg-libxau:      1.0.8-h470a237_6      conda-forge
    xorg-libxdmcp:    1.1.2-h470a237_7      conda-forge
    xorg-libxext:     1.3.3-h470a237_4      conda-forge
    xorg-libxrender:  0.9.10-h470a237_2     conda-forge
    xorg-renderproto: 0.11.1-h470a237_2     conda-forge
    xorg-xextproto:   7.3.0-h470a237_2      conda-forge
    xorg-xproto:      7.0.31-h470a237_7     conda-forge
    xz:               5.2.4-h470a237_0      conda-forge

Proceed ([y]/n)? y

Downloading and Extracting Packages
gdal-2.2.2           |  778 KB | ### | 100% 
freexl-1.0.5         |   44 KB | ### | 100% 
kealib-1.4.8         |  173 KB | ### | 100% 
cgal-4.12            | 11.8 MB | ### | 100% 
libgdal-2.2.2        | 16.1 MB | ### | 100% 
libssh2-1.8.0        |  240 KB | ### | 100% 
libxml2-2.9.8        |  1.8 MB | ### | 100% 
xerces-c-3.2.0       |  3.9 MB | ### | 100% 
freetype-2.8.1       |  2.9 MB | ### | 100% 
intel-openmp-2018.0. |  705 KB | ### | 100% 
numpy-base-1.14.3    |  4.0 MB | ### | 100% 
libiconv-1.15        |  2.0 MB | ### | 100% 
xorg-renderproto-0.1 |    8 KB | ### | 100% 
proj4-4.9.3          |  4.0 MB | ### | 100% 
gsl-2.2.1            |  2.6 MB | ### | 100% 
xorg-libsm-1.2.2     |   24 KB | ### | 100% 
poppler-0.67.0       |  8.5 MB | ### | 100% 
fontconfig-2.13.0    |  281 KB | ### | 100% 
xorg-xproto-7.0.31   |   72 KB | ### | 100% 
geos-3.6.2           |  3.3 MB | ### | 100% 
gmp-6.1.2            |  676 KB | ### | 100% 
libxcb-1.13          |  393 KB | ### | 100% 
libspatialite-4.3.0a |  4.6 MB | ### | 100% 
poppler-data-0.4.9   |  3.5 MB | ### | 100% 
pthread-stubs-0.4    |    5 KB | ### | 100% 
libpq-9.6.6          |  101 KB | ### | 100% 
mkl_fft-1.0.4        |  497 KB | ### | 100% 
libdap4-3.19.1       | 15.6 MB | ### | 100% 
json-c-0.12.1        |   47 KB | ### | 100% 
util-linux-2.21      |   35 KB | ### | 100% 
rsgislib-3.5.7       |  4.2 MB | ### | 100% 
icu-58.2             | 22.8 MB | ### | 100% 
xorg-libice-1.0.9    |   55 KB | ### | 100% 
libgfortran-ng-7.2.0 |  1.2 MB | ### | 100% 
libgfortran-3.0.0    |  281 KB | ### | 100% 
libboost-1.67.0      | 20.9 MB | ### | 100% 
pixman-0.34.0        |  1.2 MB | ### | 100% 
curl-7.61.0          |  860 KB | ### | 100% 
xorg-libxau-1.0.8    |   12 KB | ### | 100% 
pcre-8.41            |  244 KB | ### | 100% 
cairo-1.14.12        |  1.3 MB | ### | 100% 
libopenblas-0.2.20   |  8.8 MB | ### | 100% 
xorg-libxrender-0.9. |   28 KB | ### | 100% 
numpy-1.14.3         |   42 KB | ### | 100% 
giflib-5.1.4         |   74 KB | ### | 100% 
boost-cpp-1.66.0     | 18.8 MB | ### | 100% 
bzip2-1.0.6          |  310 KB | ### | 100% 
libnetcdf-4.4.1.1    |  2.0 MB | ### | 100% 
krb5-1.14.6          |  4.0 MB | ### | 100% 
xorg-libxext-1.3.3   |   45 KB | ### | 100% 
expat-2.2.5          |  144 KB | ### | 100% 
xz-5.2.4             |  329 KB | ### | 100% 
xorg-libxdmcp-1.1.2  |   17 KB | ### | 100% 
mkl_random-1.0.1     |  1.1 MB | ### | 100% 
hdf5-1.10.1          |  5.0 MB | ### | 100% 
mkl-2018.0.3         | 198.7 MB | ### | 100% 
glib-2.55.0          |  8.3 MB | ### | 100% 
xorg-xextproto-7.3.0 |   26 KB | ### | 100% 
libtiff-4.0.9        |  521 KB | ### | 100% 
libuuid-1.0.3        |   34 KB | ### | 100% 
hdf4-4.2.13          |  969 KB | ### | 100% 
muparser-2.2.5       |  162 KB | ### | 100% 
openjpeg-2.3.0       |  375 KB | ### | 100% 
jpeg-9c              |  230 KB | ### | 100% 
mpfr-4.0.1           |  602 KB | ### | 100% 
libkml-1.3.0         |  633 KB | ### | 100% 
libpng-1.6.34        |  304 KB | ### | 100% 
xorg-kbproto-1.0.7   |   25 KB | ### | 100% 
xorg-libx11-1.6.5    |  888 KB | ### | 100% 
gettext-0.19.8.1     |  6.3 MB | ### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

root@66e8203f067b:/app# python -c "from rsgislib import imageregistration"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/miniconda2/lib/python2.7/site-packages/rsgislib/imageregistration/__init__.py", line 28, in <module>
    from ._imageregistration import *
ImportError: libpoppler.so.71: cannot open shared object file: No such file or directory
root@66e8203f067b:/app#

```
I've read on other forums, github & support threads that this is likely due to the mix of channels (default & conda-forge) of the gdal dependencies.

Inspired by @samfranklin I also attempted to install fixed versions of conda packages in order to get at least something working, but could not get it to work.

I'm not in need of bleeding edge `rsgislib`. I just need it to work, even if that's several versions back. As you can probably tell, I am too a newbie at this. Could someone demonstrate some `conda` installation commands to get this going?

**Comment by danclewley** [comment]
As one of the `rsgislib` maintainers I have seen that there are problems with `rsgislib` and that it needs to be rebuilt, I just haven't got round to resolving them yet. If someone else wants to look at that would be great.

@ocefpaf do you want to close this as it isn't a problem with`gdal`.

**Comment by samfranklin** [comment]
@danclewley Hey Dan. Absolutely no issue with your timescales. I fully appreciate that you're likely maintaining rsgislib in your own time around other work, so thank you for doing that for the benefit of users. Sadly, I don't think I have the technical skill to help resolve this, sorry about that !

I'm new to using arcsi/rsgislib, so I wasn't sure of the best way to report the issue. I thought it was a gdal conda-forge problem, hence why I arrived here.

Taking this particular issue as an example. Is your preference for arcsi/rsgislib users to report issues _**only**_ to the rsgislib mailing list? Or should users raise issues over on [rsgislib-feedstock](https://github.com/conda-forge/rsgislib-feedstock) in addition to posting to the mailing list? Just wanted like to get your take on how best to any report issues that crop up.

Thanks again for your help :)
