### ISSUE TITLE
Import error when shapely specified in dependencies

### ISSUE THREAD

**Issue by leroygr** [conda-forge/gdal-feedstock#257]
Issue:

I have import errors related with gdal, apparently only when shapely is included in the deps:

```
$ conda create -n test -c conda-forge python=3.6 Basemap fiona rasterio pyproj pyshp shapely
$ conda activate test; python -c "import gdal"
ImportError: /home/gle/anaconda3/envs/test/lib/python3.6/site-packages/osgeo/../../../libgdal.so.20: undefined symbol: _ZN6libdap3DDSC1EPNS_15BaseTypeFactoryERKSs
```

However, it works if I don't specify shapely in dependencies:
```
$ conda create -n test -c conda-forge python=3.6 Basemap fiona rasterio pyproj pyshp
$ conda activate test; python -c "import gdal"
```

As you can see in the `conda list` outputs in the two situations, the difference is that shapely is installed through conda-forge channel when specified in the list of dependencies. When it is not specified in the dependencies, it is installed from the default channel.

I would of course prefer to specify shapely in my dependencies but it doesn't work so far... 

Any idea?

Thanks!
Greg

ps: it is the same situation with Python 3.7

<br/>
Environment with shapely explicitly in dependencies
<details>

```
$ conda list
# packages in environment at /home/gle/anaconda3/envs/test:
#
# Name                    Version                   Build  Channel
affine                    2.2.2                      py_0    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
attrs                     18.2.0                     py_0    conda-forge
basemap                   1.2.0           py36hb9db7be_1000    conda-forge
blas                      1.0                         mkl  
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
boto3                     1.9.82                     py_0    conda-forge
botocore                  1.12.82                    py_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.14.12           h80bd089_1005    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cffi                      1.11.5          py36h9745a5d_1001    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cryptography              2.3.1           py36hb7f436b_1000    conda-forge
curl                      7.63.0            h646f8bb_1000    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
docutils                  0.14                  py36_1001    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fiona                     1.8.4           py36heb36068_1001    conda-forge
fontconfig                2.13.1            h2176d3f_1000    conda-forge
freetype                  2.9.1             h94bbf69_1005    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
gdal                      2.3.2            py36hb00a9d7_0    conda-forge
geos                      3.6.2                hfc679d8_4    conda-forge
geotiff                   1.4.2             hfe6da40_1005    conda-forge
gettext                   0.19.8.1          h9745a5d_1001    conda-forge
giflib                    5.1.4             h14c3975_1001    conda-forge
glib                      2.56.2            had28632_1001    conda-forge
gst-plugins-base          1.12.5            h3865690_1000    conda-forge
gstreamer                 1.12.5            h0cc0488_1000    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.3            hba1933b_1001    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py36_1000    conda-forge
intel-openmp              2019.1                      144  
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.12.1               h470a237_1    conda-forge
kealib                    1.4.10            hc069b17_1000    conda-forge
kiwisolver                1.0.1           py36h6bb024c_1002    conda-forge
krb5                      1.16.3            hc83ff2d_1000    conda-forge
libcurl                   7.63.0            h01ee5af_1000    conda-forge
libdap4                   3.19.1            hd48c02d_1000    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgdal                   2.3.2                hc73897a_0    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15              h14c3975_1004    conda-forge
libkml                    1.3.0             h328b03d_1009    conda-forge
libnetcdf                 4.6.1             hc6a9f4b_1010    conda-forge
libpng                    1.6.36            h84994c4_1000    conda-forge
libpq                     10.6              h13b8bad_1000    conda-forge
libspatialite             4.3.0a            h9968ff2_1023    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.10            h648cc4a_1001    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
matplotlib                3.0.2           py36h8a2030e_1001    conda-forge
matplotlib-base           3.0.2           py36h167e16e_1001    conda-forge
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py36h470a237_1    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.15.4           py36h7e9f1db_0  
numpy-base                1.15.4           py36hde5b4d6_0  
openjpeg                  2.3.0             hf38bd82_1003    conda-forge
openssl                   1.0.2p            h14c3975_1002    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pip                       18.1                  py36_1000    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
poppler                   0.67.0            h2fc8fa2_1002    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                10.6              h66cca7a_1000    conda-forge
proj4                     4.9.3                h470a237_8    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyproj                    1.9.5.1         py36h2944ce7_1006    conda-forge
pyqt                      5.6.0           py36h13b7fb3_1008    conda-forge
pyshp                     2.0.1                      py_0    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
python                    3.6.7             hd21baee_1001    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
qt                        5.6.2                hf70d934_9    conda-forge
rasterio                  1.0.13           py36h54a03ab_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
s3transfer                0.1.13                py36_1001    conda-forge
setuptools                40.6.3                   py36_0    conda-forge
shapely                   1.6.4           py36h0c48222_1000    conda-forge
sip                       4.18.1          py36hf484d3e_1000    conda-forge
six                       1.12.0                py36_1000    conda-forge
snuggs                    1.4.1                      py_1    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
tornado                   5.1.1           py36h14c3975_1000    conda-forge
tzcode                    2018g             h14c3975_1001    conda-forge
urllib3                   1.24.1                py36_1000    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
xerces-c                  3.2.0                h5d6a6da_2    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h14c3975_1004    conda-forge
xorg-libsm                1.2.3             h4937e3b_1000    conda-forge
xorg-libx11               1.6.6             h14c3975_1000    conda-forge
xorg-libxau               1.0.8             h14c3975_1006    conda-forge
xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
xorg-libxext              1.3.3             h14c3975_1004    conda-forge
xorg-libxrender           0.9.10            h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge

```
</details>

<br/>
Environment without shapely in dependencies
<details>

```
$ conda list
# packages in environment at /home/gle/anaconda3/envs/test:
#
# Name                    Version                   Build  Channel
affine                    2.2.2                      py_0    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
attrs                     18.2.0                     py_0    conda-forge
basemap                   1.2.0           py36h673bf1a_1001    conda-forge
blas                      1.0                         mkl  
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
boto3                     1.9.82                     py_0    conda-forge
botocore                  1.12.82                    py_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.14.12           h80bd089_1005    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cffi                      1.11.5          py36h9745a5d_1001    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cryptography              2.3.1           py36hb7f436b_1000    conda-forge
curl                      7.63.0            h646f8bb_1000    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
docutils                  0.14                  py36_1001    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fiona                     1.8.4           py36h1c6dbfb_1002    conda-forge
fontconfig                2.13.1            h2176d3f_1000    conda-forge
freetype                  2.9.1             h94bbf69_1005    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
gdal                      2.4.0           py36heb36068_1001    conda-forge
geos                      3.7.1             hf484d3e_1000    conda-forge
geotiff                   1.4.3             h1105359_1000    conda-forge
gettext                   0.19.8.1          h9745a5d_1001    conda-forge
giflib                    5.1.4             h14c3975_1001    conda-forge
glib                      2.56.2            had28632_1001    conda-forge
gst-plugins-base          1.12.5            h3865690_1000    conda-forge
gstreamer                 1.12.5            h0cc0488_1000    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.4          nompi_h11e915b_1105    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py36_1000    conda-forge
intel-openmp              2019.1                      144  
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
kealib                    1.4.10            he7154bc_1002    conda-forge
kiwisolver                1.0.1           py36h6bb024c_1002    conda-forge
krb5                      1.16.3            hc83ff2d_1000    conda-forge
libcurl                   7.63.0            h01ee5af_1000    conda-forge
libdap4                   3.19.1            hd48c02d_1000    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgdal                   2.4.0             h982c1cc_1001    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15              h14c3975_1004    conda-forge
libkml                    1.3.0             h328b03d_1009    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libpng                    1.6.36            h84994c4_1000    conda-forge
libpq                     10.6              h13b8bad_1000    conda-forge
libspatialite             4.3.0a              hb08deb6_19  
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.10            h648cc4a_1001    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
matplotlib                3.0.2           py36h8a2030e_1001    conda-forge
matplotlib-base           3.0.2           py36h167e16e_1001    conda-forge
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py36h470a237_1    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.15.4           py36h7e9f1db_0  
numpy-base                1.15.4           py36hde5b4d6_0  
openjpeg                  2.3.0             hf38bd82_1003    conda-forge
openssl                   1.0.2p            h14c3975_1002    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pip                       18.1                  py36_1000    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
poppler                   0.67.0            h2fc8fa2_1002    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                10.6              h66cca7a_1000    conda-forge
proj4                     5.2.0             h14c3975_1001    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyproj                    1.9.6           py36hc0953d3_1000    conda-forge
pyqt                      5.6.0           py36h13b7fb3_1008    conda-forge
pyshp                     2.0.1                      py_0    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
python                    3.6.7             hd21baee_1001    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
qt                        5.6.2                hf70d934_9    conda-forge
rasterio                  1.0.13           py36h286bbcc_1    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
s3transfer                0.1.13                py36_1001    conda-forge
setuptools                40.6.3                   py36_0    conda-forge
shapely                   1.6.4            py36h86c5351_0  
sip                       4.18.1          py36hf484d3e_1000    conda-forge
six                       1.12.0                py36_1000    conda-forge
snuggs                    1.4.1                      py_1    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
tornado                   5.1.1           py36h14c3975_1000    conda-forge
tzcode                    2018g             h14c3975_1001    conda-forge
urllib3                   1.24.1                py36_1000    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
xerces-c                  3.2.2             hac72e42_1001    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h14c3975_1004    conda-forge
xorg-libsm                1.2.3             h4937e3b_1000    conda-forge
xorg-libx11               1.6.6             h14c3975_1000    conda-forge
xorg-libxau               1.0.8             h14c3975_1006    conda-forge
xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
xorg-libxext              1.3.3             h14c3975_1004    conda-forge
xorg-libxrender           0.9.10            h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : test
    active env location : /home/gle/anaconda3/envs/test
            shell level : 1
       user config file : /home/gle/.condarc
 populated config files : /home/gle/.condarc
          conda version : 4.5.12
    conda-build version : 3.12.1
         python version : 3.6.4.final.0
       base environment : /home/gle/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/gle/anaconda3/pkgs
                          /home/gle/.conda/pkgs
       envs directories : /home/gle/anaconda3/envs
                          /home/gle/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.18.4 CPython/3.6.4 Linux/4.19.13-1-MANJARO manjaro/18.0.2 glibc/2.28
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by ocefpaf** [comment]
https://github.com/conda-forge/shapely-feedstock/pull/46 should fix this.

**Comment by trey-stafford** [comment]
This is also an issue for gdal=2.2.4:
```
$ conda create -n gdal_test
$ source activate gdal_test
$ conda install python=3.5 gdal=2.2.4

$ python -c "import gdal"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/trst2284/miniconda3/envs/gdal_test/lib/python3.5/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/trst2284/miniconda3/envs/gdal_test/lib/python3.5/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/trst2284/miniconda3/envs/gdal_test/lib/python3.5/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/trst2284/miniconda3/envs/gdal_test/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/trst2284/miniconda3/envs/gdal_test/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/trst2284/miniconda3/envs/gdal_test/lib/python3.5/site-packages/osgeo/../../../libgdal.so.20: undefined symbol: _ZN6libdap3DDSC1EPNS_15BaseTypeFactoryERKSs
```

**Comment by trey-stafford** [comment]
I have been able to resolve this issue by specifying the version of `libgcc-ng`: 
```
$ conda install python=3.5 gdal=2.2.4 libgcc-ng=7.2.0
$ python -c "import gdal"
$ echo $?
0
$ conda list libgcc-ng
# Name                    Version                   Build  Channel
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge/label/main
```
