### ISSUE TITLE
Newest 2.4.0 build causes pyproj RuntimeError projection not named

### ISSUE THREAD

**Issue by djhoese** [conda-forge/gdal-feedstock#262]
Tests for my package are suddenly failing with new gdal (possibly rasterio), but the error is showing up with a pyproj error. You can see it in one of our travis jobs:

https://travis-ci.org/pytroll/satpy/jobs/484681655#L6502-L6521

The tests that are failing are not part of the things that were changed in the commit being tested. From what I can tell (as someone familiar with the code) is that we are loading a geotiff from disk using `xarray.open_rasterio`, accessing the `data_arr.attrs['crs']`, and parsing that PROJ.4 string later on and passing it to `pyproj.Proj`. I'm wondering if xarray/rasterio/gdal is returning an empty CRS string.

Something that is curious is that it doesn't seem to fail on OSX Python 3.6, but does fail on Linux py36 and OSX/Linux py27.

**Comment by djhoese** [comment]
Trying to reproduce the failing linux python 3.6 job and I get a segmentation fault with rasterio/libgdal:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/davidh/.conda/envs/satpy_test_36/lib/python3.6/site-packages/xarray/backends/rasterio_.py", line 213, in open_rasterio
    import rasterio
  File "/home/davidh/.conda/envs/satpy_test_36/lib/python3.6/site-packages/rasterio/__init__.py", line 22, in <module>
    from rasterio._base import gdal_version
ImportError: /home/davidh/.conda/envs/satpy_test_36/lib/python3.6/site-packages/rasterio/../../../libgdal.so.20: undefined symbol: _ZNK6libdap5Error17get_error_messageB5cxx11Ev
```

**Comment by djhoese** [comment]
Ah this is the same segmentation fault as #261.

**Comment by djhoese** [comment]
I figured out the segfault issue. It seems that `libkml` needs to be a specific (newest) build:

```
$ conda update libkml
Solving environment: done

## Package Plan ##

  environment location: /home/davidh/.conda/envs/satpy_test_36

  added / updated specs: 
    - libkml


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    boost-1.68.0               |py36h8619c78_1001         325 KB  conda-forge

The following packages will be UPDATED:

    boost:     1.67.0-py36h3e44d54_0 conda-forge --> 1.68.0-py36h8619c78_1001 conda-forge
    boost-cpp: 1.67.0-h3a22d5f_0     conda-forge --> 1.68.0-h11c811c_1000     conda-forge
    libkml:    1.3.0-hccc92b1_8      conda-forge --> 1.3.0-h328b03d_1009      conda-forge
```

@ocefpaf Is it possible to pin this in some way? Any ideas?

Additionally, it looks like some library has started returning the WKT instead of the PROJ.4 string to xarray. I'll have to search some release notes.

**Comment by ocefpaf** [comment]
Latest `libkml` should be picked up, maybe another dependency is making `conda` "wiggle" its way out of a complex solution and preferring the old boost.

Here is the solution for my env with

`conda create --name TEST python=3.6 gdal`


```
  atk                conda-forge/linux-64::atk-2.25.90-hf2eb9ee_1001
  attrs              conda-forge/noarch::attrs-18.2.0-py_0
  backcall           conda-forge/noarch::backcall-0.1.0-py_0
  blas               conda-forge/linux-64::blas-1.1-openblas
  bleach             conda-forge/noarch::bleach-3.1.0-py_0
  boost-cpp          conda-forge/linux-64::boost-cpp-1.68.0-h11c811c_1000
  bzip2              conda-forge/linux-64::bzip2-1.0.6-h14c3975_1002
  ca-certificates    conda-forge/linux-64::ca-certificates-2018.11.29-ha4d7672_0
  cairo              conda-forge/linux-64::cairo-1.14.12-h80bd089_1005
  certifi            conda-forge/linux-64::certifi-2018.11.29-py36_1000
  curl               conda-forge/linux-64::curl-7.63.0-h646f8bb_1000
  dbus               conda-forge/linux-64::dbus-1.13.0-h4e0c4b3_1000
  decorator          conda-forge/noarch::decorator-4.3.2-py_0
  entrypoints        conda-forge/linux-64::entrypoints-0.3-py36_1000
  expat              conda-forge/linux-64::expat-2.2.5-hf484d3e_1002
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-h2176d3f_1000
  freetype           conda-forge/linux-64::freetype-2.9.1-h94bbf69_1005
  freexl             conda-forge/linux-64::freexl-1.0.5-h14c3975_1002
  gdal               conda-forge/linux-64::gdal-2.4.0-py36h1c6dbfb_1002
  gdk-pixbuf         conda-forge/linux-64::gdk-pixbuf-2.36.12-h4f1c04b_1001
  geos               conda-forge/linux-64::geos-3.7.1-hf484d3e_1000
  geotiff            conda-forge/linux-64::geotiff-1.4.3-h1105359_1000
  gettext            conda-forge/linux-64::gettext-0.19.8.1-h9745a5d_1001
  giflib             conda-forge/linux-64::giflib-5.1.4-h14c3975_1001
  glib               conda-forge/linux-64::glib-2.56.2-had28632_1001
  gmp                conda-forge/linux-64::gmp-6.1.2-hf484d3e_1000
  gobject-introspec~ conda-forge/linux-64::gobject-introspection-1.56.1-py36h9e29830_1001
  graphite2          conda-forge/linux-64::graphite2-1.3.13-hf484d3e_1000
  gstreamer          conda-forge/linux-64::gstreamer-1.12.5-h0cc0488_1000
  gtk2               conda-forge/linux-64::gtk2-2.24.31-h5baeb44_1000
  harfbuzz           conda-forge/linux-64::harfbuzz-1.9.0-he243708_1001
  hdf4               conda-forge/linux-64::hdf4-4.2.13-h9a582f1_1002
  hdf5               conda-forge/linux-64::hdf5-1.10.4-nompi_h11e915b_1105
  icu                conda-forge/linux-64::icu-58.2-hf484d3e_1000
  ipykernel          conda-forge/linux-64::ipykernel-5.1.0-py36h24bf2e0_1001
  ipython            conda-forge/linux-64::ipython-7.2.0-py36h24bf2e0_1000
  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1
  ipywidgets         conda-forge/noarch::ipywidgets-7.4.2-py_0
  jedi               conda-forge/linux-64::jedi-0.13.2-py36_1000
  jinja2             conda-forge/noarch::jinja2-2.10-py_1
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  json-c             conda-forge/linux-64::json-c-0.13.1-h14c3975_1001
  jsonschema         conda-forge/linux-64::jsonschema-3.0.0a3-py36_1000
  jupyter            conda-forge/noarch::jupyter-1.0.0-py_1
  jupyter_client     conda-forge/noarch::jupyter_client-5.2.4-py_1
  jupyter_console    conda-forge/noarch::jupyter_console-6.0.0-py_0
  jupyter_contrib_c~ conda-forge/noarch::jupyter_contrib_core-0.3.3-py_2
  jupyter_contrib_n~ conda-forge/linux-64::jupyter_contrib_nbextensions-0.5.1-py36_0
  jupyter_core       conda-forge/noarch::jupyter_core-4.4.0-py_0
  jupyter_highlight~ conda-forge/linux-64::jupyter_highlight_selected_word-0.2.0-py36_1000
  jupyter_latex_envs conda-forge/linux-64::jupyter_latex_envs-1.4.4-py36_1000
  jupyter_nbextensi~ conda-forge/linux-64::jupyter_nbextensions_configurator-0.4.1-py36_0
  kealib             conda-forge/linux-64::kealib-1.4.10-he7154bc_1002
  krb5               conda-forge/linux-64::krb5-1.16.3-hc83ff2d_1000
  libcurl            conda-forge/linux-64::libcurl-7.63.0-h01ee5af_1000
  libdap4            conda-forge/linux-64::libdap4-3.19.1-hd48c02d_1000
  libedit            conda-forge/linux-64::libedit-3.1.20170329-hf8c457e_1001
  libffi             conda-forge/linux-64::libffi-3.2.1-hf484d3e_1005
  libgcc-ng          conda-forge/linux-64::libgcc-ng-7.3.0-hdf63c60_0
  libgdal            conda-forge/linux-64::libgdal-2.4.0-h982c1cc_1002
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.2.0-hdf63c60_3
  libiconv           conda-forge/linux-64::libiconv-1.15-h14c3975_1004
  libkml             conda-forge/linux-64::libkml-1.3.0-h328b03d_1009
  libnetcdf          conda-forge/linux-64::libnetcdf-4.6.2-hbdf4f91_1001
  libpng             conda-forge/linux-64::libpng-1.6.36-h84994c4_1000
  libpq              conda-forge/linux-64::libpq-10.6-h13b8bad_1000
  libsodium          conda-forge/linux-64::libsodium-1.0.16-h14c3975_1001
  libspatialite      conda-forge/linux-64::libspatialite-4.3.0a-hb5ec416_1026
  libssh2            conda-forge/linux-64::libssh2-1.8.0-h1ad7b7a_1003
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-7.3.0-hdf63c60_0
  libtiff            conda-forge/linux-64::libtiff-4.0.10-h9022e91_1002
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxml2            conda-forge/linux-64::libxml2-2.9.8-h143f9aa_1005
  libxslt            conda-forge/linux-64::libxslt-1.1.32-h4785a14_1002
  lxml               conda-forge/linux-64::lxml-4.3.0-py36h23eabaa_1000
  markupsafe         conda-forge/linux-64::markupsafe-1.1.0-py36h14c3975_1000
  mistune            conda-forge/linux-64::mistune-0.8.4-py36h14c3975_1000
  nbconvert          conda-forge/noarch::nbconvert-5.3.1-py_1
  nbformat           conda-forge/noarch::nbformat-4.4.0-py_1
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  notebook           conda-forge/linux-64::notebook-5.7.4-py36_1000
  numpy              conda-forge/linux-64::numpy-1.16.0-py36_blas_openblash1522bff_1000
  openblas           conda-forge/linux-64::openblas-0.3.3-h9ac9557_1001
  openjpeg           conda-forge/linux-64::openjpeg-2.3.0-hf38bd82_1003
  openssl            conda-forge/linux-64::openssl-1.0.2p-h14c3975_1002
  pandoc             conda-forge/linux-64::pandoc-2.5-1
  pandocfilters      conda-forge/noarch::pandocfilters-1.4.2-py_1
  pango              conda-forge/linux-64::pango-1.40.14-hf0c64fd_1003
  parso              conda-forge/noarch::parso-0.3.2-py_0
  pcre               conda-forge/linux-64::pcre-8.41-hf484d3e_1003
  pexpect            conda-forge/linux-64::pexpect-4.6.0-py36_1000
  pickleshare        conda-forge/linux-64::pickleshare-0.7.5-py36_1000
  pip                conda-forge/linux-64::pip-19.0.1-py36_0
  pixman             conda-forge/linux-64::pixman-0.34.0-h14c3975_1003
  poppler            conda-forge/linux-64::poppler-0.67.0-h2fc8fa2_1002
  poppler-data       conda-forge/noarch::poppler-data-0.4.9-1
  postgresql         conda-forge/linux-64::postgresql-10.6-h66cca7a_1000
  proj4              conda-forge/linux-64::proj4-5.2.0-h14c3975_1001
  prometheus_client  conda-forge/noarch::prometheus_client-0.5.0-py_0
  prompt_toolkit     conda-forge/noarch::prompt_toolkit-2.0.7-py_0
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  ptyprocess         conda-forge/linux-64::ptyprocess-0.6.0-py36_1000
  pygments           conda-forge/noarch::pygments-2.3.1-py_0
  pyqt               conda-forge/linux-64::pyqt-5.6.0-py36h13b7fb3_1008
  pyrsistent         conda-forge/linux-64::pyrsistent-0.14.9-py36h14c3975_1000
  python             conda-forge/linux-64::python-3.6.7-hd21baee_1001
  python-dateutil    conda-forge/noarch::python-dateutil-2.7.5-py_0
  pyyaml             conda-forge/linux-64::pyyaml-3.13-py36h14c3975_1001
  pyzmq              conda-forge/linux-64::pyzmq-17.1.2-py36h6afc9c9_1001
  qt                 conda-forge/linux-64::qt-5.6.2-hbe13537_1012
  qtconsole          conda-forge/noarch::qtconsole-4.4.3-py_0
  readline           conda-forge/linux-64::readline-7.0-hf8c457e_1001
  send2trash         conda-forge/noarch::send2trash-1.5.0-py_0
  setuptools         conda-forge/linux-64::setuptools-40.6.3-py36_0
  sip                conda-forge/linux-64::sip-4.18.1-py36hf484d3e_1000
  six                conda-forge/linux-64::six-1.12.0-py36_1000
  sqlite             conda-forge/linux-64::sqlite-3.26.0-h67949de_1000
  terminado          conda-forge/linux-64::terminado-0.8.1-py36_1001
  testpath           conda-forge/linux-64::testpath-0.4.2-py36_1000
  tk                 conda-forge/linux-64::tk-8.6.9-h84994c4_1000
  tornado            conda-forge/linux-64::tornado-5.1.1-py36h14c3975_1000
  traitlets          conda-forge/linux-64::traitlets-4.3.2-py36_1000
  tzcode             conda-forge/linux-64::tzcode-2018g-h14c3975_1001
  wcwidth            conda-forge/noarch::wcwidth-0.1.7-py_1
  webencodings       conda-forge/noarch::webencodings-0.5.1-py_1
  wheel              conda-forge/linux-64::wheel-0.32.3-py36_0
  widgetsnbextension conda-forge/linux-64::widgetsnbextension-3.4.2-py36_1000
  xerces-c           conda-forge/linux-64::xerces-c-3.2.2-hac72e42_1001
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h14c3975_1002
  xorg-libice        conda-forge/linux-64::xorg-libice-1.0.9-h14c3975_1004
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.3-h4937e3b_1000
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.6.6-h14c3975_1000
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.8-h14c3975_1006
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.2-h14c3975_1007
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.3-h14c3975_1004
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.10-h14c3975_1002
  xorg-libxt         conda-forge/linux-64::xorg-libxt-1.1.5-h14c3975_1002
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h14c3975_1002
  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h14c3975_1002
  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h14c3975_1007
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  yaml               conda-forge/linux-64::yaml-0.1.7-h14c3975_1001
  zeromq             conda-forge/linux-64::zeromq-4.2.5-hf484d3e_1006
  zlib               conda-forge/linux-64::zlib-1.2.11-h14c3975_1004
  zstd               conda-forge/linux-64::zstd-1.3.3-1
```

**Comment by djhoese** [comment]
Yeah new environments seem to be fine. Old environments just didn't seem to be *required* to update libkml even though it apparently made a big difference (seg fault). As for the original problem that this issue was made it is being addressed here: https://github.com/pydata/xarray/pull/2715

So I'll close this as a non-issue unless you want to find a way to be more restrictive about `libkml`.

**Comment by ocefpaf** [comment]
> So I'll close this as a non-issue unless you want to find a way to be more restrictive about libkml.

We cannot be more restrictive but I can try to find the reason for the downgrade and either remove the offending packages or fix them. I'll look into your CIs logs later today.
