### ISSUE TITLE
libgdal error on import

### ISSUE THREAD

**Issue by mhearne-usgs** [conda-forge/gdal-feedstock#263]
Issue:
With simple installation (see below), importing fiona causes the following error:

>>> from fiona import collection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mhearne/miniconda/envs/myenv/lib/python3.5/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/home/mhearne/miniconda/envs/myenv/lib/python3.5/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: /home/mhearne/miniconda/envs/myenv/lib/python3.5/site-packages/fiona/../../../libgdal.so.20: undefined symbol: _ZN6libdap3DDSC1EPNS_15BaseTypeFactoryERKSs

<br/>
Environment (<code>conda list</code>):
<details>

```
# packages in environment at /home/mhearne/miniconda/envs/myenv:
#
# Name                    Version                   Build  Channel
blas                      1.1                    openblas    conda-forge
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.16.0            ha4e643d_1000    conda-forge
certifi                   2018.8.24             py35_1001    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
curl                      7.63.0            h646f8bb_1000    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fiona                     1.7.13           py35hb00a9d7_3    conda-forge
fontconfig                2.13.1            h2176d3f_1000    conda-forge
freetype                  2.9.1             h94bbf69_1005    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
gdal                      2.2.4            py35hb00a9d7_1    conda-forge
geos                      3.6.2                hfc679d8_4    conda-forge
geotiff                   1.4.2             hfe6da40_1005    conda-forge
gettext                   0.19.8.1          h9745a5d_1001    conda-forge
giflib                    5.1.4             h14c3975_1001    conda-forge
glib                      2.58.2            hf63aee3_1001    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.3            hba1933b_1001    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.12.1               h470a237_1    conda-forge
kealib                    1.4.10            hc069b17_1000    conda-forge
krb5                      1.16.3            hc83ff2d_1000    conda-forge
libcurl                   7.63.0            h01ee5af_1000    conda-forge
libdap4                   3.19.1            hd48c02d_1000    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgdal                   2.2.4               h744ea89_10    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15              h14c3975_1004    conda-forge
libkml                    1.3.0             h328b03d_1009    conda-forge
libnetcdf                 4.6.1             hc6a9f4b_1010    conda-forge
libpng                    1.6.36            h84994c4_1000    conda-forge
libpq                     10.6              h13b8bad_1000    conda-forge
libspatialite             4.3.0a            h9968ff2_1023    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.10            h9022e91_1002    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
munch                     2.3.2                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.15.2          py35_blas_openblashd3ea46f_0  [blas_openblas]  conda-forge
openblas                  0.2.20                        8    conda-forge
openjpeg                  2.3.0             hf38bd82_1003    conda-forge
openssl                   1.0.2p            h14c3975_1002    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pip                       18.0                  py35_1001    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
poppler                   0.67.0               h2ad7f00_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                10.6              h66cca7a_1000    conda-forge
proj4                     4.9.3                h470a237_8    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
python                    3.5.5                h5001a0f_2    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
setuptools                40.4.3                   py35_0    conda-forge
shapely                   1.6.4            py35h164cb2d_1    conda-forge
six                       1.11.0                   py35_1    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
tzcode                    2018g             h14c3975_1001    conda-forge
wheel                     0.32.0                py35_1000    conda-forge
xerces-c                  3.2.0                h5d6a6da_2    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h14c3975_1004    conda-forge
xorg-libsm                1.2.3             h4937e3b_1000    conda-forge
xorg-libx11               1.6.6             h14c3975_1000    conda-forge
xorg-libxau               1.0.8             h14c3975_1006    conda-forge
xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
xorg-libxext              1.3.3             h14c3975_1004    conda-forge
xorg-libxrender           0.9.10            h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
zstd                      1.3.3                         1    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```

     active environment : myenv
    active env location : /home/mhearne/miniconda/envs/myenv
            shell level : 2
       user config file : /home/mhearne/.condarc
 populated config files : /home/mhearne/.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : /home/mhearne/miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/mhearne/miniconda/pkgs
                          /home/mhearne/.conda/pkgs
       envs directories : /home/mhearne/miniconda/envs
                          /home/mhearne/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/3.10.0-957.1.3.el7.x86_64 scientific/7.6 glibc/2.17
                UID:GID : 176300529:176300529
             netrc file : None
           offline mode : False

```
</details>

Steps to re-create:
conda create -n myenv python=3.5 -y
conda install fiona -y
python
>>>from fiona import collection

**Comment by ocefpaf** [comment]
conda-forge stopped building Python 3.5 a while ago and the old binaries are probably no longer OK for the new compilers and conda-build 3 packages that may be picked up.

What do you get for:

```
conda create --name TEST python=3.6 fiona --yes
conda activate TEST
python -c 'import fiona; print(fiona.__version__)'
1.8.4
```
