### ISSUE TITLE
gdal installation in fresh env gives libgdal.so.20: undefined symbol: _ZN6libdap3DDSC1EPNS_15BaseTypeFactoryERKSs

### ISSUE THREAD

**Issue by weatherbell** [conda-forge/gdal-feedstock#266]
```
conda create --name GIS -c conda-forge --override-channels  python=3.6.5 gdal
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/GIS

  added / updated specs:
    - gdal
    - python=3.6.5


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blas-1.1                   |         openblas           1 KB  conda-forge
    bzip2-1.0.6                |    h14c3975_1002         415 KB  conda-forge
    certifi-2018.11.29         |        py36_1000         145 KB  conda-forge
    curl-7.64.0                |       h646f8bb_0         143 KB  conda-forge
    hdf5-1.10.2                |       hc401514_3         4.8 MB  conda-forge
    krb5-1.16.3                |    hc83ff2d_1000         1.4 MB  conda-forge
    libcurl-7.64.0             |       h01ee5af_0         586 KB  conda-forge
    libedit-3.1.20170329       |                0         160 KB  conda-forge
    libffi-3.2.1               |    hf484d3e_1005          46 KB  conda-forge
    libgfortran-ng-7.2.0       |       hdf63c60_3         1.2 MB  conda-forge
    libpng-1.6.36              |    h84994c4_1000         303 KB  conda-forge
    libpq-10.6                 |    h13b8bad_1000         2.5 MB  conda-forge
    libspatialite-4.3.0a       |               19         4.6 MB  conda-forge
    libtiff-4.0.10             |    h9022e91_1002         555 KB  conda-forge
    ncurses-5.9                |               10         1.1 MB  conda-forge
    numpy-1.16.1               |py36_blas_openblash1522bff_0         4.3 MB  conda-forge
    openblas-0.3.3             |    h9ac9557_1001        15.8 MB  conda-forge
    openssl-1.0.2p             |    h14c3975_1002         3.1 MB  conda-forge
    pip-19.0.2                 |           py36_0         1.8 MB  conda-forge
    pthread-stubs-0.4          |    h14c3975_1001           5 KB  conda-forge
    python-3.6.5               |                1        21.0 MB  conda-forge
    readline-7.0               |                0         838 KB  conda-forge
    setuptools-40.8.0          |           py36_0         626 KB  conda-forge
    sqlite-3.20.1              |                2         1.3 MB  conda-forge
    tk-8.6.9                   |    h84994c4_1000         3.1 MB  conda-forge
    wheel-0.33.0               |           py36_0          34 KB  conda-forge
    xz-5.2.4                   |    h14c3975_1001         366 KB  conda-forge
    zlib-1.2.11                |    h14c3975_1004         101 KB  conda-forge
    zstd-1.3.3                 |                1        1023 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        71.3 MB

The following NEW packages will be INSTALLED:

  blas               conda-forge/linux-64::blas-1.1-openblas
  boost-cpp          conda-forge/linux-64::boost-cpp-1.68.0-h11c811c_1000
  bzip2              conda-forge/linux-64::bzip2-1.0.6-h14c3975_1002
  ca-certificates    conda-forge/linux-64::ca-certificates-2018.11.29-ha4d7672_0
  cairo              conda-forge/linux-64::cairo-1.14.12-he6fea26_5
  certifi            conda-forge/linux-64::certifi-2018.11.29-py36_1000
  curl               conda-forge/linux-64::curl-7.64.0-h646f8bb_0
  expat              conda-forge/linux-64::expat-2.2.5-hf484d3e_1002
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-h2176d3f_1000
  freetype           conda-forge/linux-64::freetype-2.9.1-h94bbf69_1005
  freexl             conda-forge/linux-64::freexl-1.0.5-h14c3975_1002
  gdal               conda-forge/linux-64::gdal-2.2.4-py36hb00a9d7_1
  geos               conda-forge/linux-64::geos-3.6.2-hfc679d8_4
  geotiff            conda-forge/linux-64::geotiff-1.4.2-hfe6da40_1005
  gettext            conda-forge/linux-64::gettext-0.19.8.1-h9745a5d_1001
  giflib             conda-forge/linux-64::giflib-5.1.4-h14c3975_1001
  glib               conda-forge/linux-64::glib-2.55.0-h464dc38_2
  hdf4               conda-forge/linux-64::hdf4-4.2.13-h9a582f1_1002
  hdf5               conda-forge/linux-64::hdf5-1.10.2-hc401514_3
  icu                conda-forge/linux-64::icu-58.2-hf484d3e_1000
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  json-c             conda-forge/linux-64::json-c-0.12.1-h470a237_1
  kealib             conda-forge/linux-64::kealib-1.4.9-h0bee7d0_2
  krb5               conda-forge/linux-64::krb5-1.16.3-hc83ff2d_1000
  libcurl            conda-forge/linux-64::libcurl-7.64.0-h01ee5af_0
  libdap4            conda-forge/linux-64::libdap4-3.19.1-hd48c02d_1000
  libedit            conda-forge/linux-64::libedit-3.1.20170329-0
  libffi             conda-forge/linux-64::libffi-3.2.1-hf484d3e_1005
  libgcc-ng          conda-forge/linux-64::libgcc-ng-7.3.0-hdf63c60_0
  libgdal            conda-forge/linux-64::libgdal-2.2.4-ha6e4b24_6
  libgfortran        conda-forge/linux-64::libgfortran-3.0.0-1
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.2.0-hdf63c60_3
  libiconv           conda-forge/linux-64::libiconv-1.15-h14c3975_1004
  libkml             conda-forge/linux-64::libkml-1.3.0-h328b03d_1009
  libnetcdf          conda-forge/linux-64::libnetcdf-4.6.1-h628ed10_200
  libpng             conda-forge/linux-64::libpng-1.6.36-h84994c4_1000
  libpq              conda-forge/linux-64::libpq-10.6-h13b8bad_1000
  libspatialite      conda-forge/linux-64::libspatialite-4.3.0a-19
  libssh2            conda-forge/linux-64::libssh2-1.8.0-h1ad7b7a_1003
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-7.3.0-hdf63c60_0
  libtiff            conda-forge/linux-64::libtiff-4.0.10-h9022e91_1002
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxml2            conda-forge/linux-64::libxml2-2.9.8-h143f9aa_1005
  ncurses            conda-forge/linux-64::ncurses-5.9-10
  numpy              conda-forge/linux-64::numpy-1.16.1-py36_blas_openblash1522bff_0
  openblas           conda-forge/linux-64::openblas-0.3.3-h9ac9557_1001
  openjpeg           conda-forge/linux-64::openjpeg-2.3.0-hf38bd82_1003
  openssl            conda-forge/linux-64::openssl-1.0.2p-h14c3975_1002
  pcre               conda-forge/linux-64::pcre-8.41-hf484d3e_1003
  pip                conda-forge/linux-64::pip-19.0.2-py36_0
  pixman             conda-forge/linux-64::pixman-0.34.0-h14c3975_1003
  poppler            conda-forge/linux-64::poppler-0.61.1-h4d7e492_4
  poppler-data       conda-forge/noarch::poppler-data-0.4.9-1
  proj4              conda-forge/linux-64::proj4-4.9.3-h470a237_8
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  python             conda-forge/linux-64::python-3.6.5-1
  readline           conda-forge/linux-64::readline-7.0-0
  setuptools         conda-forge/linux-64::setuptools-40.8.0-py36_0
  sqlite             conda-forge/linux-64::sqlite-3.20.1-2
  tk                 conda-forge/linux-64::tk-8.6.9-h84994c4_1000
  wheel              conda-forge/linux-64::wheel-0.33.0-py36_0
  xerces-c           conda-forge/linux-64::xerces-c-3.2.0-h5d6a6da_2
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h14c3975_1002
  xorg-libice        conda-forge/linux-64::xorg-libice-1.0.9-h14c3975_1004
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.3-h4937e3b_1000
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.6.7-h14c3975_1000
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.2-h14c3975_1007
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.3-h14c3975_1004
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.10-h14c3975_1002
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h14c3975_1002
  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h14c3975_1002
  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h14c3975_1007
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  zlib               conda-forge/linux-64::zlib-1.2.11-h14c3975_1004
  zstd               conda-forge/linux-64::zstd-1.3.3-1


Proceed ([y]/n)? y


Downloading and Extracting Packages
wheel-0.33.0         | 34 KB     | ##################################################################################################################################################################### | 100%
zstd-1.3.3           | 1023 KB   | ##################################################################################################################################################################### | 100%
bzip2-1.0.6          | 415 KB    | ##################################################################################################################################################################### | 100%
ncurses-5.9          | 1.1 MB    | ##################################################################################################################################################################### | 100%
setuptools-40.8.0    | 626 KB    | ##################################################################################################################################################################### | 100%
certifi-2018.11.29   | 145 KB    | ##################################################################################################################################################################### | 100%
numpy-1.16.1         | 4.3 MB    | ##################################################################################################################################################################### | 100%
krb5-1.16.3          | 1.4 MB    | ##################################################################################################################################################################### | 100%
libtiff-4.0.10       | 555 KB    | ##################################################################################################################################################################### | 100%
readline-7.0         | 838 KB    | ##################################################################################################################################################################### | 100%
pthread-stubs-0.4    | 5 KB      | ##################################################################################################################################################################### | 100%
libgfortran-ng-7.2.0 | 1.2 MB    | ##################################################################################################################################################################### | 100%
python-3.6.5         | 21.0 MB   | ##################################################################################################################################################################### | 100%
libpng-1.6.36        | 303 KB    | ##################################################################################################################################################################### | 100%
libpq-10.6           | 2.5 MB    | ##################################################################################################################################################################### | 100%
zlib-1.2.11          | 101 KB    | ##################################################################################################################################################################### | 100%
libedit-3.1.20170329 | 160 KB    | ##################################################################################################################################################################### | 100%
openblas-0.3.3       | 15.8 MB   | ##################################################################################################################################################################### | 100%
tk-8.6.9             | 3.1 MB    | ##################################################################################################################################################################### | 100%
xz-5.2.4             | 366 KB    | ##################################################################################################################################################################### | 100%
openssl-1.0.2p       | 3.1 MB    | ##################################################################################################################################################################### | 100%
hdf5-1.10.2          | 4.8 MB    | ##################################################################################################################################################################### | 100%
sqlite-3.20.1        | 1.3 MB    | ##################################################################################################################################################################### | 100%
blas-1.1             | 1 KB      | ##################################################################################################################################################################### | 100%
libspatialite-4.3.0a | 4.6 MB    | ##################################################################################################################################################################### | 100%
curl-7.64.0          | 143 KB    | ##################################################################################################################################################################### | 100%
pip-19.0.2           | 1.8 MB    | ##################################################################################################################################################################### | 100%
libffi-3.2.1         | 46 KB     | ##################################################################################################################################################################### | 100%
libcurl-7.64.0       | 586 KB    | ##################################################################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate GIS
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) root@9d3e8867b971:/requirements# conda activate GIS
(GIS) root@9d3e8867b971:/requirements# python3
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/GIS/lib/python3.6/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/opt/conda/envs/GIS/lib/python3.6/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/opt/conda/envs/GIS/lib/python3.6/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/opt/conda/envs/GIS/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/conda/envs/GIS/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /opt/conda/envs/GIS/lib/python3.6/site-packages/osgeo/../../../libgdal.so.20: undefined symbol: _ZN6libdap3DDSC1EPNS_15BaseTypeFactoryERKSs
```

conda info: (but keep in mind I did -c conda forge and --override-channels)
```
     active environment : GIS
    active env location : /opt/conda/envs/GIS
            shell level : 2
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.6.4
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/intel/linux-64
                          https://conda.anaconda.org/intel/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.4 requests/2.20.1 CPython/3.6.5 Linux/4.9.125-linuxkit debian/9 glibc/2.24
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

**Comment by kmuehlbauer** [comment]
@weatherbell Python 3.6.5 is rather old, means it was build almost a year ago. Current is 3.6.7. Can you try this?

**Comment by ocefpaf** [comment]
> @weatherbell Python 3.6.5 is rather old, means it was build almost a year ago. Current is 3.6.7. Can you try this?

Unless you really need `python 3.6.5` I recommend you pinning to the major version and not the micro. Try:

`conda create --name GIS -c conda-forge --override-channels  python=3.6 gdal`

**Comment by weatherbell** [comment]
It is actually very important for us to use the intel channel's python because we need the speed boost. Intel has 3.6.2, 3.6.5 and 3.6.8 python versions. @kmuehlbauer you were right that pinning python to 3.6.7 worked, but when I added -c intel (before -c conda-forge) it did not work. I tried pinning to 3.6.8, but that did not work for a different reason:
```

UnsatisfiableError: The following specifications were found to be in conflict:
  - gdal -> libgdal==2.4.0=h982c1cc_1002 -> libspatialite[version='>=4.3.0a,<4.4.0a0'] -> sqlite[version='>=3.26.0,<4.0a0']
  - python=3.6.8
```
I guess you guys don't have a recipe for 3.6.8 yet? 

@ocefpaf your solution is what ended up working for my situation (having to use the intel python), but the version that conda chose was 3.6.2.

I am curious why 3.6.5 stopped working - it worked as of a few weeks ago.

Thanks for your help guys!

**Comment by ocefpaf** [comment]
> It is actually very important for us to use the intel channel's python because we need the speed boost. Intel has 3.6.2, 3.6.5 and 3.6.8 python versions. @kmuehlbauer you were right that pinning python to 3.6.7 worked, but when I added -c intel (before -c conda-forge) it did not work. I tried pinning to 3.6.8, but that did not work for a different reason:

Mixing channels is always a bad idea. See https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels

> I am curious why 3.6.5 stopped working - it worked as of a few weeks ago.

As we update the packages some old versions are not rebuilt to accommodate the new changes/pins due to CI and human resources.

> @ocefpaf your solution is what ended up working for my situation (having to use the intel python), but the version that conda chose was 3.6.2.

Conda's solver does that sometimes. At least it chose a version that works :-)

BTW, [here is an example of `.condarc`](https://gist.github.com/ocefpaf/863fc5df6ed8444378fbb1211ad8feb1) file that may help you with the problem of using multiple channels, but note that if you pin python you are forcing conda to solve for something that may be incompatible.

PS: python and its pinning are quite complex and, unless intel provides their own version for all of conda-forge's packages, I don't expect for anything that is compiled to work out of the box with their package. Only pure python packages and some very simple c extensions.
