### ISSUE TITLE
ImportError: libkea.so.1.4.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by baloe** [conda-forge/gdal-feedstock#286]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
# packages in environment at /home/s4080143/.conda/envs/pers:
#
_license                  1.1                      py36_1  
alabaster                 0.7.10           py36h306e16b_0  
anaconda                  custom           py36hbbc8b67_0  
anaconda-client           1.6.6            py36h59e3ba0_0  
anaconda-navigator        1.6.11                   py36_0  
anaconda-project          0.8.2            py36h44fb852_0  
asn1crypto                0.24.0                   py36_0  
astroid                   1.6.0                    py36_0  
astropy                   2.0.3            py36h14c3975_0  
attrs                     17.3.0           py36h5ab58ff_0  
babel                     2.5.1                    py36_0  
backports                 1.0              py36hfa02d7e_1  
backports.shutil_get_terminal_size 1.0.0            py36hfea85ff_2  
beautifulsoup4            4.6.0            py36h49b8c8c_1  
bitarray                  0.8.1            py36h5834eb8_0  
blas                      1.1                    openblas    conda-forge
blaze                     0.11.3           py36h4e06776_0  
bleach                    2.1.2                    py36_0  
bokeh                     0.12.13          py36h2f9c1c0_0  
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
boto                      2.48.0           py36h6e4cd66_1  
bottleneck                1.2.1            py36haac1ea0_0  
bzip2                     1.0.6                h6d464ef_2  
ca-certificates           2017.08.26           h1d4fec5_0  
cairo                     1.14.10              hdf128ce_6  
certifi                   2017.11.5        py36hf29ccca_0  
cffi                      1.11.2           py36h2825082_0  
chardet                   3.0.4            py36h0f667ec_1  
click                     6.7              py36h5253387_0  
cloudpickle               0.5.2            py36h84cdd9c_0  
clyent                    1.2.2            py36h7e57e65_1  
colorama                  0.3.9            py36h489cec4_0  
contextlib2               0.5.5            py36h6c84a62_0  
coverage                  4.4.2            py36hca7c4c5_0  
cryptography              2.1.4            py36hd09be54_0  
curl                      7.55.1               h78862de_4  
cycler                    0.10.0           py36h93f1223_0  
cython                    0.27.3           py36h1860423_0  
cytoolz                   0.8.2            py36h708bfd4_0  
dask                      0.16.1                   py36_0  
dask-core                 0.16.1                   py36_0  
datashape                 0.5.4            py36h3ad6b5c_0  
dbus                      1.10.22              h3b5a359_0  
debtcollector             1.19.0                    <pip>
decorator                 4.1.2            py36hd076ac8_0  
distributed               1.20.2                   py36_0  
docutils                  0.14             py36hb0f60f5_0  
entrypoints               0.2.3            py36h1aec115_2  
enum-compat               0.0.2                     <pip>
et_xmlfile                1.0.1            py36hd6bccc3_0  
eventlet                  0.20.0                    <pip>
expat                     2.2.5                he0dffb1_0  
fastcache                 1.0.2            py36h5b0c431_0  
fasteners                 0.14.1                    <pip>
flask                     0.12.2           py36hb24657c_0  
flask-cors                3.0.3            py36h2d857d3_0  
fontconfig                2.12.4               h88586e7_1  
freetype                  2.8                  hab7d2ae_1  
freexl                    1.0.5                h470a237_2    conda-forge
gdal                      2.2.2            py36hc209d97_1  
geos                      3.6.2                hfc679d8_4    conda-forge
get_terminal_size         1.0.0                haa9412d_0  
gevent                    1.2.2            py36h2fe25dc_0  
giflib                    5.1.4                h470a237_1    conda-forge
glib                      2.53.6               h5d9569c_2  
gmp                       6.1.2                h6c8ec71_1  
gmpy2                     2.0.8            py36hc8893dd_2  
graphite2                 1.3.10               hc526e54_0  
greenlet                  0.4.12           py36h2d503a6_0  
gst-plugins-base          1.12.2               he3457e5_0  
gstreamer                 1.12.2               h4f93127_0  
h5py                      2.7.1            py36h3585f63_0  
harfbuzz                  1.5.0                h2545bd6_0  
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1               h9caa474_1  
heapdict                  1.0.0            py36h79797d7_0  
html5lib                  1.0.1            py36h2f9c1c0_0  
hypothesis                3.38.5           py36h196a6cc_0  
hypre                     2.15.0               hfbb3b56_0    conda-forge
icu                       58.2                 h9c2bf20_1  
idna                      2.6              py36h82fb2a8_1  
imageio                   2.2.0            py36he555465_0  
imagesize                 0.7.1            py36h52d8127_0  
intel-openmp              2018.0.0             hc7b2577_8  
ipykernel                 4.7.0            py36h2f9c1c0_0  
ipython                   6.2.1            py36h88c514a_1  
ipython_genutils          0.2.0            py36hb52b0d5_0  
ipywidgets                7.1.0                    py36_0  
iso8601                   0.1.12                    <pip>
isort                     4.2.15           py36had401c0_0  
itsdangerous              0.24             py36h93cc618_1  
jbig                      2.1                  hdba287a_0  
jdcal                     1.3              py36h4c697fb_0  
jedi                      0.11.0                   py36_2  
jinja2                    2.10             py36ha16c418_0  
jpeg                      9b                   h024ee3a_2  
json-c                    0.12.1               h470a237_1    conda-forge
jsonschema                2.6.0            py36h006f8b5_0  
jupyter                   1.0.0            py36h9896ce5_0  
jupyter_client            5.2.1                    py36_0  
jupyter_console           5.2.0            py36he59e554_1  
jupyter_core              4.4.0            py36h7c827e3_0  
kealib                    1.4.8                hfc679d8_0    conda-forge
keystoneauth1             3.4.0                     <pip>
krb5                      1.14.6                        0    conda-forge
lazy-object-proxy         1.3.1            py36h10fcdad_0  
libdap4                   3.19.1                        0    conda-forge
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                hd88cf55_4  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 7.2.0                h7cc24e2_2  
libgdal                   2.2.2                h804cdde_1  
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                h9f7466a_2  
libiconv                  1.15                 h63c8f33_5  
libkml                    1.3.0                hccc92b1_8    conda-forge
libnetcdf                 4.4.1.1                      10    conda-forge
libpng                    1.6.32               hbd3595f_4  
libpq                     9.6.6                h4e02ad2_0  
libsodium                 1.0.15               hf101ebd_0  
libspatialite             4.3.0a                       19    conda-forge
libssh2                   1.8.0                h2d05a93_3  
libstdcxx-ng              7.2.0                h7a57d05_2  
libtiff                   4.0.9                h28f6b97_0  
libtool                   2.4.6                h544aabb_3  
libxcb                    1.12                 hcd93eb1_4  
libxml2                   2.9.4                h2e8b1d7_6  
libxslt                   1.1.29               h78d5cac_6  
llvmlite                  0.21.0           py36ha241eea_0  
locket                    0.2.0            py36h787c0ad_1  
lxml                      4.1.1            py36h4d89739_0  
lzo                       2.10                 h49e0be7_2  
markupsafe                1.0              py36hd9260cd_1  
matplotlib                2.1.1            py36ha26af80_0  
mccabe                    0.6.1            py36h5ad9710_1  
metis                     5.1.0                         0    menpo
mistune                   0.8.1            py36h3d5977c_0  
mkl                       2018.0.1             h19d6760_4  
mkl-service               1.1.2            py36h17a0993_4  
monotonic                 1.4                       <pip>
mpc                       1.0.3                hec55b23_5  
mpfr                      3.1.5                h11a74b3_2  
mpi                       1.0                     openmpi    conda-forge
mpmath                    1.0.0            py36hfeacd6b_2  
msgpack                   0.5.6                     <pip>
msgpack-python            0.5.1            py36h6bb024c_0  
multipledispatch          0.4.9            py36h41da3fb_0  
mumps-mpi                 5.1.2           blas_openblash3277127_0  [blas_openblas]  conda-forge
mysql-connector-python    2.1.7                     <pip>
navigator-updater         0.1.0            py36h14770f7_0  
nbconvert                 5.3.1            py36hb41ffb7_0  
nbformat                  4.4.0            py36h31c9010_0  
ncurses                   6.0                  h9df7e31_2  
netaddr                   0.7.19                    <pip>
netifaces                 0.10.6                    <pip>
networkx                  2.0              py36h7e96fb8_0  
nltk                      3.2.5            py36h7532b22_0  
nose                      1.3.7            py36hcdf7029_2  
notebook                  5.2.2            py36h40a37e6_0  
numba                     0.36.2          np113py36h7a10136_0  
numexpr                   2.6.4            py36hc4a3f9a_0  
numpy                     1.15.2          py36_blas_openblashd3ea46f_1  [blas_openblas]  conda-forge
numpydoc                  0.7.0            py36h18f165f_0  
odo                       0.5.1            py36h90ed295_0  
olefile                   0.44             py36h79f9f78_0  
openblas                  0.2.20                        8    conda-forge
openjpeg                  2.3.0                         2    conda-forge
openmpi                   3.1.2                h26a2512_2    conda-forge
openpyxl                  2.4.9            py36hb5dfbf6_0  
openssl                   1.0.2n               hb7f436b_0  
os-brick                  2.4.0                     <pip>
os-win                    4.0.0                     <pip>
oslo.concurrency          3.26.0                    <pip>
oslo.config               5.2.0                     <pip>
oslo.context              2.20.0                    <pip>
oslo.i18n                 3.20.0                    <pip>
oslo.log                  3.37.0                    <pip>
oslo.privsep              1.28.0                    <pip>
oslo.serialization        2.25.0                    <pip>
oslo.service              1.30.0                    <pip>
oslo.utils                3.36.0                    <pip>
packaging                 16.8             py36ha668100_1  
pandas                    0.22.0           py36hf484d3e_0  
pandoc                    1.19.2.1             hea2e7c5_1  
pandocfilters             1.4.2            py36ha6701b7_1  
pango                     1.40.11              h8191d47_0  
parmetis                  4.0.3                hc48fe69_2    conda-forge
parso                     0.1.1            py36h35f843b_0  
partd                     0.3.8            py36h36fd896_0  
Paste                     2.0.3                     <pip>
PasteDeploy               1.5.2                     <pip>
path.py                   10.5             py36h55ceabb_0  
pathlib2                  2.3.0            py36h49efa8e_0  
patsy                     0.4.1            py36ha3be15e_0  
pbr                       3.1.1                     <pip>
pcre                      8.41                 hc27e229_1  
pep8                      1.7.1                    py36_0  
petsc                     3.10.2          blas_openblash1308f21_0  [blas_openblas]  conda-forge
petsc4py                  3.10.0           py36h0812000_1    conda-forge
pexpect                   4.3.1                    py36_0  
pickleshare               0.7.4            py36h63277f8_0  
pillow                    5.0.0            py36h3deb7b8_0  
pip                       9.0.3                     <pip>
pip                       9.0.1            py36h6c6f9ce_4  
pixman                    0.34.0               hceecf20_3  
pluggy                    0.6.0            py36hb689045_0  
ply                       3.10             py36hed35086_0  
poppler                   0.60.1               hc909a00_0  
poppler-data              0.4.9                         1    conda-forge
prettytable               0.7.2                     <pip>
proj4                     4.9.3                hc8507d1_7  
prompt_toolkit            1.0.15           py36h17d85b1_0  
psutil                    5.4.3            py36h14c3975_0  
ptscotch                  6.0.6                h7a7e0c4_0    conda-forge
ptyprocess                0.5.2            py36h69acd42_0  
py                        1.5.2            py36h29bf505_0  
pycodestyle               2.3.1            py36hf609f19_0  
pycosat                   0.6.3            py36h0a5515d_0  
pycparser                 2.18             py36hf9f622e_1  
pycrypto                  2.6.1            py36h6998063_1  
pycurl                    7.43.0           py36h5e72054_3  
pyflakes                  1.6.0            py36h7bd6a15_0  
pygments                  2.2.0            py36h0d3125c_0  
pyinotify                 0.9.6                     <pip>
pylint                    1.7.4            py36hb9d4533_0  
pympler                   0.5              py36h6b12e4d_0  
pyodbc                    4.0.21           py36h083aac6_0  
pyopenssl                 17.5.0           py36h20ba746_0  
pyparsing                 2.2.0            py36hee85983_1  
pyqt                      5.6.0            py36h0386399_5  
pysocks                   1.6.7            py36hd97a5b1_1  
pytables                  3.4.2            py36h3b5282a_2  
pytest                    3.3.0            py36h23ce9bc_0  
python                    3.6.4                hc3d631a_0  
python-dateutil           2.6.1            py36h88d3b88_1  
python-levenshtein        0.12.0                   py36_0    conda-forge
pytz                      2017.3           py36h63b9c63_0  
pywavelets                0.5.2            py36he602eb0_0  
pyyaml                    3.12             py36hafb9ca4_1  
pyzmq                     16.0.3           py36he2533c7_0  
qt                        5.6.2               h974d657_12  
qtawesome                 0.4.4            py36h609ed8c_0  
qtconsole                 4.3.1            py36h8f73b5b_0  
qtpy                      1.3.1            py36h3691cc8_0  
quaternion                2018.11.3.1.0.41  py36he59b558_0    conda-forge
readline                  7.0                  ha6073c6_4  
repoze.lru                0.7                       <pip>
requests                  2.18.4           py36he2e5f8d_1  
retrying                  1.3.3                     <pip>
rfc3986                   1.1.0                     <pip>
rope                      0.10.7           py36h147e2ec_0  
Routes                    2.4.1                     <pip>
ruamel_yaml               0.11.14          py36ha2fb22d_2  
scalapack                 2.0.2                h3c96f6f_3    conda-forge
scikit-image              0.13.1           py36h14c3975_1  
scikit-learn              0.19.1           py36h7aa7ec6_0  
scipy                     1.0.0            py36hbf646e7_0  
scotch                    6.0.6                hc058ab9_0    conda-forge
seaborn                   0.8.1            py36hfad7ec4_0  
setuptools                36.5.0           py36he42e2e1_0  
setuptools                39.0.1                    <pip>
shapely                   1.6.4            py36h164cb2d_1    conda-forge
simplegeneric             0.8.1            py36h2cb9092_0  
simplejson                3.13.2                    <pip>
singledispatch            3.4.0.3          py36h7a266c3_0  
sip                       4.18.1           py36h51ed4ed_2  
six                       1.11.0           py36h372c433_1  
snowballstemmer           1.2.1            py36h6febd40_0  
sortedcollections         0.5.3            py36h3c761f9_0  
sortedcontainers          1.5.7            py36hdf89491_0  
sphinx                    1.6.3            py36he5f0bdb_0  
sphinxcontrib             1.0              py36h6d0f590_1  
sphinxcontrib-websupport  1.0.1            py36hb5cb234_1  
spyder                    3.2.6                    py36_0  
sqlalchemy                1.1.13           py36hfb5efd7_0  
sqlite                    3.20.1               hb898158_2  
statsmodels               0.8.0            py36h8533d0b_0  
stevedore                 1.28.0                    <pip>
suitesparse               4.5.6           blas_openblash55dcaef_201  [blas_openblas]  conda-forge
sympy                     1.1.1            py36hc6d1c1c_0  
tbb                       2019.2               h2d50403_0    conda-forge
tblib                     1.3.2            py36h34cf8b6_0  
terminado                 0.6              py36ha25a19f_0  
testpath                  0.3.1            py36h8cadb63_0  
tk                        8.6.7                hc745277_3  
toolz                     0.8.2            py36h81f2dff_0  
tornado                   4.5.2            py36h1283b2a_0  
traitlets                 4.3.2            py36h674d592_0  
typing                    3.6.2            py36h7da032a_0  
unicodecsv                0.14.1           py36ha668878_0  
unixodbc                  2.3.4                hc36303a_1  
urllib3                   1.22             py36hbe7ace6_0  
util-linux                2.21                          0  
virtualenv                15.1.0                   py36_0  
vtk                       7.0.0                    py36_0    menpo
wcwidth                   0.1.7            py36hdf4376a_0  
webencodings              0.5.1            py36h800622e_1  
WebOb                     1.7.4                     <pip>
werkzeug                  0.12.2           py36hc703753_0  
wheel                     0.30.0           py36hfd4bba0_1  
widgetsnbextension        3.0.8            py36h25a1d49_0  
wrapt                     1.10.11          py36h28b7045_0  
xerces-c                  3.2.2                h5d6a6da_1    conda-forge
xlrd                      1.1.0            py36h1db9f0c_1  
xlsxwriter                1.0.2            py36h3de1aca_0  
xlwt                      1.3.0            py36h7b00a1f_0  
xz                        5.2.3                h55aa19d_2  
yaml                      0.1.7                had09818_2  
zeromq                    4.2.2                hbedb6e5_2  
zict                      0.1.3            py36h3a3bf81_0  
zlib                      1.2.11               ha838bed_2  
zope                      1.0                      py36_0  
zope.interface            4.4.3            py36h0ccbf34_0 

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
     active environment : pers
    active env location : /home/s4080143/.conda/envs/pers
            shell level : 1
       user config file : /home/s4080143/.condarc
 populated config files : /home/s4080143/.condarc
          conda version : 4.4.7
    conda-build version : not installed
         python version : 3.6.4.final.0
       base environment : /sw/taurus/libraries/python/3.6-anaconda4.4.0  (read only)
           channel URLs : https://conda.anaconda.org/menpo/linux-64
                          https://conda.anaconda.org/menpo/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /sw/taurus/libraries/python/3.6-anaconda4.4.0/pkgs
                          /home/s4080143/.conda/pkgs
       envs directories : /home/s4080143/.conda/envs
                          /sw/taurus/libraries/python/3.6-anaconda4.4.0/envs
               platform : linux-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/3.6.4 Linux/3.10.0-693.21.1.el7.x86_64 rhel/7.4 glibc/2.17
                UID:GID : 1053040:50485
             netrc file : None
           offline mode : False
```
</details>

This issue is related to [that one](https://github.com/conda-forge/gdal-feedstock/issues/275). It was reportedly fixed but I'm still experiencing the error. I ran `conda install gdal` which appeared to be successful, but `from osgeo import ogr` fails with the following message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/s4080143/.conda/envs/pers/lib/python3.6/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/s4080143/.conda/envs/pers/lib/python3.6/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/s4080143/.conda/envs/pers/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/s4080143/.conda/envs/pers/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libkea.so.1.4.7: cannot open shared object file: No such file or directory
```

**Comment by ocefpaf** [comment]
This is a classic case of mixed channel. Please update your `conda` and see https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it

**Comment by baloe** [comment]
@ocefpaf the instructions which you referred to only apply to conda >=4.6, I'm using 4.4.7 though.
So I can only solve this issue by having my server admins upgrade anaconda  or by installing my own anaconda?

**Comment by ocefpaf** [comment]
> @ocefpaf the instructions which you referred to only apply to conda >=4.6, I'm using 4.4.7 though.
> So I can only solve this issue by having my server admins upgrade anaconda or by installing my own anaconda?

Like I mention you have to update your `conda` first. If your server admin can do it great. If not, code was created to be a user space software, so get miniconda and configured it your way on your user space.
