### ISSUE TITLE
gdal broken because of icu update

### ISSUE THREAD

**Issue by cpaulik** [conda-forge/gdal-feedstock#313]
Hi again :smile: 

It seems that a fresh gdal environment does not work because of a `icu` update.

A `conda install -c conda-forge "icu<64"` fixes it.

See below:

```
conda create -n test gdal                       
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.5
  latest version: 4.7.10

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/test

  added / updated specs:
    - gdal


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    boost-cpp-1.70.0           |       h8e57a91_2        21.1 MB  conda-forge
    cairo-1.16.0               |    hfb77d84_1002         1.5 MB  conda-forge
    certifi-2019.6.16          |           py37_1         149 KB  conda-forge
    curl-7.65.3                |       hf8cf82a_0         132 KB  conda-forge
    fontconfig-2.13.1          |    h86ecdb6_1001         340 KB  conda-forge
    gdal-3.0.1                 |   py37h5f563d9_4         1.2 MB  conda-forge
    icu-64.2                   |       he1b5a44_0        12.6 MB  conda-forge
    libcurl-7.65.3             |       hda55be3_0         575 KB  conda-forge
    libgdal-3.0.1              |       h0845e09_4        18.6 MB  conda-forge
    libpq-11.4                 |       hd9ab2ff_3         2.5 MB  conda-forge
    libxml2-2.9.9              |       hee79883_2         1.3 MB  conda-forge
    poppler-0.67.0             |       ha967d66_7         8.9 MB  conda-forge
    postgresql-11.4            |       hc63931a_3         4.8 MB  conda-forge
    tiledb-1.6.0               |       h69c774e_1         2.1 MB  conda-forge
    xerces-c-3.2.2             |    h8412b87_1004         1.7 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        77.5 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  boost-cpp          conda-forge/linux-64::boost-cpp-1.70.0-h8e57a91_2
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h516909a_0
  ca-certificates    conda-forge/linux-64::ca-certificates-2019.6.16-hecc5488_0
  cairo              conda-forge/linux-64::cairo-1.16.0-hfb77d84_1002
  certifi            conda-forge/linux-64::certifi-2019.6.16-py37_1
  cfitsio            conda-forge/linux-64::cfitsio-3.470-hb60a0a2_1
  curl               conda-forge/linux-64::curl-7.65.3-hf8cf82a_0
  expat              conda-forge/linux-64::expat-2.2.5-he1b5a44_1003
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-h86ecdb6_1001
  freetype           conda-forge/linux-64::freetype-2.10.0-he983fc9_0
  freexl             conda-forge/linux-64::freexl-1.0.5-h14c3975_1002
  gdal               conda-forge/linux-64::gdal-3.0.1-py37h5f563d9_4
  geos               conda-forge/linux-64::geos-3.7.2-he1b5a44_1
  geotiff            conda-forge/linux-64::geotiff-1.5.1-h560c3f3_2
  gettext            conda-forge/linux-64::gettext-0.19.8.1-hc5be6a0_1002
  giflib             conda-forge/linux-64::giflib-5.1.7-h516909a_1
  glib               conda-forge/linux-64::glib-2.58.3-h6f030ca_1002
  hdf4               conda-forge/linux-64::hdf4-4.2.13-h9a582f1_1002
  hdf5               conda-forge/linux-64::hdf5-1.10.5-nompi_h3c11f04_1100
  icu                conda-forge/linux-64::icu-64.2-he1b5a44_0
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  json-c             conda-forge/linux-64::json-c-0.13.1-h14c3975_1001
  kealib             conda-forge/linux-64::kealib-1.4.10-h58c409b_1005
  krb5               conda-forge/linux-64::krb5-1.16.3-h05b26f9_1001
  libblas            conda-forge/linux-64::libblas-3.8.0-10_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-10_openblas
  libcurl            conda-forge/linux-64::libcurl-7.65.3-hda55be3_0
  libdap4            conda-forge/linux-64::libdap4-3.19.1-hd48c02d_1000
  libedit            conda-forge/linux-64::libedit-3.1.20170329-hf8c457e_1001
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1006
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libgdal            conda-forge/linux-64::libgdal-3.0.1-h0845e09_4
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-7.3.0-hdf63c60_0
  libiconv           conda-forge/linux-64::libiconv-1.15-h516909a_1005
  libkml             conda-forge/linux-64::libkml-1.3.0-h4fcabce_1010
  liblapack          conda-forge/linux-64::liblapack-3.8.0-10_openblas
  libnetcdf          conda-forge/linux-64::libnetcdf-4.6.2-h056eaf5_1002
  libopenblas        conda-forge/linux-64::libopenblas-0.3.6-h6e990d7_4
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_0
  libpq              conda-forge/linux-64::libpq-11.4-hd9ab2ff_3
  libspatialite      conda-forge/linux-64::libspatialite-4.3.0a-he1bb1e1_1029
  libssh2            conda-forge/linux-64::libssh2-1.8.2-h22169c7_2
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  libtiff            conda-forge/linux-64::libtiff-4.0.10-h57b8799_1003
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxml2            conda-forge/linux-64::libxml2-2.9.9-hee79883_2
  lz4-c              conda-forge/linux-64::lz4-c-1.8.3-he1b5a44_1001
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  numpy              conda-forge/linux-64::numpy-1.16.4-py37h95a1406_0
  openblas           conda-forge/linux-64::openblas-0.3.6-h6e990d7_4
  openjpeg           conda-forge/linux-64::openjpeg-2.3.1-h58a6597_0
  openssl            conda-forge/linux-64::openssl-1.1.1c-h516909a_0
  pcre               conda-forge/linux-64::pcre-8.41-hf484d3e_1003
  pip                conda-forge/linux-64::pip-19.1.1-py37_0
  pixman             conda-forge/linux-64::pixman-0.38.0-h516909a_1003
  poppler            conda-forge/linux-64::poppler-0.67.0-ha967d66_7
  poppler-data       conda-forge/noarch::poppler-data-0.4.9-1
  postgresql         conda-forge/linux-64::postgresql-11.4-hc63931a_3
  proj4              conda-forge/linux-64::proj4-6.1.0-he751ad9_2
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  python             conda-forge/linux-64::python-3.7.3-h33d41f4_1
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  setuptools         conda-forge/linux-64::setuptools-41.0.1-py37_0
  sqlite             conda-forge/linux-64::sqlite-3.29.0-hcee41ef_0
  tbb                conda-forge/linux-64::tbb-2018.0.5-h2d50403_0
  tiledb             conda-forge/linux-64::tiledb-1.6.0-h69c774e_1
  tk                 conda-forge/linux-64::tk-8.6.9-hed695b0_1002
  tzcode             conda-forge/linux-64::tzcode-2019a-h516909a_1002
  wheel              conda-forge/linux-64::wheel-0.33.4-py37_0
  xerces-c           conda-forge/linux-64::xerces-c-3.2.2-h8412b87_1004
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h14c3975_1002
  xorg-libice        conda-forge/linux-64::xorg-libice-1.0.10-h516909a_0
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.3-h84519dc_1000
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.6.8-h516909a_0
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h516909a_0
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.4-h516909a_0
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.10-h516909a_1002
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h14c3975_1002
  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h14c3975_1002
  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h14c3975_1007
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1005
  zstd               conda-forge/linux-64::zstd-1.4.0-h3b9ef0a_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
libgdal-3.0.1        | 18.6 MB   | ################################################################################################################################################################################################## | 100% 
cairo-1.16.0         | 1.5 MB    | ################################################################################################################################################################################################## | 100% 
tiledb-1.6.0         | 2.1 MB    | ################################################################################################################################################################################################## | 100% 
gdal-3.0.1           | 1.2 MB    | ################################################################################################################################################################################################## | 100% 
libxml2-2.9.9        | 1.3 MB    | ################################################################################################################################################################################################## | 100% 
postgresql-11.4      | 4.8 MB    | ################################################################################################################################################################################################## | 100% 
poppler-0.67.0       | 8.9 MB    | ################################################################################################################################################################################################## | 100% 
fontconfig-2.13.1    | 340 KB    | ################################################################################################################################################################################################## | 100% 
xerces-c-3.2.2       | 1.7 MB    | ################################################################################################################################################################################################## | 100% 
curl-7.65.3          | 132 KB    | ################################################################################################################################################################################################## | 100% 
libcurl-7.65.3       | 575 KB    | ################################################################################################################################################################################################## | 100% 
libpq-11.4           | 2.5 MB    | ################################################################################################################################################################################################## | 100% 
icu-64.2             | 12.6 MB   | ################################################################################################################################################################################################## | 100% 
boost-cpp-1.70.0     | 21.1 MB   | ################################################################################################################################################################################################## | 100% 
certifi-2019.6.16    | 149 KB    | ################################################################################################################################################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate


╭ Lx  cpa@cpaulik-laptop    workspace  vdsdb  vdsdb 
├─ miniconda2-4.3.30/envs/vdsdb-37                                                                                                                                                                   ✔  02:04 Dur   master v1.2.14 ? ⍟2
╰❯ conda activate test      

╭ Lx  cpa@cpaulik-laptop    workspace  vdsdb  vdsdb 
├─ miniconda2-4.3.30/envs/vdsdb-37                                                                                                                                                                               ✔   master v1.2.14 ? ⍟2
╰❯ python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/test/lib/python3.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/test/lib/python3.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/test/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/test/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libicui18n.so.58: cannot open shared object file: No such file or directory
>>> exit()


```

**Comment by ocefpaf** [comment]
I fixed version `2.4.1` over the weekend. Working on `2.4.2` and `3.0.1` today.

**Comment by djhoese** [comment]
@ocefpaf Strange thing happened since the newest 2.4.2 packages hit `anaconda.org`. My automated testing (local jenkins server) builds a new environment and now gets gdal 2.3.3 even though the previous build (same `environment.yml` I think, about 30 minutes before you merged #314) got gdal 2.4.1. I would guess that's because something else I'm using is depending on old icu? I'll rerun the jenkins job just in case it was a weird race condition between new packages being available and you possibly deleting old/bad packages.

**Comment by ocefpaf** [comment]
@djhoese it takes ~50 min for the CDN to sync do you are getting old `gdal` (probably from `defaults`) b/c the new ones are not in the channel yet.

**Comment by ocefpaf** [comment]
@cpaulik and @djhoese can you try it again? Hopefully I re-created package for all the current use cases and combinations we have in conda-forge at the moment.

**Comment by cpaulik** [comment]
Thanks @ocefpaf . It seems to work in all our pipelines.

I hope to not talk to you for a while now :smiley:

**Comment by djhoese** [comment]
@ocefpaf On OSX doing `conda create -n satpy_py37 python=3.7 satpy rasterio matplotlib gdal` still results in 2.3.3 being preferred. I'm guessing this is from the `h5py` dependency like you mentioned?

On my jenkins CI tests, looks like I'm getting gdal 2.4.1.

**Comment by ocefpaf** [comment]
> I hope to not talk to you for a while now

You can talk to me about non-gdal issue :smile:



> @ocefpaf On OSX doing `conda create -n satpy_py37 python=3.7 satpy rasterio matplotlib gdal` still results in 2.3.3 being preferred. I'm guessing this is from the `h5py` dependency like you mentioned?
> 
> On my jenkins CI tests, looks like I'm getting gdal 2.4.1.
> 
> Edit: Got lost in all the notifications, I see that this 2.4.1 _might_ be expected?

Yep. `2.4.1` is the only one with old `proj4 <6` and old `hdf5`. If you remove rasterio (that requires old proj4) you can get `gdal 2.4.2` with the old `hdf5`.

**Comment by djhoese** [comment]
Doesn't this mean that I should expect 2.4.1 on my OSX environment too (instead of 2.3.3 which is what I'm getting)?

**Comment by djhoese** [comment]
Note: Just did `gdal=2.4.1` on my OSX system and that resolved. Not sure why not forcing the version is jumping down to `2.3.3`. I guess I'm satisfied enough right now.

**Comment by ocefpaf** [comment]
> Doesn't this mean that I should expect 2.4.1 on my OSX environment too (instead of 2.3.3 which is what I'm getting)?

Yep. Not sure why conda is not preferring that :-/
