### ISSUE TITLE
gdal broken because of tiledb update

### ISSUE THREAD

**Issue by cpaulik** [conda-forge/gdal-feedstock#327]
Hi,

Same story as always :smile: 

```
conda create -n gdal-tiledb-test -c conda-forge gdal
conda activate gdal-tiledb-test

python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gdal-tiledb-test/lib/python3.7/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gdal-tiledb-test/lib/python3.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gdal-tiledb-test/lib/python3.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gdal-tiledb-test/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gdal-tiledb-test/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libtiledb.so.1.6.0: cannot open shared object file: No such file or directory
```

## conda list output

```
# packages in environment at /home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gdal-tiledb-test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
bzip2                     1.0.8                h516909a_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
expat                     2.2.5             he1b5a44_1003    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
gdal                      3.0.1            py37h5f563d9_6    conda-forge
geos                      3.7.2                he1b5a44_1    conda-forge
geotiff                   1.5.1                h560c3f3_2    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3            h6f030ca_1002    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1100    conda-forge
icu                       64.2                 he1b5a44_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
kealib                    1.4.10            h58c409b_1005    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdap4                   3.20.2            hd48c02d_1000    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgdal                   3.0.1                hbef8c27_6    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0               12_openblas    conda-forge
libnetcdf                 4.6.2             h056eaf5_1002    conda-forge
libopenblas               0.3.7                h6e990d7_1    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     11.5                 hd9ab2ff_0    conda-forge
libspatialite             4.3.0a            he1bb1e1_1029    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10            h57b8799_1003    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                hee79883_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.17.0           py37h95a1406_0    conda-forge
openjpeg                  2.3.1                h58a6597_0    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pip                       19.2.2                   py37_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
poppler                   0.67.0               ha967d66_7    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.5                 hc63931a_0    conda-forge
proj4                     6.1.0                he751ad9_2    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
sqlite                    3.29.0               hcee41ef_0    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tiledb                    1.6.2                h69c774e_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.8                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1005    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge
```

**Comment by djhoese** [comment]
I brought this up on the tiledb package too: https://github.com/conda-forge/tiledb-feedstock/issues/39

@tdenniston pointed out that it was a bug in 1.6.1 that the `.so` wasn't named with `.1.6.1`. So I guess the question for `@tdenniston` is whether or not the patch part of the version number needs to be in the `.so` filename?

Does this mean `tiledb` needs to be added to conda-forge pinnings?

**Comment by ocefpaf** [comment]
I pulled the two `tiledb` newer builds, `1.6.1` and `1.6.2`, and left only the one that `gdal` was built with, `1.6.0`. I'm adding `tiledb` to the pinning package and proper `run_exports`. Things should normalize as soon as the CDNs syncs (~50 min). Let me know if you are still experiencing problems.

**Comment by djhoese** [comment]
@ocefpaf I'm still seeing the solver trying to find tiledb 1.6.2 but then failing with a HTTP 404 when trying to download. Will try rerunning it to see what happens.

**Comment by ocefpaf** [comment]
It works for me now. It may be a cache things trying to access a package that is no longer there :-/
