### ISSUE TITLE
libgdal.20.dylib links againsty Homebew libraries on OS X

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/gdal-feedstock#33]
The libgdal.20.dylib library shipped in 2.0.2 build 2 conda package links again Homebrew libraries which are not guaranteed to available on a user's system (and are not on my systems which uses MacPorts).  On systems without these libraries gdal is not importable.

```
$ wget https://anaconda.org/conda-forge/gdal/2.0.2/download/osx-64/gdal-2.0.2-np19py35_2.tar.bz2
...
$ tar xf gdal-2.0.2-np19py35_2.tar.bz2
...
$ otool -L lib/libgdal.20.dylib
lib/libgdal.20.dylib:
	@rpath/libgdal.20.dylib (compatibility version 21.0.0, current version 21.2.0)
	@rpath/libproj.9.dylib (compatibility version 10.0.0, current version 10.0.0)
	/usr/local/lib/libjson-c.2.dylib (compatibility version 3.0.0, current version 3.1.0)
	/usr/local/lib/libfreexl.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	@rpath/libgeos_c.1.dylib (compatibility version 10.0.0, current version 10.2.0)
	@rpath/libgeos-3.4.2.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libsqlite3.0.dylib (compatibility version 9.0.0, current version 9.6.0)
	/usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version 7.2.0)
	@rpath/./libxerces-c-3.1.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libopenjp2.7.dylib (compatibility version 7.0.0, current version 2.1.0)
	@rpath/./libnetcdf.7.dylib (compatibility version 10.0.0, current version 10.0.0)
	/usr/local/lib/libgif.4.1.6.dylib (compatibility version 6.0.0, current version 6.6.0)
	/usr/local/lib/libgeotiff.2.dylib (compatibility version 4.0.0, current version 4.0.0)
	@rpath/libtiff.5.dylib (compatibility version 8.0.0, current version 8.4.0)
	@rpath/liblzma.5.dylib (compatibility version 6.0.0, current version 6.5.0)
	@rpath/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
	@rpath/libpng16.16.dylib (compatibility version 34.0.0, current version 34.0.0)
	/usr/local/lib/libpq.5.dylib (compatibility version 5.0.0, current version 5.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	@rpath/libcurl.4.dylib (compatibility version 9.0.0, current version 9.0.0)
	@rpath/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	@rpath/./libkea.1.4.5.dylib (compatibility version 1.4.5, current version 1.4.5)
	@rpath/./libhdf5_hl.10.dylib (compatibility version 11.0.0, current version 11.1.0)
	@rpath/./libhdf5_cpp.10.dylib (compatibility version 11.0.0, current version 11.1.0)
	@rpath/./libhdf5.10.dylib (compatibility version 11.0.0, current version 11.1.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 60.0.0)
```

Libraries in /usr/local/... are from Homebrew.

**Comment by ocefpaf** [comment]
The latest build number(`4`) should correct that. Can you take a look?

**Comment by jjhelmus** [comment]
Is there a version 2.0.2 build 4 for OS X?  I'm not seeing it on Anaconda.org

**Comment by jjhelmus** [comment]
gdal-1.11.4-np111py35_4.tar.bz2 still seems to link against Homebrew libraries

```
$ tar xf osx-64-gdal-1.11.4-np111py35_4.tar.bz2
...
$ otool -L lib/libgdal.1.dylib
lib/libgdal.1.dylib:
	@rpath/libgdal.1.dylib (compatibility version 20.0.0, current version 20.4.0)
	@rpath/libjson-c.2.dylib (compatibility version 3.0.0, current version 3.1.0)
	@rpath/./libexpat.1.dylib (compatibility version 8.0.0, current version 8.0.0)
	@rpath/./libxerces-c-3.1.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libopenjp2.7.dylib (compatibility version 7.0.0, current version 2.1.0)
	@rpath/libjasper.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	@rpath/./libnetcdf.7.dylib (compatibility version 10.0.0, current version 10.0.0)
	@rpath/./libhdf5_hl.10.dylib (compatibility version 11.0.0, current version 11.1.0)
	@rpath/./libhdf5.10.dylib (compatibility version 11.0.0, current version 11.1.0)
	@rpath/libgif.7.dylib (compatibility version 8.0.0, current version 8.0.0)
	/usr/local/lib/libgeotiff.2.dylib (compatibility version 4.0.0, current version 4.0.0)
	@rpath/libtiff.5.dylib (compatibility version 8.0.0, current version 8.4.0)
	@rpath/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
	@rpath/libpng16.16.dylib (compatibility version 34.0.0, current version 34.0.0)
	/usr/local/lib/libpq.5.dylib (compatibility version 5.0.0, current version 5.6.0)
	@rpath/libspatialite.7.dylib (compatibility version 9.0.0, current version 9.0.0)
	@rpath/liblzma.5.dylib (compatibility version 6.0.0, current version 6.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	@rpath/libfreexl.1.dylib (compatibility version 3.0.0, current version 3.0.0)
	@rpath/libcharset.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	@rpath/libproj.9.dylib (compatibility version 10.0.0, current version 10.0.0)
	@rpath/libgeos_c.1.dylib (compatibility version 10.0.0, current version 10.2.0)
	@rpath/libgeos-3.4.2.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libsqlite3.0.dylib (compatibility version 9.0.0, current version 9.6.0)
	@rpath/libcurl.4.dylib (compatibility version 9.0.0, current version 9.0.0)
	@rpath/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libxml2.2.dylib (compatibility version 12.0.0, current version 12.3.0)
	@rpath/libicui18n.56.dylib (compatibility version 56.0.0, current version 56.1.0)
	@rpath/libicuuc.56.dylib (compatibility version 56.0.0, current version 56.1.0)
	@rpath/libicudata.56.dylib (compatibility version 56.0.0, current version 56.1.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/libiconv.2.dylib (compatibility version 8.0.0, current version 8.1.0)
	@rpath/./libstdc++.6.dylib (compatibility version 7.0.0, current version 7.19.0)
```

**Comment by ocefpaf** [comment]
Nope, that is for gdal 1. But the PR was merged a few moments ago and I notice that the build number was not bumped.

https://github.com/conda-forge/gdal-feedstock/pull/31/files

**Comment by pelson** [comment]
> Nope, that is for gdal 1. But the PR was merged a few moments ago and I notice that the build number was not bumped.

Oh man! Does that mean more waiting for AppVeyor? GDAL is a killer 😄

**Comment by ocefpaf** [comment]
Let me bump the build number on `gdal 2`.  Now that I remember I haven't merge https://github.com/conda-forge/gdal-feedstock/pull/32 yet, so the homebrew fix  is not available for `gdal 1`.

**Comment by ocefpaf** [comment]
> Oh man! Does that mean more waiting for AppVeyor? GDAL is a killer

We can merge `gdal 2` bump right away :wink:

**Comment by ocefpaf** [comment]
@jjhelmus as soon as the binaries from #34 are up can you take a look and close this?

**Comment by jjhelmus** [comment]
Will do.

**Comment by jjhelmus** [comment]
Pulled the conda-forge gdal `np110py27_3` package and it looks to be free from Homebrew libraries.  I am able to import gdal fine on my system which uses MacPorts.  Unfortunately, numpy 1.10, Python 2.7 seems to be the only [Travis CI setup that got uploaded](https://travis-ci.org/conda-forge/gdal-feedstock/builds/121468082) because of conda-forge being [over its storage limit](https://travis-ci.org/conda-forge/gdal-feedstock/jobs/121468114).

```
[ERROR] 
Traceback (most recent call last):
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/binstar_client/commands/upload.py", line 214, in main
    callback=upload_print_callback(args))
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/binstar_client/__init__.py", line 474, in upload
    self._check_response(res)
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/binstar_client/__init__.py", line 196, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ('Storage requirements exceeded (3221225472 bytes). Payment is required to add a file. Please go to https://anaconda.org/binstar.settings/billing to update your plan', 402)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/anaconda", line 6, in <module>
    sys.exit(binstar_client.scripts.cli.main())
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 87, in main
    description=__doc__, version=version)
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 66, in binstar_main
    return args.main(args)
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/binstar_client/commands/upload.py", line 219, in main
    except requests_ext.OpenSslError:
TypeError: catching classes that do not inherit from BaseException is not allowed
Traceback (most recent call last):
  File "./ci_support/upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "./ci_support/upload_or_check_non_existence.py", line 108, in main
    upload(cli, meta, owner, channel)
  File "./ci_support/upload_or_check_non_existence.py", line 55, in upload
    env=os.environ)
  File "/Users/travis/miniconda3/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', 'binstar.token', 'upload', '/Users/travis/miniconda3/conda-bld/osx-64/gdal-2.0.2-np110py35_3.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1
```

**Comment by ocefpaf** [comment]
I am wiping all the `gdal` binaries and rebuilding them. All previous ones had the `homebrew` contamination anyways.

**Comment by jjhelmus** [comment]
Build `3` seems to be available on OS X for most version of Python and is working without Homebrew.  Closing issue.  Thanks for the quick fix!

**Comment by ocefpaf** [comment]
The rest is slowly making their way to the channel. Thanks for testing.
