### ISSUE TITLE
Incompatible library version

### ISSUE THREAD

**Issue by palaiya** [conda-forge/gdal-feedstock#335]
Issue:

I have been struggling from this issue since a while. I deleted my entire environment, created new environment reinstalled all the packages **STRICTLY FROM ONE CHANNEL** as mentioned below that is `conda-forge`.  But i am unable to get rid of the following exception. I could see [here](https://github.com/conda-forge/gdal-feedstock/issues/111) a lot of people are facing similar issue but there has been no solution posted so far.

```
Traceback (most recent call last):
  File "cloudmask.py", line 4, in <module>
    import earthpy.spatial as es
  File "/Users/Naresh/anaconda3/envs/starfm/lib/python3.7/site-packages/earthpy/spatial.py", line 15, in <module>
    import geopandas as gpd
  File "/Users/Naresh/anaconda3/envs/starfm/lib/python3.7/site-packages/geopandas/__init__.py", line 5, in <module>
    from geopandas.io.file import read_file  # noqa
  File "/Users/Naresh/anaconda3/envs/starfm/lib/python3.7/site-packages/geopandas/io/file.py", line 6, in <module>
    import fiona
  File "/Users/Naresh/anaconda3/envs/starfm/lib/python3.7/site-packages/fiona/__init__.py", line 83, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/Users/Naresh/anaconda3/envs/starfm/lib/python3.7/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/Naresh/anaconda3/envs/starfm/lib/python3.7/site-packages/fiona/ogrext.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libtiff.5.dylib
  Referenced from: /Users/Naresh/anaconda3/envs/starfm/lib/libgdal.20.dylib
  Reason: Incompatible library version: libgdal.20.dylib requires version 10.0.0 or later, but libtiff.5.dylib provides version 6.0.0

```

Here is my output of `.condarc`

```
auto_activate_base: false
ssl_verify: true
channels:
  - defaults
  - conda-forge
channel_priority: strict
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/Naresh/anaconda3/envs/starfm:
#
# Name                    Version                   Build  Channel
affine                    2.3.0                      py_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
appnope                   0.1.0                 py37_1000    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
astroid                   2.3.0                    py37_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
babel                     2.7.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
bokeh                     1.3.4                    py37_0    conda-forge
boost-cpp                 1.70.0               h75728bb_2    conda-forge
bzip2                     1.0.8                h01d97ff_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
cairo                     1.16.0            he1c11cd_1002    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
cffi                      1.12.3           py37hccf1714_0    conda-forge
cfitsio                   3.470                h84d2f63_2    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.2.2                      py_0    conda-forge
cryptography              2.7              py37h212c5bf_0    conda-forge
curl                      7.65.3               h22ea746_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.10.0           py37h01d97ff_0    conda-forge
dask                      2.5.0                      py_0    conda-forge
dask-core                 2.5.0                      py_0    conda-forge
dbus                      1.13.6               h2f22bb5_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
distributed               2.5.0                      py_0    conda-forge
docutils                  0.15.2                   py37_0    conda-forge
earthpy                   0.7.4                      py_0    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             h6de7cb9_1003    conda-forge
fasteners                 0.14.1                     py_3    conda-forge
fiona                     1.8.7            py37h238e834_0    conda-forge
fontconfig                2.13.1            h6b1039f_1001    conda-forge
freetype                  2.10.0               h24853df_1    conda-forge
freexl                    1.0.5             h1de35cc_1002    conda-forge
fsspec                    0.5.1                      py_0    conda-forge
gdal                      2.4.2            py37h39889d8_4    conda-forge
geopandas                 0.6.0                      py_0    conda-forge
geos                      3.7.2                h6de7cb9_2    conda-forge
geotiff                   1.5.1                h83de174_2    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.1.7                h01d97ff_1    conda-forge
glib                      2.58.3            h9d45998_1002    conda-forge
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.5          nompi_h15a436c_1103    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
imageio                   2.5.0                    py37_0    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge
ipython                   7.8.0            py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     4.3.21                   py37_0    conda-forge
jedi                      0.15.1                   py37_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
json-c                    0.13.1            h1de35cc_1001    conda-forge
jsonschema                3.0.2                    py37_0    conda-forge
jupyter_client            5.3.3                    py37_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kealib                    1.4.10            h6659575_1005    conda-forge
keyring                   19.2.0                   py37_0    conda-forge
kiwisolver                1.1.0            py37h770b8ee_0    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
lazy-object-proxy         1.4.2            py37h01d97ff_0    conda-forge
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libcurl                   7.65.3               h16faf7d_0    conda-forge
libcxx                    9.0.0                         0    conda-forge
libcxxabi                 9.0.0                         0    conda-forge
libdap4                   3.20.4               habf5908_0    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgdal                   2.4.2                hf77bb78_4    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
libkml                    1.3.0             hed7d534_1010    conda-forge
liblapack                 3.8.0               12_openblas    conda-forge
libnetcdf                 4.6.2             h1a02027_1003    conda-forge
libopenblas               0.3.7                h4bb4525_1    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libpq                     11.5                 h756f0eb_1    conda-forge
libsodium                 1.0.17               h01d97ff_0    conda-forge
libspatialindex           1.9.0                h6de7cb9_1    conda-forge
libspatialite             4.3.0a            he369b6e_1029    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.0.10            hd08fb8f_1003    conda-forge
libxml2                   2.9.9                h12c6b28_5    conda-forge
llvm-openmp               9.0.0                h40edb58_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
markupsafe                1.1.1            py37h1de35cc_0    conda-forge
matplotlib                3.1.1                    py37_1    conda-forge
matplotlib-base           3.1.1            py37h3a684a6_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py37h1de35cc_1000    conda-forge
monotonic                 1.5                        py_0    conda-forge
msgpack-python            0.6.2            py37h770b8ee_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
nbconvert                 5.6.0                    py37_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
networkx                  2.3                        py_0    conda-forge
numcodecs                 0.6.3            py37h0a44026_0    conda-forge
numpy                     1.17.2           py37h6b0580a_0    conda-forge
numpydoc                  0.9.1                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                hdc36067_1    conda-forge
openssl                   1.1.1c               h01d97ff_0    conda-forge
packaging                 19.2                       py_0    conda-forge
pandas                    0.25.1           py37h86efe34_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.5.1                      py_0    conda-forge
partd                     1.0.0                      py_0    conda-forge
pcre                      8.41              h0a44026_1003    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    6.1.0            py37h75ffe9a_1    conda-forge
pip                       19.2.3                   py37_0    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
poppler                   0.67.0               hd5eb092_7    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.5                 h25afefd_1    conda-forge
proj4                     6.1.0                h2cc77ee_2    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
psutil                    5.6.3            py37h01d97ff_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pylint                    2.4.1                    py37_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
pyproj                    2.2.1            py37h804dea5_0    conda-forge
pyqt                      5.9.2            py37h2a560b1_4    conda-forge
pyrsistent                0.15.4           py37h01d97ff_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
python                    3.7.3                h93065d6_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python.app                1.2             py37h1de35cc_1200    conda-forge
pytz                      2019.2                     py_0    conda-forge
pywavelets                1.0.3            py37h1e5eb4f_1    conda-forge
pyyaml                    5.1.2            py37h01d97ff_0    conda-forge
pyzmq                     18.1.0           py37hee98d25_0    conda-forge
qt                        5.9.7                h8cf7e54_3    conda-forge
qtawesome                 0.6.0                      py_0    conda-forge
qtconsole                 4.5.5                      py_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
rasterio                  1.0.28           py37h238e834_1    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
rope                      0.14.0                     py_0    conda-forge
rtree                     0.8.3           py37h666c49c_1002    conda-forge
scikit-image              0.15.0           py37h86efe34_2    conda-forge
scipy                     1.3.1            py37h7e0e109_2    conda-forge
setuptools                41.2.0                   py37_0    conda-forge
shapely                   1.6.4           py37h0567c5e_1006    conda-forge
sip                       4.19.8          py37h0a44026_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
snowballstemmer           1.9.1                      py_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sphinx                    2.2.0                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
spyder                    3.3.6                    py37_0    conda-forge
spyder-kernels            0.5.2                    py37_0    conda-forge
sqlite                    3.29.0               hb7d70f7_1    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tblib                     1.4.0                      py_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tiledb                    1.6.2                h4f44bfb_1    conda-forge
tk                        8.6.9             h2573ce8_1003    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h01d97ff_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
tzcode                    2019a             h01d97ff_1002    conda-forge
urllib3                   1.25.6                   py37_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
wrapt                     1.11.2           py37h01d97ff_0    conda-forge
wurlitzer                 1.0.3                    py37_0    conda-forge
xerces-c                  3.2.2             hbda6038_1004    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
zarr                      2.3.2                    py37_0    conda-forge
zeromq                    4.3.2                h6de7cb9_2    conda-forge
zict                      1.0.0                      py_0    conda-forge
zlib                      1.2.11            h01d97ff_1006    conda-forge
zstd                      1.4.0                ha9f0a20_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

    active environment : starfm
    active env location : /Users/Naresh/anaconda3/envs/starfm
            shell level : 1
       user config file : /Users/Naresh/.condarc
 populated config files : /Users/Naresh/.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : 
       base environment : /Users/Naresh/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/Naresh/anaconda3/pkgs
                          /Users/Naresh/.conda/pkgs
       envs directories : /Users/Naresh/anaconda3/envs
                          /Users/Naresh/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Darwin/18.6.0 OSX/10.14.5
                UID:GID : 501:20
             netrc file : /Users/Naresh/.netrc
           offline mode : False

```
</details>

**Comment by ocefpaf** [comment]
```
channels:
  - defaults
  - conda-forge
```

The channel order is the problem there, you need `conda-forge` on top of `defaults` for a stable experience and/or a problem that we can debug. Please see https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge for more information.
