### ISSUE TITLE
Poppler linking issue

### ISSUE THREAD

**Issue by adamjstewart** [conda-forge/gdal-feedstock#359]
Issue:

First, I install GDAL

<details>

```console
$ conda install -c conda-forge gdal
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.12
  latest version: 4.8.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/ec2-user/anaconda3/envs/pytorch_p36

  added / updated specs: 
    - gdal


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    freexl-1.0.5               |    h14c3975_1002          43 KB  conda-forge
    hdf4-4.2.13                |                0         969 KB  conda-forge
    libpq-9.6.6                |       h4e02ad2_0         101 KB
    libnetcdf-4.4.1.1          |               10         2.0 MB  conda-forge
    geos-3.6.2                 |       heeff764_2         1.6 MB
    gdal-2.2.2                 |   py36hc209d97_1         767 KB
    poppler-data-0.4.9         |                1         3.4 MB  conda-forge
    boost-cpp-1.70.0           |       ha2d47e9_0        21.0 MB  conda-forge
    xerces-c-3.2.2             |    hea5cb30_1003         1.7 MB  conda-forge
    libgdal-2.2.2              |       h804cdde_1        16.1 MB
    kealib-1.4.8               |       hfc679d8_0         173 KB  conda-forge
    json-c-0.12.1              |       h470a237_1          47 KB  conda-forge
    openssl-1.0.2t             |       h14c3975_0         3.1 MB  conda-forge
    pytables-3.4.4             |           py36_8         3.3 MB  conda-forge
    poppler-0.65.0             |       h581218d_1         1.6 MB
    proj4-4.9.3                |       h516909a_9         3.2 MB  conda-forge
    libkml-1.3.0               |    h4fcabce_1010         643 KB  conda-forge
    ca-certificates-2019.11.28 |       hecc5488_0         145 KB  conda-forge
    libspatialite-4.3.0a       |      h72746d6_18         3.1 MB
    openjpeg-2.3.1             |       h58a6597_0         470 KB  conda-forge
    libdap4-3.19.1             |       h6ec2957_0         1.5 MB
    hdf5-1.10.1                |                2         5.0 MB  conda-forge
    h5py-2.8.0                 |   py36h470a237_0         3.7 MB  conda-forge
    certifi-2019.11.28         |           py36_0         149 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        74.0 MB

The following NEW packages will be INSTALLED:

    boost-cpp:       1.70.0-ha2d47e9_0    conda-forge
    freexl:          1.0.5-h14c3975_1002  conda-forge
    gdal:            2.2.2-py36hc209d97_1            
    geos:            3.6.2-heeff764_2                
    giflib:          5.1.9-h516909a_0     conda-forge
    hdf4:            4.2.13-0             conda-forge
    json-c:          0.12.1-h470a237_1    conda-forge
    kealib:          1.4.8-hfc679d8_0     conda-forge
    libdap4:         3.19.1-h6ec2957_0               
    libgdal:         2.2.2-h804cdde_1                
    libkml:          1.3.0-h4fcabce_1010  conda-forge
    libnetcdf:       4.4.1.1-10           conda-forge
    libpq:           9.6.6-h4e02ad2_0                
    libspatialite:   4.3.0a-h72746d6_18              
    openjpeg:        2.3.1-h58a6597_0     conda-forge
    poppler:         0.65.0-h581218d_1               
    poppler-data:    0.4.9-1              conda-forge
    proj4:           4.9.3-h516909a_9     conda-forge
    xerces-c:        3.2.2-hea5cb30_1003  conda-forge

The following packages will be UPDATED:

    ca-certificates: 2019.10.16-0                     --> 2019.11.28-hecc5488_0 conda-forge
    certifi:         2019.9.11-py36_0                 --> 2019.11.28-py36_0     conda-forge
    pytables:        3.4.3-py36h02b9ad4_2             --> 3.4.4-py36_8          conda-forge

The following packages will be DOWNGRADED:

    h5py:            2.8.0-py36h989c5e5_3             --> 2.8.0-py36h470a237_0  conda-forge
    hdf5:            1.10.2-hba1933b_1                --> 1.10.1-2              conda-forge
    openssl:         1.0.2t-h7b6447c_1                --> 1.0.2t-h14c3975_0     conda-forge

Proceed ([y]/n)? y


Downloading and Extracting Packages
freexl-1.0.5         | 43 KB     | ############################################################################################################################### | 100% 
hdf4-4.2.13          | 969 KB    | ############################################################################################################################### | 100% 
libpq-9.6.6          | 101 KB    | ############################################################################################################################### | 100% 
libnetcdf-4.4.1.1    | 2.0 MB    | ############################################################################################################################### | 100% 
geos-3.6.2           | 1.6 MB    | ############################################################################################################################### | 100% 
gdal-2.2.2           | 767 KB    | ############################################################################################################################### | 100% 
poppler-data-0.4.9   | 3.4 MB    | ############################################################################################################################### | 100% 
boost-cpp-1.70.0     | 21.0 MB   | ############################################################################################################################### | 100% 
xerces-c-3.2.2       | 1.7 MB    | ############################################################################################################################### | 100% 
libgdal-2.2.2        | 16.1 MB   | ############################################################################################################################### | 100% 
kealib-1.4.8         | 173 KB    | ############################################################################################################################### | 100% 
json-c-0.12.1        | 47 KB     | ############################################################################################################################### | 100% 
openssl-1.0.2t       | 3.1 MB    | ############################################################################################################################### | 100% 
pytables-3.4.4       | 3.3 MB    | ############################################################################################################################### | 100% 
poppler-0.65.0       | 1.6 MB    | ############################################################################################################################### | 100% 
proj4-4.9.3          | 3.2 MB    | ############################################################################################################################### | 100% 
libkml-1.3.0         | 643 KB    | ############################################################################################################################### | 100% 
ca-certificates-2019 | 145 KB    | ############################################################################################################################### | 100% 
libspatialite-4.3.0a | 3.1 MB    | ############################################################################################################################### | 100% 
openjpeg-2.3.1       | 470 KB    | ############################################################################################################################### | 100% 
libdap4-3.19.1       | 1.5 MB    | ############################################################################################################################### | 100% 
hdf5-1.10.1          | 5.0 MB    | ############################################################################################################################### | 100% 
h5py-2.8.0           | 3.7 MB    | ############################################################################################################################### | 100% 
certifi-2019.11.28   | 149 KB    | ############################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
</details>

Then, I run:
```console
$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libpoppler.so.71: cannot open shared object file: No such file or directory
```
It seems like the wrong version of libpoppler is installed:
```console
$ ls anaconda3/envs/pytorch_p36/lib/libpoppler*
anaconda3/envs/pytorch_p36/lib/libpoppler-cpp.so        anaconda3/envs/pytorch_p36/lib/libpoppler-glib.so        anaconda3/envs/pytorch_p36/lib/libpoppler.so
anaconda3/envs/pytorch_p36/lib/libpoppler-cpp.so.0      anaconda3/envs/pytorch_p36/lib/libpoppler-glib.so.8      anaconda3/envs/pytorch_p36/lib/libpoppler.so.76
anaconda3/envs/pytorch_p36/lib/libpoppler-cpp.so.0.5.0  anaconda3/envs/pytorch_p36/lib/libpoppler-glib.so.8.9.0  anaconda3/envs/pytorch_p36/lib/libpoppler.so.76.0.0
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/ec2-user/anaconda3/envs/pytorch_p36:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
alabaster                 0.7.10           py36h306e16b_0  
anaconda-client           1.6.14                   py36_0  
anaconda-project          0.8.2            py36h44fb852_0  
argparse                  1.4.0                     <pip>
asn1crypto                0.24.0                   py36_0  
astroid                   1.6.3                    py36_0  
astropy                   3.0.2            py36h3010b51_1  
attrs                     18.1.0                   py36_0  
autovizwidget             0.13.1                    <pip>
babel                     2.5.3                    py36_0  
backcall                  0.1.0                    py36_0  
backports                 1.0              py36hfa02d7e_1  
backports.shutil_get_terminal_size 1.0.0            py36hfea85ff_2  
bcrypt                    3.1.7                     <pip>
beautifulsoup4            4.6.0            py36h49b8c8c_1  
bitarray                  0.8.1            py36h14c3975_1  
bkcharts                  0.2              py36h735825a_0  
blas                      1.0                         mkl  
blaze                     0.11.3           py36h4e06776_0  
bleach                    2.1.3                    py36_0  
blosc                     1.14.3               hdbcaa40_0  
bokeh                     1.0.4                    py36_0  
boost-cpp                 1.70.0               ha2d47e9_0    conda-forge
boto                      2.48.0           py36h6e4cd66_1  
boto3                     1.10.19                    py_0  
boto3                     1.10.24                   <pip>
botocore                  1.13.19                    py_0  
botocore                  1.13.24                   <pip>
bottleneck                1.2.1            py36haac1ea0_0  
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cached-property           1.5.1                     <pip>
cairo                     1.14.12              h8948797_3  
certifi                   2019.11.28               py36_0    conda-forge
cffi                      1.11.5           py36h9745a5d_0  
chardet                   3.0.4            py36h0f667ec_1  
click                     6.7              py36h5253387_0  
cloudpickle               0.5.3                    py36_0  
clyent                    1.2.2            py36h7e57e65_1  
colorama                  0.3.9            py36h489cec4_0  
contextlib2               0.5.5            py36h6c84a62_0  
cryptography              2.2.2            py36h14c3975_0  
cryptography              2.8                       <pip>
cudatoolkit               10.1.243             h6bb024c_0  
curl                      7.60.0               h84994c4_0  
cycler                    0.10.0           py36h93f1223_0  
cymem                     2.0.2            py36he1b5a44_0    fastai
cython                    0.28.2           py36h14c3975_0  
cython-blis               0.2.4            py36h516909a_1    fastai
cytoolz                   0.9.0.1          py36h14c3975_0  
dask                      0.17.5                   py36_0  
dask-core                 0.17.5                   py36_0  
dataclasses               0.6                        py_0    fastai
datashape                 0.5.4            py36h3ad6b5c_0  
dbus                      1.13.2               h714fa37_1  
decorator                 4.3.0                    py36_0  
defusedxml                0.6.0                      py_0  
distributed               1.21.8                   py36_0  
docker                    4.1.0                     <pip>
docker-compose            1.25.0                    <pip>
dockerpty                 0.4.1                     <pip>
docopt                    0.6.2                     <pip>
docutils                  0.14             py36hb0f60f5_0  
entrypoints               0.2.3            py36h1aec115_2  
environment-kernels       1.1.1                     <pip>
et_xmlfile                1.0.1            py36hd6bccc3_0  
expat                     2.2.5                he0dffb1_0  
fastai                    1.0.59                        1    fastai
fastcache                 1.0.2            py36h14c3975_2  
fastprogress              0.1.22                     py_0    fastai
filelock                  3.0.4                    py36_0  
flask                     1.0.2                    py36_1  
flask-cors                3.0.4                    py36_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_1  
freexl                    1.0.5             h14c3975_1002    conda-forge
fribidi                   1.0.5                h7b6447c_0  
gdal                      2.2.2            py36hc209d97_1  
geos                      3.6.2                heeff764_2  
get_terminal_size         1.0.0                haa9412d_0  
gevent                    1.3.0            py36h14c3975_0  
giflib                    5.1.9                h516909a_0    conda-forge
glib                      2.56.1               h000015b_0  
glob2                     0.6              py36he249c77_0  
gmp                       6.1.2                h6c8ec71_1  
gmpy2                     2.0.8            py36hc8893dd_2  
graphite2                 1.3.11               h16798f4_2  
graphviz                  2.40.1               h21bd128_2  
greenlet                  0.4.13           py36h14c3975_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.8.0            py36h470a237_0    conda-forge
harfbuzz                  1.8.8                hffaf4a1_0  
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1                        2    conda-forge
hdijupyterutils           0.13.1                    <pip>
heapdict                  1.0.0                    py36_2  
html5lib                  1.0.1            py36h2f9c1c0_0  
icu                       58.2                 h9c2bf20_1  
idna                      2.6              py36h82fb2a8_1  
imageio                   2.3.0                    py36_0  
imagesize                 1.0.0                    py36_0  
intel-openmp              2018.0.0                      8  
ipykernel                 4.8.2                    py36_0  
ipyparallel               6.2.2                     <pip>
ipython                   6.4.0                    py36_0  
ipython_genutils          0.2.0            py36hb52b0d5_0  
ipywidgets                7.4.0                     <pip>
ipywidgets                7.2.1                    py36_0  
isort                     4.3.4                    py36_0  
itsdangerous              0.24             py36h93cc618_1  
jbig                      2.1                  hdba287a_0  
jdcal                     1.4                      py36_0  
jedi                      0.12.0                   py36_1  
jinja2                    2.10             py36ha16c418_0  
jmespath                  0.9.4                      py_0  
jpeg                      9b                   h024ee3a_2  
json-c                    0.12.1               h470a237_1    conda-forge
jsonschema                2.6.0            py36h006f8b5_0  
jupyter                   1.0.0                    py36_4  
jupyter_client            5.2.3                    py36_0  
jupyter_console           5.2.0            py36he59e554_1  
jupyter_core              4.4.0            py36h7c827e3_0  
jupyterlab                0.32.1                   py36_0  
jupyterlab_launcher       0.10.5                   py36_0  
kealib                    1.4.8                hfc679d8_0    conda-forge
kiwisolver                1.0.1            py36h764f252_0  
krb5                      1.14.2               hcdc1b81_6  
lazy-object-proxy         1.3.1            py36h10fcdad_0  
libcurl                   7.60.0               h1ad7b7a_0  
libdap4                   3.19.1               h6ec2957_0  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgdal                   2.2.2                h804cdde_1  
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3  
libkml                    1.3.0             h4fcabce_1010    conda-forge
libnetcdf                 4.4.1.1                      10    conda-forge
libpng                    1.6.37               hbc83047_0  
libpq                     9.6.6                h4e02ad2_0  
libprotobuf               3.5.2                hd28b015_1    conda-forge
libsodium                 1.0.16               h1bed415_0  
libspatialite             4.3.0a              h72746d6_18  
libssh2                   1.8.0                h9cfc8f7_4  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.9                he85c1e1_1  
libtool                   2.4.6                h544aabb_3  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.8                h26e45fe_1  
libxslt                   1.1.32               h1312cb7_0  
llvmlite                  0.23.1           py36hdbcaa40_0  
locket                    0.2.0            py36h787c0ad_1  
lxml                      4.2.1            py36h23eabaa_0  
lzo                       2.10                 h49e0be7_2  
markupsafe                1.0              py36hd9260cd_1  
matplotlib                3.0.3            py36h5429711_0  
matplotlib                2.2.2                     <pip>
mccabe                    0.6.1            py36h5ad9710_1  
mistune                   0.8.3            py36h14c3975_1  
mkl                       2018.0.3                      1  
mkl-service               1.1.2            py36h17a0993_4  
mkl_fft                   1.0.6            py36h7dd41cf_0  
mkl_random                1.0.1            py36h629b387_0  
mock                      3.0.5                     <pip>
more-itertools            4.1.0                    py36_0  
mpc                       1.0.3                hec55b23_5  
mpfr                      3.1.5                h11a74b3_2  
mpi                       1.0                     openmpi    conda-forge
mpmath                    1.0.0            py36hfeacd6b_2  
msgpack                   0.6.0                     <pip>
msgpack-python            0.5.6            py36h6bb024c_0  
multipledispatch          0.5.0                    py36_0  
murmurhash                1.0.2            py36he6710b0_0  
nb_conda                  2.2.1                    py36_2    conda-forge
nb_conda_kernels          2.2.2                    py36_0    conda-forge
nbconvert                 5.4.1                    py36_3  
nbformat                  4.4.0            py36h31c9010_0  
ncurses                   6.1                  hf484d3e_0  
networkx                  2.1                      py36_0  
ninja                     1.9.0            py36hfd86e86_0  
nltk                      3.3.0                    py36_0  
nose                      1.3.7            py36hcdf7029_2  
notebook                  5.5.0                    py36_0  
numba                     0.38.0           py36h637b7d7_0  
numexpr                   2.6.5            py36h7bf3b9c_0  
numpy                     1.15.4           py36h1d66e8a_0  
numpy-base                1.15.4           py36h81de0dd_0  
numpydoc                  0.8.0                    py36_0  
nvidia-ml-py3             7.352.0                    py_0    fastai
odo                       0.5.1            py36h90ed295_0  
olefile                   0.45.1                   py36_0  
onnx                      1.5.0                     <pip>
openjpeg                  2.3.1                h58a6597_0    conda-forge
openmpi                   3.1.0                h26a2512_3    conda-forge
openpyxl                  2.5.3                    py36_0  
openssl                   1.0.2t               h14c3975_0    conda-forge
packaging                 17.1                     py36_0  
pandas                    0.24.2           py36he6710b0_0  
pandoc                    1.19.2.1             hea2e7c5_1  
pandocfilters             1.4.2            py36ha6701b7_1  
pango                     1.42.3               h8589676_0  
paramiko                  2.6.0                     <pip>
parso                     0.2.0                    py36_0  
partd                     0.3.8            py36h36fd896_0  
patchelf                  0.9                  hf79760b_2  
path.py                   11.0.1                   py36_0  
pathlib2                  2.3.2                    py36_0  
patsy                     0.5.0                    py36_0  
pcre                      8.42                 h439df22_0  
pep8                      1.7.1                    py36_0  
pexpect                   4.5.0                    py36_0  
pickleshare               0.7.4            py36h63277f8_0  
pillow                    5.2.0            py36heded4f4_0  
pip                       10.0.1                   py36_0  
pixman                    0.34.0               hceecf20_3  
pkginfo                   1.4.2                    py36_1  
plac                      0.9.6                    py36_0  
plotly                    4.3.0                     <pip>
pluggy                    0.6.0            py36hb689045_0  
ply                       3.11                     py36_0  
poppler                   0.65.0               h581218d_1  
poppler-data              0.4.9                         1    conda-forge
preshed                   2.0.1            py36he6710b0_0  
proj4                     4.9.3                h516909a_9    conda-forge
prompt_toolkit            1.0.15           py36h17d85b1_0  
protobuf                  3.5.2            py36hd28b015_0    conda-forge
protobuf3-to-dict         0.1.5                     <pip>
psutil                    5.4.5            py36h14c3975_0  
psycopg2                  2.7.5                     <pip>
ptyprocess                0.5.2            py36h69acd42_0  
py                        1.5.3                    py36_0  
py4j                      0.10.7                    <pip>
pycodestyle               2.4.0                    py36_0  
pycosat                   0.6.3            py36h0a5515d_0  
pycparser                 2.18             py36hf9f622e_1  
pycrypto                  2.6.1            py36h14c3975_8  
pycurl                    7.43.0.1         py36hb7f436b_0  
pyflakes                  1.6.0            py36h7bd6a15_0  
pygal                     2.4.0                     <pip>
pygments                  2.2.0            py36h0d3125c_0  
pykerberos                1.2.1            py36h14c3975_0  
pylint                    1.8.4                    py36_0  
PyNaCl                    1.3.0                     <pip>
pyodbc                    4.0.23           py36hf484d3e_0  
pyopenssl                 18.0.0                   py36_0  
pyparsing                 2.2.0            py36hee85983_1  
pyqt                      5.9.2            py36h751905a_0  
pysocks                   1.6.8                    py36_0  
pyspark                   2.3.2                     <pip>
pytables                  3.4.4                    py36_8    conda-forge
pytest                    3.5.1                    py36_0  
pytest-arraydiff          0.2                      py36_0  
pytest-astropy            0.3.0                    py36_0  
pytest-doctestplus        0.1.3                    py36_0  
pytest-openfiles          0.3.0                    py36_0  
pytest-remotedata         0.2.1                    py36_0  
python                    3.6.5                hc3d631a_2  
python-dateutil           2.7.3                    py36_0  
pytorch                   1.3.1           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
pytz                      2018.4                   py36_0  
pywavelets                0.5.2            py36he602eb0_0  
pyyaml                    3.12             py36hafb9ca4_1  
pyzmq                     17.0.0           py36h14c3975_0  
qt                        5.9.6                h52aff34_0  
qtawesome                 0.4.4            py36h609ed8c_0  
qtconsole                 4.3.1            py36h8f73b5b_0  
qtpy                      1.4.1                    py36_0  
readline                  7.0                  ha6073c6_4  
requests                  2.20.0                py36_1000    conda-forge
requests-kerberos         0.12.0                    <pip>
retrying                  1.3.3                     <pip>
rope                      0.10.7           py36h147e2ec_0  
ruamel_yaml               0.15.35          py36h14c3975_1  
s3fs                      0.1.5                    py36_0  
s3transfer                0.2.1                    py36_0  
sagemaker                 1.44.0                    <pip>
sagemaker-pyspark         1.2.6                     <pip>
scikit-image              0.13.1           py36h14c3975_1  
scikit-learn              0.19.1           py36h7aa7ec6_0  
scikit-learn              0.20.3                    <pip>
scipy                     1.1.0            py36hfc37229_0  
seaborn                   0.8.1            py36hfad7ec4_0  
send2trash                1.5.0                    py36_0  
setuptools                39.1.0                   py36_0  
simplegeneric             0.8.1                    py36_2  
singledispatch            3.4.0.3          py36h7a266c3_0  
sip                       4.19.8           py36hf484d3e_0  
six                       1.11.0           py36h372c433_1  
snappy                    1.1.7                hbae5bb6_3  
snowballstemmer           1.2.1            py36h6febd40_0  
sortedcollections         0.6.1                    py36_0  
sortedcontainers          1.5.10                   py36_0  
spacy                     2.1.8            py36hc9558a2_0    fastai
sparkmagic                0.12.5                    <pip>
sphinx                    1.7.4                    py36_0  
sphinxcontrib             1.0              py36h6d0f590_1  
sphinxcontrib-websupport  1.0.1            py36hb5cb234_1  
spyder                    3.2.8                    py36_0  
SQLAlchemy                1.2.11                    <pip>
sqlalchemy                1.2.7            py36h6b74fdf_0  
sqlite                    3.23.1               he433501_0  
srsly                     0.1.0            py36he1b5a44_0    fastai
statsmodels               0.9.0            py36h3010b51_0  
sympy                     1.1.1            py36hc6d1c1c_0  
tbb                       2018.0.4             h6bb024c_1  
tbb4py                    2018.0.4         py36h6bb024c_1  
tblib                     1.3.2            py36h34cf8b6_0  
terminado                 0.8.1                    py36_1  
testpath                  0.3.1            py36h8cadb63_0  
texttable                 1.6.2                     <pip>
thinc                     7.0.8            py36hc9558a2_0    fastai
tk                        8.6.8                hbc83047_0  
toolz                     0.9.0                    py36_0  
torchvision               0.4.2                py36_cu101    pytorch
tornado                   5.0.2                    py36_0  
tqdm                      4.38.0                     py_0  
traitlets                 4.3.2            py36h674d592_0  
typing                    3.6.4                    py36_0  
typing-extensions         3.7.4.1                   <pip>
unicodecsv                0.14.1           py36ha668878_0  
unixodbc                  2.3.6                h1bed415_0  
urllib3                   1.23                     py36_0  
wasabi                    0.2.2                      py_0    fastai
wcwidth                   0.1.7            py36hdf4376a_0  
webencodings              0.5.1            py36h800622e_1  
websocket-client          0.56.0                    <pip>
werkzeug                  0.14.1                   py36_0  
wheel                     0.31.1                   py36_0  
widgetsnbextension        3.4.2                     <pip>
widgetsnbextension        3.2.1                    py36_0  
wrapt                     1.10.11          py36h28b7045_0  
xerces-c                  3.2.2             hea5cb30_1003    conda-forge
xlrd                      1.1.0            py36h1db9f0c_1  
xlsxwriter                1.0.4                    py36_0  
xlwt                      1.3.0            py36h7b00a1f_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zeromq                    4.2.5                h439df22_0  
zict                      0.1.3            py36h3a3bf81_0  
zlib                      1.2.11               ha838bed_2  
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : pytorch_p36
    active env location : /home/ec2-user/anaconda3/envs/pytorch_p36
            shell level : 1
       user config file : /home/ec2-user/.condarc
 populated config files : /home/ec2-user/.condarc
          conda version : 4.5.12
    conda-build version : 3.10.5
         python version : 3.6.6.final.0
       base environment : /home/ec2-user/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/ec2-user/anaconda3/pkgs
       envs directories : /home/ec2-user/anaconda3/envs
                          /home/ec2-user/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.20.0 CPython/3.6.6 Linux/4.14.154-128.181.amzn2.x86_64 amzn/2 glibc/2.26
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by kmuehlbauer** [comment]
@adamjstewart Your gdal isn't from conda-forge channel. You would need to report somewhere else.

**Comment by adamjstewart** [comment]
```console
$ conda install -c conda-forge gdal
```
doesn't install GDAL from the conda-forge channel? What does?

**Comment by kmuehlbauer** [comment]
This depends on your conda configuration. What's is inside your .condarc?

**Comment by adamjstewart** [comment]
```console
$ cat .condarc 
pkgs_dirs:
  - ~/anaconda3/pkgs
auto_update_conda: false
```
This is the default that comes with the deep learning AMIs on AWS.

**Comment by kmuehlbauer** [comment]
OK, found it in your output of conda info. Seems that your env depends on multiple channels. AFAIK this can be a problem for the dependency solver. There is the 'strict_channel' feature which should take care that a package isn't pulled from another channel.

**Comment by kmuehlbauer** [comment]
Try this:
conda config --set channel_priority strict

**Comment by adamjstewart** [comment]
Thanks @kmuehlbauer, I found a good explanation of the problem at https://conda-forge.org/docs/user/tipsandtricks.html.

Unfortunately, this feature was added in Conda 4.6, and AWS uses Conda 4.5. I'll try upgrading, hopefully it won't break too many things...

**Comment by adamjstewart** [comment]
Hmm, update went fine, but the solver failed with hundreds of incompatible packages...

**Comment by kmuehlbauer** [comment]
@adamjstewart You can try to create a new environment and add your wanted packages.

**Comment by adamjstewart** [comment]
@kmuehlbauer unfortunately I also need the deep learning libraries that come with the PyTorch environment I'm already in. I may just give up on Conda and switch to [Spack](https://spack.io) instead. Building from source is slow, but it's better than not being able to solve the environment at all. I think [Spack's GDAL recipe](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/gdal/package.py) is more robust anyway. Thanks for your help!

**Comment by kmuehlbauer** [comment]
@adamjstewart Good luck! But as last resort, @ocefpaf do you have a recommendation?

**Comment by ocefpaf** [comment]
> @kmuehlbauer unfortunately I also need the deep learning libraries that come with the PyTorch environment I'm already in. I may just give up on Conda and switch to [Spack](https://spack.io) instead. Building from source is slow, but it's better than not being able to solve the environment at all. I think [Spack's GDAL recipe](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/gdal/package.py) [](/spack/spack/blob/HEAD@{2019-12-15T19:16:24Z}/var/spack/repos/builtin/packages/gdal/package.py) is more robust anyway. Thanks for your help!
 
Unless conda-forge have those libraries, and with the modern compiler, I don't think it will be possible to just updated/add packages to that env. Unfortunately, we are lacking on pytorch and "friends." There are some people working on them, stay tuned.
