### ISSUE TITLE
libjpeg dependency on OS X

### ISSUE THREAD

**Issue by snorfalorpagus** [conda-forge/gdal-feedstock#36]
When installing fiona in a fresh environment on OS X libjpeg 8d-1 is pulled down as a dependency by GDAL. But when the module is imported an `ImportError` is raised. It looks like GDAL was linked against libjpeg 9. Manually upgrading to version 9 seems to resolve the issue. I'm not sure why 8 gets installed in the first place.

```
snorfmac:~ snorf$ conda create -n python34 python=3.4
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: .........
Package plan for installation in environment /Users/snorf/miniconda3/envs/python34:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2g-0     
    pip:        8.1.1-py34_1 
    python:     3.4.4-0      
    readline:   6.2-2        
    setuptools: 20.7.0-py34_0
    sqlite:     3.9.2-0      
    tk:         8.5.18-0     
    wheel:      0.29.0-py34_0
    xz:         5.0.5-1      
    zlib:       1.2.8-0      

Proceed ([y]/n)? 

Linking packages ...
[      COMPLETE      ]|###################################################| 100%
#
# To activate this environment, use:
# $ source activate python34
#
# To deactivate this environment, use:
# $ source deactivate
#
snorfmac:~ snorf$ source activate python34
discarding /Users/snorf/miniconda3/bin from PATH
prepending /Users/snorf/miniconda3/envs/python34/bin to PATH
(python34)snorfmac:~ snorf$ conda install fiona
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: ....................
Package plan for installation in environment /Users/snorf/miniconda3/envs/python34:

The following NEW packages will be INSTALLED:

    click:         6.6-py34_0        
    click-plugins: 1.0.3-py34_0      
    cligj:         0.4.0-py34_0      
    curl:          7.45.0-0          
    expat:         2.1.0-0           
    fiona:         1.6.3-np111py34_3 
    freexl:        1.0.2-0           
    gdal:          1.11.4-np111py34_4
    geos:          3.4.2-1           
    giflib:        5.1.2-0           
    hdf4:          4.2.11-0          
    hdf5:          1.8.15.1-2        
    jasper:        1.900.1-1         
    jbig:          2.1-0             
    jpeg:          8d-1              
    json-c:        0.12-0            
    krb5:          1.13.2-0          
    libgcc:        4.8.5-1           
    libnetcdf:     4.3.3.1-3         
    libpng:        1.6.17-0          
    libtiff:       4.0.6-1           
    mkl:           11.3.1-0          
    munch:         2.0.4-py34_0      
    numpy:         1.11.0-py34_0     
    openjpeg:      2.1.0-1           
    proj.4:        4.9.1-2           
    six:           1.10.0-py34_0     
    xerces-c:      3.1.2-0           

Proceed ([y]/n)? 

Linking packages ...
[      COMPLETE      ]|###################################################| 100%
(python34)snorfmac:~ snorf$ python
Python 3.4.4 |Continuum Analytics, Inc.| (default, Jan  9 2016, 17:30:09) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/snorf/miniconda3/envs/python34/lib/python3.4/site-packages/fiona/__init__.py", line 72, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/Users/snorf/miniconda3/envs/python34/lib/python3.4/site-packages/fiona/collection.py", line 7, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/snorf/miniconda3/envs/python34/lib/python3.4/site-packages/fiona/ogrext.so, 2): Library not loaded: @rpath/libjpeg.9.dylib
  Referenced from: /Users/snorf/miniconda3/envs/python34/lib//libjasper.1.dylib
  Reason: image not found
```
Update libjpeg:
```
(python34)snorfmac:~ snorf$ conda install jpeg
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: ......
Package plan for installation in environment /Users/snorf/miniconda3/envs/python34:

The following packages will be UPDATED:

    jpeg: 8d-1 --> 9b-0

Proceed ([y]/n)? 

Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
(python34)snorfmac:~ snorf$ python
Python 3.4.4 |Continuum Analytics, Inc.| (default, Jan  9 2016, 17:30:09) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiona
>>> fiona.__version__
'1.6.3.post1'
```

**Comment by ocefpaf** [comment]
@snorfalorpagus  we just updated our `jpeg` package. I will trigger the rebuilds to get rid of the issue. Hold on...

**Comment by pelson** [comment]
Another situation where https://github.com/conda/conda-build/pull/747 would hugely help.
