### ISSUE TITLE
Mutating some internal state of HTTP?

### ISSUE THREAD

**Issue by four43** [conda-forge/gdal-feedstock#365]
**GDAL report, they tossed it up to you guys: https://github.com/OSGeo/gdal/issues/2189**

Issue: Changing the import order of the `osgeo` library to before `requests` breaks functionality. There is some internal modification being done from the `osgeo` library to some HTTP stack that is breaking `requests`

Conda Specific reproduction steps:
```bash
$ conda --version
conda 4.8.1
$ conda create --name "gdal-issue-repro"
$ conda activate gdal-issue-repro
$ conda install -c conda-forge gdal>3
$ pip install requests
```
**test.py**
```python
from osgeo import gdal
import requests

print(f"ogr version: {gdal.__version__}, requests version: {requests.__version__}")
requests.get('https://www.weather.gov/gis/Counties')
print("Success!")
```
Running that produces:
```
python ./test.py
ogr version: 3.0.3, requests version: 2.22.0
Traceback (most recent call last):
  File "/opt/miniconda3/envs/gdal-issue-repro/lib/python3.8/site-packages/urllib3/response.py", line 388, in _decode
    data = self._decoder.decompress(data)
  File "/opt/miniconda3/envs/gdal-issue-repro/lib/python3.8/site-packages/urllib3/response.py", line 85, in decompress
    ret += self._obj.decompress(data)
zlib.error: Error -2 while decompressing data: inconsistent stream state

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/gdal-issue-repro/lib/python3.8/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/opt/miniconda3/envs/gdal-issue-repro/lib/python3.8/site-packages/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/opt/miniconda3/envs/gdal-issue-repro/lib/python3.8/site-packages/urllib3/response.py", line 536, in read
    data = self._decode(data, decode_content, flush_decoder)
  File "/opt/miniconda3/envs/gdal-issue-repro/lib/python3.8/site-packages/urllib3/response.py", line 391, in _decode
    raise DecodeError(
urllib3.exceptions.DecodeError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -2 while decompressing data: inconsistent stream state'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test.py", line 5, in <module>
    requests.get('https://www.weather.gov/gis/Counties')
  File "/opt/miniconda3/envs/gdal-issue-repro/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/miniconda3/envs/gdal-issue-repro/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/miniconda3/envs/gdal-issue-repro/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/miniconda3/envs/gdal-issue-repro/lib/python3.8/site-packages/requests/sessions.py", line 686, in send
    r.content
  File "/opt/miniconda3/envs/gdal-issue-repro/lib/python3.8/site-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/opt/miniconda3/envs/gdal-issue-repro/lib/python3.8/site-packages/requests/models.py", line 755, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -2 while decompressing data: inconsistent stream state'))
```

But flipping around the import order:

**test-working.py**
```python
import requests
from osgeo import gdal

print(f"ogr version: {gdal.__version__}, requests version: {requests.__version__}")
requests.get('https://www.weather.gov/gis/Counties')
print("Success!")
```
```bash
$ python ./test-working.py
ogr version: 3.0.3, requests version: 2.22.0
Success!
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /opt/miniconda3/envs/gdal-issue-repro:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
certifi                   2019.11.28               py38_0    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
chardet                   3.0.4                    pypi_0    pypi
curl                      7.65.3               hf8cf82a_0    conda-forge
expat                     2.2.5             he1b5a44_1004    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
gdal                      3.0.3            py38hbb6b9fb_0    conda-forge
geos                      3.8.0                he1b5a44_0    conda-forge
geotiff                   1.5.1                h38872f0_8    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.2.1                h516909a_1    conda-forge
glib                      2.58.3          py38h6f030ca_1002    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                      pypi_0    pypi
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
kealib                    1.4.10            h58c409b_1005    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdap4                   3.20.4               hd3bb157_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgdal                   3.0.3                h20022a4_0    conda-forge
libgfortran-ng            7.3.0                hdf63c60_4    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libnetcdf                 4.7.3           nompi_h9f9fd6a_101    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     12.1                 hd9ab2ff_0    conda-forge
libspatialite             4.3.0a            ha48a99a_1034    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                h56121f0_5    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.17.5           py38h95a1406_0    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pip                       20.0.1                   py38_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
poppler                   0.67.0               h14e79db_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.1                 hc63931a_0    conda-forge
proj                      6.3.0                hc80f0dc_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
python                    3.8.1                h357f687_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   pypi_0    pypi
setuptools                45.1.0                   py38_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tiledb                    1.7.0                hcde45ca_2    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
urllib3                   1.25.8                   pypi_0    pypi
wheel                     0.33.6                   py38_0    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : gdal-issue-repro
    active env location : /opt/miniconda3/envs/gdal-issue-repro
            shell level : 2
       user config file : /home/seth/.condarc
 populated config files : /home/seth/.condarc
          conda version : 4.8.1
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __cuda=9.1
                          __glibc=2.27
       base environment : /opt/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /home/seth/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /home/seth/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.1 requests/2.21.0 CPython/3.7.6 Linux/4.15.0-74-generic ubuntu/18.04.3 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by ocefpaf** [comment]
Trying to reproduce this with conda-forge's `requests` gave me a segfault :-(

Investigating...

**Comment by gvellut** [comment]
I arrived here looking for some help on the "zlib.error: Error -2 while decompressing data: inconsistent stream state" error message. I also encountered the same issue using gdal from Conda, but it doesn't involve requests : I use openpyxl to read an xlsx file (which is just a zip) and the call to zlib inside the library produces the same error message, but only if I load gdal first as with @four43's issue.

My version of conda is 4.8.2 on Linux (I also tested on macOS with conda 4.6.13 but I could not get the same error).

Here is how I created a minimal env to reproduce :

```
conda env create -n bugreport python=3.7.3
conda activate bugreport
conda install -c conda-forge gdal=2.4.1 openpyxl=2.6.3
```

**test.py** : 

```python
import gdal
import openpyxl
openpyxl.load_workbook("db.xlsx", read_only=True)
```

(the db.xlsx can be an empty one created with Excel or LibreOffice)

Here is the error :
```
# python test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    openpyxl.load_workbook("db.xlsx", read_only=True)
  File "/opt/conda/envs/bugreport/lib/python3.7/site-packages/openpyxl/reader/excel.py", line 319, in load_workbook
    reader.read()
  File "/opt/conda/envs/bugreport/lib/python3.7/site-packages/openpyxl/reader/excel.py", line 275, in read
    self.read_manifest()
  File "/opt/conda/envs/bugreport/lib/python3.7/site-packages/openpyxl/reader/excel.py", line 136, in read_manifest
    src = self.archive.read(ARC_CONTENT_TYPES)
  File "/opt/conda/envs/bugreport/lib/python3.7/zipfile.py", line 1429, in read
    return fp.read()
  File "/opt/conda/envs/bugreport/lib/python3.7/zipfile.py", line 885, in read
    buf += self._read1(self.MAX_N)
  File "/opt/conda/envs/bugreport/lib/python3.7/zipfile.py", line 975, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -2 while decompressing data: inconsistent stream state
```

Removing the import gdal or putting it after the `import openpyxl` works correctly.

**Comment by AdrianoKF** [comment]
While I'm not using the conda GDAL build, I was experiencing a similar issue yesterday, when trying to fetch and decompress a ZIP archive while having the GDAL module imported: https://stackoverflow.com/questions/63161532/python-segmentation-fault-when-using-zipfile-while-gdal-package-loaded

Maybe this points to some actual problem in downstream GDAL, where the issue was originally reported (https://github.com/OSGeo/gdal/issues/2189).

Were you able to find any solution?

**Comment by ocefpaf** [comment]
I'm not 100% sure the problem is upstream but I'm also unclear on how to fix this :-/

**Comment by four43** [comment]
@ocefpaf we feel for you and wish you luck! ha ha

**Comment by kmuehlbauer** [comment]
Can't reproduce this with Python=3.10. Did this issue resolve over time?

**Comment by ocefpaf** [comment]
Let's close and re-open a new one if the problem persists. We had a few new gdal versions since this was open.
