### ISSUE TITLE
Mac feedstock file encoding issue

### ISSUE THREAD

**Issue by hobu** [conda-forge/gdal-feedstock#422]
When I try to build the gdal-feedstock on my mac, I get the following

```
fatal: iconv_open(UTF-8,UTF-8-MAC) failed, but needed:
    precomposed unicode is not supported.
    If you want to use decomposed unicode, run
    "git config core.precomposeunicode false"

v3.1.0RC1-1455-ge00491a02c

Traceback (most recent call last):
  File "/Users/hobu/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda_build/source.py", line 364, in git_info
    stdout = check_output_env(cmd, stderr=stderr, cwd=src_dir, env=env)
  File "/Users/hobu/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda_build/utils.py", line 415, in check_output_env
    *popenargs, **kwargs).rstrip()
  File "/Users/hobu/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda_build/utils.py", line 405, in _func_defaulting_env_to_os_environ
    out = subprocess.check_output(_args, **kwargs)
  File "/Users/hobu/miniconda3/envs/conda-build/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/Users/hobu/miniconda3/envs/conda-build/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/Users/hobu/miniconda3/envs/conda-build/bin/git', 'status']' returned non-zero exit status 128.
```

I'm not sure what file has the bad character in its filename or content.

**Comment by ocefpaf** [comment]
No idea, sorry. I'm not a mac person and I don't have one to test.

It is odd though that the failure is coming from git, did you modify the recipe to pull the RC from a `git_url`? If so that could be even a conda-build bug. Can you try to use GitHub's archive scheme to get a tarball for that commit instead?

**Comment by hobu** [comment]
> did you modify the recipe to pull the RC from a git_url? 

Yep, trying to do for GDAL what I did for PROJ https://github.com/conda-forge/proj.4-feedstock/pull/98

**Comment by gillins** [comment]
Hmm looks like a problem with `git`... Can you do a `git clone` with `conda` `git`?

**Comment by hobu** [comment]
It was indeed OSX's git. Some googling showed this is a longstanding issue. I don't have a resolution for it, but it isn't the feedstock's problem.
