### ISSUE TITLE
`from osgeo import gdal` and running `gdalinfo` fails on windows after gdal install

### ISSUE THREAD

**Issue by realuser** [conda-forge/gdal-feedstock#644]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I installed gdal via `conda install gdal`

When I run `from osgeo import gdal` I get the following error:

```
Python 3.10.4 | packaged by conda-forge | (main, Mar 30 2022, 08:38:02) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal
Traceback (most recent call last):
  File "C:\myenv\lib\site-packages\osgeo\__init__.py", line 29, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\myenv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\myenv\lib\site-packages\osgeo\__init__.py", line 45, in <module>
    _gdal = swig_import_helper()
  File "C:\myenv\lib\site-packages\osgeo\__init__.py", line 41, in swig_import_helper
    raise ImportError(traceback_string + '\n' + msg)
ImportError: Traceback (most recent call last):
  File "C:\myenv\lib\site-packages\osgeo\__init__.py", line 29, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\myenv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: The specified module could not be found.

On Windows, with Python >= 3.8, DLLs are no longer imported from the PATH.
If gdalXXX.dll is in the PATH, then set the USE_PATH_FOR_GDAL_PYTHON=YES environment variable
to feed the PATH into os.add_dll_directory().

```

Also when I run `gdalinfo` from the command line I get the following error:
> The code execution cannot proceed because gssapi64.dll was not found. Reinstalling the program may fix this problem.

![image](https://user-images.githubusercontent.com/7472570/185263371-9aa448c3-e5dc-4fd7-8065-673ffc83ba00.png)

### Installed packages

```shell
(myenv) C:\>conda list
# packages in environment at C:\myenv:
#
# Name                    Version                   Build  Channel
asgiref                   3.5.2                    pypi_0    pypi
blas                      1.0                         mkl
bzip2                     1.0.8                he774522_0
ca-certificates           2022.07.19           haa95532_0
certifi                   2022.6.15       py310haa95532_0
cfitsio                   3.470                h2bbff1b_7
curl                      7.84.0               h2bbff1b_0
django                    4.1                      pypi_0    pypi
django-countries          7.3.2                    pypi_0    pypi
django-debug-toolbar      3.6.0                    pypi_0    pypi
django-extensions         3.2.0                    pypi_0    pypi
expat                     2.4.4                h6c2663c_0
freexl                    1.0.6                h2bbff1b_0
gdal                      3.4.1           py310h0fae465_0
geos                      3.8.0                h33f27b4_0
geotiff                   1.7.0                h4545760_0
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.6               h1756f20_1
icc_rt                    2019.0.0             h0cc432a_1
intel-openmp              2021.4.0          haa95532_3556
jpeg                      9e                   h2bbff1b_0
kealib                    1.4.14               hde4a422_1
lerc                      3.0                  hd77b12b_0
libcurl                   7.84.0               h86230a5_0
libdeflate                1.8                  h2bbff1b_5
libffi                    3.4.2                hd77b12b_4
libgdal                   3.4.1                h9b24a9a_2
libiconv                  1.16                 h2bbff1b_2
libnetcdf                 4.8.1                h6685c40_1
libpng                    1.6.37               h2a8f88b_0
libpq                     12.9                 hb652d5d_3
libspatialite             4.3.0a              h14feca5_20
libssh2                   1.10.0               hcd4344a_0
libtiff                   4.4.0                h8a3f274_0
libxml2                   2.9.14               h0ad7f3c_0
libzip                    1.8.0                h49b8836_0
lz4-c                     1.9.3                h2bbff1b_1
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0           py310h2bbff1b_0
mkl_fft                   1.3.1           py310ha0764ea_0
mkl_random                1.2.2           py310h4ed8f06_0
msys2-conda-epoch         20160418                      1
numpy                     1.23.1          py310h6d2d95c_0
numpy-base                1.23.1          py310h206c741_0
openjpeg                  2.4.0                h4fc8c34_0
openssl                   1.1.1q               h2bbff1b_0
pip                       22.1.2          py310haa95532_0
proj                      6.2.1                h3758d61_0
psycopg2                  2.9.3                    pypi_0    pypi
python                    3.10.4               hbb2ffb3_0
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2022.2.1                 pypi_0    pypi
setuptools                61.2.0          py310haa95532_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.39.2               h2bbff1b_0
sqlparse                  0.4.2                    pypi_0    pypi
tiledb                    2.3.3                h3649cd2_2
tk                        8.6.12               h2bbff1b_0
typing-extensions         4.3.0                    pypi_0    pypi
tzdata                    2022.2                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2             py310haa95532_2
xerces-c                  3.2.3                ha925a31_0
xz                        5.2.5                h8cc25b3_1
zlib                      1.2.12               h8cc25b3_2
zstd                      1.5.2                h19a0ad4_0
```

### Environment info

```shell
(myenv) C:\>conda info

     active environment : myenv
    active env location : C:\myenv
            shell level : 1
       user config file : C:\Users\username\.condarc
 populated config files : C:\Users\username\.condarc
          conda version : 4.12.0
    conda-build version : 3.21.8
         python version : 3.9.12.final.0
       virtual packages : __cuda=11.6=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\anaconda3  (writable)
      conda av data dir : C:\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\anaconda3\pkgs
                          C:\Users\username\.conda\pkgs
                          C:\Users\username\AppData\Local\conda\conda\pkgs
       envs directories : C:\envs
                          C:\anaconda3\envs
                          C:\Users\username\.conda\envs
                          C:\Users\username\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Windows/10 Windows/10.0.19044
          administrator : True
             netrc file : None
           offline mode : False
```

**Comment by gillins** [comment]
Hi @realuser, seems that none of your packages come from conda-forge (the "Channel" column is either empty or `pypi`). Can you try creating a new environment like this and see what happens:
```
conda create -n myenv2 gdal
conda activate myenv2
```
Might also be worth setting channel priority like this (if you haven't already):
```
conda config --set channel_priority strict
```

**Comment by realuser** [comment]
I did this and the result is the same however the channel column appears to still be empty.  I did run `conda config --set channel_priority strict` first

**Comment by gillins** [comment]
> Should I switch the order of those?

Yes your .condarc should look like this:
```
channels:
  - conda-forge
  - defaults
channel_priority: strict
```

**Comment by realuser** [comment]
Ok that worked thanks. I had thought defaults was the more "official" one

**Comment by xylar** [comment]
@realuser, I guess in some ways `defaults` is more "official" but you run into trouble like you found when you mix packages from different conda channels or when you mix PyPI packages (installed with `pip`) with conda packages.  Since `conda-forge` has a lot more packages to offer, people often want it to be the highest priority channel like in this case.
