### ISSUE TITLE
Shared Libraries Error

### ISSUE THREAD

**Issue by mccarthyryanc** [conda-forge/gdal-feedstock#69]
**OS**: Ubuntu 16.04
**Anaconda**: 4.0
**Python**: 3.5

I installed gdal via conda:
```
$ conda install -c conda-forge gdal
```
with no issues.

However I get the following error with any call to GDAL:
```
$ gdalinfo --version
gdalinfo: error while loading shared libraries: libcharset.so.1: cannot open shared object file: No such file or directory
```

**Comment by gillins** [comment]
I can't reproduce that here. `libcharset` is provided by the `libiconv` package. Can you try installing `gdal` into a new environment let us know what happens:
```
conda create -n myenv gdal
source activate myenv
gdalinfo --version
```

**Comment by mccarthyryanc** [comment]
Creating a new environment fixes GDAL, thanks for the help. However, it looks like installing rasterio is package that originally messed things up. I'll post an issue at the rasterio-feedstock.

**Comment by ocefpaf** [comment]
@mccarthyryanc `rasterio` is pinned against `gdal 1.11.x`, so maybe that is the problem. I will take a look at this.

**Comment by mccarthyryanc** [comment]
Here is what I get when installing rasterio in a new environment:
```
conda create -n rasterio_test_env rasterio
source activate rasterio_test_env
conda install -c conda-forge rasterio
python
```
```python
>>> import rasterio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mccarthyr/anaconda3/envs/rasterio_test_env/lib/python3.5/site-packages/rasterio/__init__.py", line 15, in <module>
    from rasterio._base import (
ImportError: libmfhdf.so.0: cannot open shared object file: No such file or directory
```

**Comment by ocefpaf** [comment]
@mccarthyryanc I suspect you are getting a mix of channels (`defaults` and `conda-forge`).
Please try:

```shell
conda create -n rasterio_test_env python=3.5 rasterio --yes -c conda-forge 
source activate rasterio_test_env
python -c "import rasterio; print(rasterio.__version__)"
```

Also paste here the result `conda list`. It should be similar to [this](https://gist.github.com/ocefpaf/0b1b61b18a7dea342a69b4914b234054) one.

**Comment by mccarthyryanc** [comment]
Yep, that works. Here is the conda list output:
```
# packages in environment at /home/mccarthyr/anaconda3/envs/rasterio_test_env:
#
affine                    2.0.0.post1              py35_0    conda-forge
click                     6.6                      py35_0    defaults
click-plugins             1.0.3                    py35_0    conda-forge
cligj                     0.4.0                    py35_0    defaults
curl                      7.49.0                        0    defaults
expat                     2.1.0                         1    conda-forge
freexl                    1.0.2                         0    conda-forge
gdal                      1.11.4             np111py35_10    conda-forge
geos                      3.4.2                         1    conda-forge
giflib                    5.1.2                         0    conda-forge
hdf4                      4.2.11                        4    conda-forge
hdf5                      1.8.17                        0    conda-forge
icu                       56.1                          2    conda-forge
jasper                    1.900.1                       2    conda-forge
jpeg                      9b                            0    conda-forge
json-c                    0.12                          0    conda-forge
krb5                      1.13.2                        0    defaults
libgcc                    5.2.0                         0    defaults
libiconv                  1.14                          1    conda-forge
libnetcdf                 4.4.0                         1    conda-forge
libpng                    1.6.22                        0    defaults
libspatialite             4.3.0a                        6    conda-forge
libtiff                   4.0.6                         4    conda-forge
libxml2                   2.9.3                         6    conda-forge
mkl                       11.3.3                        0    defaults
ncurses                   5.9                           7    conda-forge
numpy                     1.11.0                   py35_1    defaults
openjpeg                  2.1.0                         5    conda-forge
openssl                   1.0.2h                        1    defaults
pip                       8.1.2                    py35_0    defaults
postgresql                9.1.4                         1    defaults
proj.4                    4.9.2                         0    conda-forge
pyparsing                 2.1.4                    py35_0    defaults
python                    3.5.1                         0    defaults
rasterio                  0.35.1              np111py35_1    conda-forge
readline                  6.2                           2    defaults
setuptools                22.0.5                   py35_0    defaults
snuggs                    1.3.1                    py35_0    conda-forge
sqlite                    3.9.2                         0    defaults
tk                        8.5.19                        0    conda-forge
wheel                     0.29.0                   py35_0    defaults
xerces-c                  3.1.2                         0    defaults
xz                        5.0.5                         1    defaults
zlib                      1.2.8                         3    defaults
```
Thanks for help! Having GDAL available through conda-forge has relieved a lot of headaches for me and my coworkers!

**Comment by ocefpaf** [comment]
Glad it is resolved. I suspect the `conda-list` above is from the commands I sent you and not your original env, right? That one looks to be installing everything from `conda-forge`.

Hopefully that will be easier in the future as conda is evolving to better handle multiple channels.

**Comment by shanyuk** [comment]
You should make sure your jpeg
