### ISSUE TITLE
ice 48 vs 56

### ISSUE THREAD

**Issue by jlaura** [conda-forge/gdal-feedstock#73]
It looks like the icu library was recently upgraded from .48 to .56.  

```bash
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    icu-56.1                   |                2        21.5 MB
```

On both OSX and linux, this appears to have broken the GDAL 2.1.0 installation.

```bash
>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jlaura/miniconda3/envs/lidar2image/lib/python3.5/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/jlaura/miniconda3/envs/lidar2image/lib/python3.5/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/jlaura/miniconda3/envs/lidar2image/lib/python3.5/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/jlaura/miniconda3/envs/lidar2image/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/jlaura/miniconda3/envs/lidar2image/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libicuuc.so.48: cannot open shared object file: No such file or directory
```

I am not sure which dependency is looking for ICU, or I would open a ticket / PR there with an upgrade.  Can anyone confirm that the build is not working?  If so, does anyone know what gdal dep. requires ICU?

**Comment by jlaura** [comment]
Of course, I find it immediately after opening this ticket.   `libxml`

**Comment by gillins** [comment]
I can't reproduce this problem on my Linux. Can you try installing `gdal` into a new environment and see what happens?

**Comment by jlaura** [comment]
I just downloaded Anaconda 4.0.0, created a new clean python only env and then installed.  OS is Red Hat 4.4.7-1.  Error is:

```bash
Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jlaura/anaconda3/envs/gdaltest/lib/python3.5/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/jlaura/anaconda3/envs/gdaltest/lib/python3.5/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/jlaura/anaconda3/envs/gdaltest/lib/python3.5/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/jlaura/anaconda3/envs/gdaltest/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/jlaura/anaconda3/envs/gdaltest/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libicuuc.so.48: cannot open shared object file: No such file or directory
```

Installed Packages
```bash
# packages in environment at /home/jlaura/anaconda3/envs/gdaltest:
#
curl                      7.49.1                        0    conda-forge
freexl                    1.0.2                         1    conda-forge
gdal                      2.1.0               np111py35_4    conda-forge
geos                      3.4.2                         1    conda-forge
hdf4                      4.2.11                        4    conda-forge
hdf5                      1.8.17                        0    conda-forge
icu                       56.1                          2    conda-forge
jpeg                      9b                            0    conda-forge
kealib                    1.4.6                         1    conda-forge
krb5                      1.14.2                        0    conda-forge
libiconv                  1.14                          2    conda-forge
libnetcdf                 4.4.0                         1    conda-forge
libpng                    1.6.22                        0    defaults
libspatialite             4.3.0a                        7    conda-forge
libtiff                   4.0.6                         4    conda-forge
libxml2                   2.9.3                         7    conda-forge
mkl                       11.3.3                        0    defaults
ncurses                   5.9                           7    conda-forge
numpy                     1.11.0                   py35_1    defaults
openjpeg                  2.1.0                         5    conda-forge
openssl                   1.0.2h                        1    defaults
pip                       8.1.2                    py35_0    defaults
postgresql                9.1.4                         1    defaults
proj.4                    4.9.2                         0    conda-forge
python                    3.5.1                         0    defaults
readline                  6.2                           2    defaults
setuptools                23.0.0                   py35_0    defaults
sqlite                    3.9.2                         0    defaults
tk                        8.5.19                        0    conda-forge
wheel                     0.29.0                   py35_0    defaults
xerces-c                  3.1.3                         1    jlaura
xz                        5.0.5                         1    defaults
zlib                      1.2.8                         3    conda-forge
```

**Comment by ocefpaf** [comment]
Can you try?

```shell
conda create -n TEST python=3.5 gdal --yes --channel conda-forge
source activate TEST
python -c "import gdal; print(dir(gdal))"
```

That creates a self-contained `TEST` env with only `gdal` from conda-forge.

I tested it locally here and it downloads `icu 56.1-2 -forge` as expected. If that does work for you there we need to figure out why the latest `icu` was not downloaded in your previous attempts. Maybe a conflict with another package you have in your environment.

PS: Did you try to install `conda install -c conda-forge icu` in your current env? That might help too.

**Comment by jlaura** [comment]
I ended up cleaning our other envs that appeared to be linking, instead of downloading GDAL.  I am hitting the dreaded `ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found` which looks like it will be the end of the road on this issue (I can not upgrade the OS).  Making it to this import error suggests that the above, reported bug, had to do with conda linking.

Thanks all for the assistance.

**Comment by ocefpaf** [comment]
> I ended up cleaning our other envs that appeared to be linking, instead of downloading GDAL.  I am hitting the dreaded `ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found` which looks like it will be the end of the road on this issue (I can not upgrade the OS).  Making it to this import error suggests that the above, reported bug, had to do with conda linking.

Sorry for taking me so long to answer, but that is not your OS fault. We are having some major issues with that! Hopefully the next `gdal` release won't be linking to `libstdc++`. A workaround for now is to install the `libgcc` package on Linux.
