### ISSUE TITLE
Missing AdobeDeflate codec on Windows

### ISSUE THREAD

**Issue by snorfalorpagus** [conda-forge/gdal-feedstock#80]
I've been experiencing the following exception using rasterio on Windows:
```
Traceback (most recent call last):
  File "fix2.py", line 5, in <module>
    src = rasterio.open(filename, "r")
  File "C:\Miniconda3-x64\envs\deflate\lib\site-packages\rasterio\__init__.py",
line 193, in open
    s.start()
  File "rasterio\_base.pyx", line 72, in rasterio._base.DatasetReader.start (ras
terio/_base.c:2836)
  File "rasterio\_base.pyx", line 74, in rasterio._base.DatasetReader.start (ras
terio/_base.c:2788)
  File "rasterio\_err.pyx", line 196, in rasterio._err.CPLErrors.check (rasterio
/_err.c:1760)
rasterio._err.CPLE_AppDefined: Cannot open TIFF file due to missing codec.
```

I get a similar message trying to use the command line utils for GDAL:
```
0...10...20...30...40...50...60...70...80...90...100 - done.
Warning 1: 15_DSM.tif:AdobeDeflate compression support is not configured
ERROR 1: Cannot open TIFF file due to missing codec.
Warning 1: Can't open 15_DSM.tif. Skipping it
```

This seems to be a Windows specific issue - I have no issues reading the file(s) on Linux. I can't presently share the specific files in question due to licencing restrictions. I'll try to find something I can share.

I can't see anything in the builds that would cause this. I'm running the latest everything (64-bit):

```
    affine:        2.0.0.post1-py34_0     conda-forge
    click:         6.6-py34_0
    click-plugins: 1.0.3-py34_0           conda-forge
    cligj:         0.4.0-py34_0
    curl:          7.48.0-vc10_2          conda-forge [vc10]
    expat:         2.1.0-vc10_1           conda-forge [vc10]
    gdal:          2.1.0-np111py34_vc10_5 conda-forge [vc10]
    geos:          3.4.2-vc10_2           conda-forge [vc10]
    hdf4:          4.2.11-vc10_4          conda-forge [vc10]
    hdf5:          1.8.17-vc10_2          conda-forge [vc10]
    jpeg:          9b-vc10_0              conda-forge [vc10]
    kealib:        1.4.6-vc10_2           conda-forge [vc10]
    krb5:          1.14.2-vc10_0          conda-forge [vc10]
    libnetcdf:     4.4.0-vc10_1           conda-forge [vc10]
    libpng:        1.6.21-vc10_1          conda-forge [vc10]
    libtiff:       4.0.6-vc10_4           conda-forge [vc10]
    mkl:           11.3.3-1
    numpy:         1.11.0-py34_1
    openjpeg:      2.1.0-vc10_5           conda-forge [vc10]
    proj.4:        4.9.2-py34_vc10_0      conda-forge [vc10]
    pyparsing:     2.1.1-py34_0           conda-forge
    rasterio:      0.36.0-np111py34_0     conda-forge
    snuggs:        1.3.1-py34_0           conda-forge
    xerces-c:      3.1.2-vc10_0                       [vc10]
    zlib:          1.2.8-vc10_3           conda-forge [vc10]
```

**Comment by gillins** [comment]
Thanks for the report. Seems `libtiff` calls `zlib` compression "Adobe" internally (see `tif_codec.c`). I've just opened an issue with the `libtiff` recipe (https://github.com/conda-forge/libtiff-feedstock/issues/13) and will close this in favour of that.
