### ISSUE TITLE
Recent builds broken?

### ISSUE THREAD

**Issue by kwilcox** [conda-forge/gdal-feedstock#86]
I'm having issues on linux with 3.5 and 3.4

```bash
$ conda create -n gdal34 python=3.4
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home/kwilcox/miniconda3/envs/gdal34:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2h-1      defaults
    pip:        8.1.2-py34_0  defaults
    python:     3.4.4-5       defaults
    readline:   6.2-2         defaults
    setuptools: 23.0.0-py34_0 defaults
    sqlite:     3.13.0-0      defaults
    tk:         8.5.18-0      defaults
    wheel:      0.29.0-py34_0 defaults
    xz:         5.2.2-0       defaults
    zlib:       1.2.8-3       defaults

Proceed ([y]/n)? 

Linking packages ...
[      COMPLETE      ]|##########################################################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate gdal34
#
# To deactivate this environment, use:
# $ source deactivate
#

$ source activate gdal34                                                                                                                                                                                                

(gdal34)$ conda install -c conda-forge gdal
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/kwilcox/miniconda3/envs/gdal34:

The following NEW packages will be INSTALLED:

    curl:          7.49.1-0          conda-forge
    expat:         2.1.0-1           conda-forge
    freexl:        1.0.2-1           conda-forge
    gdal:          2.1.0-np111py34_6 conda-forge
    geos:          3.4.2-2           conda-forge
    giflib:        5.1.2-1           conda-forge
    hdf4:          4.2.11-4          conda-forge
    hdf5:          1.8.17-2          conda-forge
    jpeg:          9b-0              conda-forge
    json-c:        0.12-0            conda-forge
    kealib:        1.4.6-2           conda-forge
    krb5:          1.14.2-0          conda-forge
    libiconv:      1.14-2            conda-forge
    libnetcdf:     4.4.0-1           conda-forge
    libpng:        1.6.23-0          conda-forge
    libspatialite: 4.3.0a-8          conda-forge
    libtiff:       4.0.2-0           defaults   
    libxml2:       2.9.2-0           defaults   
    mkl:           11.3.3-0          defaults   
    numpy:         1.11.1-py34_0     defaults   
    openjpeg:      2.1.0-5           conda-forge
    postgresql:    9.1.4-1           defaults   
    proj.4:        4.9.2-0           conda-forge
    xerces-c:      3.1.2-0           defaults   

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##########################################################################################################################################################################| 100%

(gdal34)$ python
Python 3.4.4 |Continuum Analytics, Inc.| (default, Jun 15 2016, 15:26:54) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kwilcox/miniconda3/envs/gdal34/lib/python3.4/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/kwilcox/miniconda3/envs/gdal34/lib/python3.4/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/kwilcox/miniconda3/envs/gdal34/lib/python3.4/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/kwilcox/miniconda3/envs/gdal34/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: libjpeg.so.62: cannot open shared object file: No such file or directory
```

**Comment by kwilcox** [comment]
@ocefpaf came to the rescue

```bash
$ conda install -c conda-forge libtiff
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/kwilcox/miniconda3/envs/gdal34:

The following packages will be UPDATED:

    libtiff: 4.0.2-0 defaults --> 4.0.6-5 conda-forge

The following packages will be SUPERCEDED by a higher-priority channel:

    xz:      5.2.2-0 defaults --> 5.0.5-1 conda-forge

The following packages will be DOWNGRADED due to dependency conflicts:

    python:  3.4.4-5 defaults --> 3.4.4-0 defaults

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|##########################################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##########################################################################################################################################################################| 100%

(gdal34) $ python                                  
impPython 3.4.4 |Continuum Analytics, Inc.| (default, Jan 11 2016, 13:54:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdal
>>>
```

**Comment by ocefpaf** [comment]
This issue will be partially solved when we pin our Python with `xz 5.2.*`. (Ping @pelson)

Here is how it breaks down:

- conda is resolving the latest version of `Python 3.4` with  `xz 5.2.2`;
- that pulls a `libtiff` from `defaults` that is also compiled against `xz 5.2.2`;
- this `libtiff` is pinned against `jpeg8b` but conda-forge `gdal` is pinned against `jpeg 9d`. See,

```shell
> conda execute scripts/list_deps.py defaults --package libtiff --platform linux-64
Fetching package metadata: ....
libtiff 4.0.2 1 linux-64           : jpeg 8d
libtiff 4.0.6 0 linux-64           : jpeg 8d
libtiff 4.0.6 1 linux-64           : jbig 2.1, jpeg 8d, xz 5.0.5, zlib 1.2*
libtiff 4.0.6 2 linux-64           : jbig 2.1, jpeg 8d, xz 5.2.*, zlib 1.2.*
```

IMO conda should get packages that are consistently pinned (see the python downgrade in your second message which is probably using `xz 5.0.5`) or conda should at least return some sort of unresolvable dependency.

However, it seems like conda cannot do that! (I am not sure why but that happens specially when the dependency is python and/or  when creating an env.) Therefore we need to update our pinning to match `defaults` latest `xz`.

**Comment by pelson** [comment]
@ocefpaf - it would really help to track down the specific packages which are under-pinned. It sounds like they may be `defaults` packages, and we should definitely let the Continuum folks know about it.

**Comment by ocefpaf** [comment]
> @ocefpaf - it would really help to track down the specific packages which are under-pinned. It sounds like they may be `defaults` packages, and we should definitely let the Continuum folks know about it.

In this particular case I cannot see any pinning issue with `defaults`. I do see a problem in the fact that `conda-forge`'s `gdal` is pinned to `jpeg 9*` and installed along side a `libtiff` that is pinned to `jpeg 8d`. That should be incompatible IMO.

See that forcing the installation of `conda-forge`'s `libtiff` in https://github.com/conda-forge/gdal-feedstock/issues/86#issuecomment-229768696 triggered the proper solution that conda should have made in the first place with the current channel and pinning combination we have. (I'd expected at least a unresolvable dependency message.)

**Comment by pelson** [comment]
> That should be incompatible IMO.

Agreed. The metadata makes that abundantly clear.

> I am not sure what I should be tracking down there.

A bug with conda...

```
conda create -n foo libtiff=4.0.2=0 jpeg=9* -c conda-forge -c defaults
Fetching package metadata ...........
Solving package specifications ............

Package plan for installation in environment /data/local/itpe/miniconda/envs/foo:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libtiff-4.0.2              |                0        1001 KB  defaults

The following NEW packages will be INSTALLED:

    jpeg:    9b-0    conda-forge
    libtiff: 4.0.2-0 defaults
```

This should now be easy enough to generate a simple test case with to highlight the bug.

**Comment by ocefpaf** [comment]
Now that we merged https://github.com/conda-forge/libtiff-feedstock/pull/16 this can be closed.
