### ISSUE TITLE
ImportError: DLL load failed while importing _gdal: The specified procedure could not be found. At Gdal 3.4.3

### ISSUE THREAD

**Issue by julian-belina** [conda-forge/gdal-feedstock#883]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When install gdal 3.4.3 in a new environment i get the following traceback when i try to load gdal:

C:\Users\PAVAN_F>conda activate test_gdal_env
 
(test_gdal_env) C:\Users\PAVAN_F>python
Python 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:27:34) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal
Traceback (most recent call last):
  File "C:\Users\PAVAN_F\AppData\Local\Continuum\Anaconda3\envs\test_gdal_env\lib\site-packages\osgeo\__init__.py", line 29, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\PAVAN_F\AppData\Local\Continuum\Anaconda3\envs\test_gdal_env\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: The specified procedure could not be found.
 
>>>During handling of the above exception, another exception occurred:
 
>>>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\PAVAN_F\AppData\Local\Continuum\Anaconda3\envs\test_gdal_env\lib\site-packages\osgeo\__init__.py", line 45, in <module>
    _gdal = swig_import_helper()
  File "C:\Users\PAVAN_F\AppData\Local\Continuum\Anaconda3\envs\test_gdal_env\lib\site-packages\osgeo\__init__.py", line 42, in swig_import_helper
    return importlib.import_module('_gdal')
  File "C:\Users\PAVAN_F\AppData\Local\Continuum\Anaconda3\envs\test_gdal_env\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal'

### Installed packages

```shell
# packages in environment at C:\Users\PAVAN_F\AppData\Local\Continuum\Anaconda3\envs\test_gdal_env:
#
# Name                    Version                   Build  Channel
blosc                     1.21.5               hdccc3a2_0    conda-forge
boost-cpp                 1.78.0               h9f4b32c_4    conda-forge
bzip2                     1.0.8                hcfcfb64_5    conda-forge
ca-certificates           2023.11.17           h56e8100_0    conda-forge
cairo                     1.16.0            hd694305_1014    conda-forge
cfitsio                   4.1.0                h5a969a9_0    conda-forge
curl                      8.5.0                hd5e4a3a_0    conda-forge
expat                     2.5.0                h63175ca_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
freexl                    1.0.6                h67ca5e6_1    conda-forge
gdal                      3.4.3           py310h644bc08_1    conda-forge
geos                      3.11.1               h1537add_0    conda-forge
geotiff                   1.7.1                h4ffd875_4    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
hdf4                      4.2.15               h1b1b6ef_5    conda-forge
hdf5                      1.12.2          nompi_h57737ce_101    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
intel-openmp              2023.2.0         h57928b3_50497    conda-forge
jpeg                      9e                   hcfcfb64_3    conda-forge
kealib                    1.5.0                h61be68b_0    conda-forge
krb5                      1.21.2               heb0366b_0    conda-forge
lcms2                     2.14                 h90d422f_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.1.2                h63175ca_1    conda-forge
libblas                   3.9.0              20_win64_mkl    conda-forge
libcblas                  3.9.0              20_win64_mkl    conda-forge
libcurl                   8.5.0                hd5e4a3a_0    conda-forge
libdeflate                1.14                 hcfcfb64_0    conda-forge
libexpat                  2.5.0                h63175ca_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgdal                   3.4.3                h43f05fc_1    conda-forge
libglib                   2.78.1               he8f3873_0    conda-forge
libhwloc                  2.9.3           default_haede6df_1009    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libkml                    1.3.0             hd45a9bc_1016    conda-forge
liblapack                 3.9.0              20_win64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_h8c042bf_106    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libpq                     15.4                 h1beaf6b_5    conda-forge
librttopo                 1.1.0               he22b5cd_12    conda-forge
libspatialite             5.0.1               h07bf483_22    conda-forge
libsqlite                 3.44.2               hcfcfb64_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libtiff                   4.4.0                hc4f729c_5    conda-forge
libwebp-base              1.3.2                hcfcfb64_0    conda-forge
libxml2                   2.12.4               hc3477c8_1    conda-forge
libzip                    1.10.1               h1d365fa_3    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
mkl                       2023.2.0         h6a75c08_50497    conda-forge
numpy                     1.26.3          py310hf667824_0    conda-forge
openjpeg                  2.5.0                hc9384bd_1    conda-forge
openssl                   3.2.0                hcfcfb64_1    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
pixman                    0.43.0               h63175ca_0    conda-forge
poppler                   22.12.0              ha6c1112_0    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                15.4                 h1beaf6b_5    conda-forge
proj                      9.1.0                h3863b3b_0    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
python                    3.10.13         h4de0772_1_cpython    conda-forge
python_abi                3.10                    4_cp310    conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
snappy                    1.1.10               hfb803bf_0    conda-forge
sqlite                    3.44.2               hcfcfb64_0    conda-forge
tbb                       2021.11.0            h91493d7_0    conda-forge
tiledb                    2.13.2               h3132609_0    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
tzdata                    2023d                h0c530f3_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
uriparser                 0.9.7                h1537add_1    conda-forge
vc                        14.3                hcf57466_18    conda-forge
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.5                h63175ca_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge
```

### Environment info

```shell
active environment : test_gdal_env
    active env location : C:\Users\PAVAN_F\AppData\Local\Continuum\Anaconda3\envs\test_gdal_env
            shell level : 1
       user config file : C:\Users\PAVAN_F\.condarc
populated config files : C:\Users\PAVAN_F\.condarc
          conda version : 23.9.0
    conda-build version : 3.28.3
         python version : 3.9.7.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\PAVAN_F\AppData\Local\Continuum\Anaconda3  (writable)
      conda av data dir : C:\Users\PAVAN_F\AppData\Local\Continuum\Anaconda3\etc\conda
  conda av metadata url : None
           channel URLs :
https://repo.anaconda.com/pkgs/main/win-64

https://repo.anaconda.com/pkgs/main/noarch

https://repo.anaconda.com/pkgs/r/win-64

https://repo.anaconda.com/pkgs/r/noarch

https://repo.anaconda.com/pkgs/msys2/win-64

https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\PAVAN_F\AppData\Local\Continuum\Anaconda3\pkgs
                          C:\Users\PAVAN_F\.conda\pkgs
                          C:\Users\PAVAN_F\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\PAVAN_F\AppData\Local\Continuum\Anaconda3\envs
                          C:\Users\PAVAN_F\.conda\envs
                          C:\Users\PAVAN_F\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.9.0 requests/2.31.0 CPython/3.9.7 Windows/10 Windows/10.0.19045 solver/libmamba conda-libmamba-solver/23.9.3 libmambapy/1.5.1 aau/0.4.3 c/4LNyGqzXy0VsBc52RAUfOQ s/_kPw7OgJloq2HMRgY6UQFg e/HsV7qpk-64Bb1qaG4SeWsA
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by akrherz** [comment]
GDAL 3.4.3 is ancient, is that version a requirement for your needs?

**Comment by julian-belina** [comment]
I suspect that that the Visual Studio might be a problem. This problem occurs on a Windows 10 machine with the 
Microsoft Visual C++ 2015-2019 Redistributable (x64) -14.28.29914.0

On a windows 11 machine with Microsoft Visual C++ 2015-2022 Redistributable (x64) -14.36.32532
The same packages are installed and no error occurs

**Comment by julian-belina** [comment]
> chine with Microsoft Vi

Unfortunately yes. A lot of software at my institute is bound to it.

**Comment by julian-belina** [comment]
@akrherz Updating the Microsoft Visual C++ 2015-2019 Redustributable from 14.28.29914 to 14.34.33130 resoled the problem. Is it possible to update the meta data to respect this constraint?

**Comment by DOptimusPrime** [comment]
I am also running into the same problem. I have  Microsoft Visual C++ 2012  11.0.61030.0, Redistributable, Microsoft Visual C++ 2015-2019 Redistributable, Microsoft Visual C++ 2015-2022 Redistributable. I am have gdal 0.3.0. This is the one I need to run code. Any ideas

**Comment by julian-belina** [comment]
Is it possible that you mean a diffrent gdal version than 0.3.0? This version would be very old and is not on conda-forge.
At least gdal 3.x versions depend on the Visual C++ 14.x redistributable. 

A possible cause for the error is that the binaries provided by conda-forge have been created with a newer version of Visual C++. The newer versions of the redistributable a backwards compatible as you can read [here](https://www.majorgeeks.com/content/page/what_is_microsoft_visual_c_and_microsoft_visual_c_redistributable_package.html#:~:text=The%20goal%20of%20the%20Microsoft,with%20Microsoft%20Visual%20C%2B%2B.)

**Comment by joaocarr** [comment]
I've been getting the same error for 2 or 3 months. I have MS Visual C++ 2015-2022 Redistributable (x64) (14.42.34438), and the following list of packages in my conda env. I don't have this issue in Linux with the same installed packages.

# packages in environment at C:\Dev\conda_envs\burst2safe:
#
# Name                    Version                   Build  Channel
_libavif_api              1.2.0                h57928b3_0    conda-forge
aiohappyeyeballs          2.5.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.11.13         py312h31fea79_0    conda-forge
aiosignal                 1.3.2              pyhd8ed1ab_0    conda-forge
aom                       3.9.1                he0c23c2_0    conda-forge
asf_search                8.1.1              pyhd8ed1ab_0    conda-forge
asf_search-base           8.1.1              pyhd8ed1ab_0    conda-forge
attrs                     25.1.0             pyh71513ae_0    conda-forge
blosc                     1.21.6               hfd34d9b_1    conda-forge
brotli-python             1.1.0           py312h275cf98_2    conda-forge
burst2safe                1.4.2              pyhd8ed1ab_1    conda-forge
bzip2                     1.0.8                h2466b09_7    conda-forge
c-blosc2                  2.15.2               h9e57077_1    conda-forge
ca-certificates           2025.1.31            h56e8100_0    conda-forge
certifi                   2025.1.31          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py312h4389bb4_0    conda-forge
charls                    2.4.2                h1537add_0    conda-forge
charset-normalizer        3.4.1              pyhd8ed1ab_0    conda-forge
ciso8601                  2.3.2           py312h4389bb4_0    conda-forge
dateparser                1.2.1              pyhd8ed1ab_0    conda-forge
dav1d                     1.2.1                hcfcfb64_0    conda-forge
freexl                    2.0.0                hf297d47_2    conda-forge
frozenlist                1.5.0           py312h31fea79_1    conda-forge
gdal                      3.10.2          py312hc39d689_1    conda-forge
geos                      3.13.0               h5a68840_0    conda-forge
geotiff                   1.7.4                h887f4e7_0    conda-forge
giflib                    5.2.2                h64bf75a_0    conda-forge
h2                        4.2.0              pyhd8ed1ab_0    conda-forge
hpack                     4.1.0              pyhd8ed1ab_0    conda-forge
hyperframe                6.1.0              pyhd8ed1ab_0    conda-forge
idna                      3.10               pyhd8ed1ab_1    conda-forge
imagecodecs               2024.12.30      py312hf5bc1e8_0    conda-forge
importlib-metadata        8.6.1              pyha770c72_0    conda-forge
importlib_metadata        8.6.1                hd8ed1ab_0    conda-forge
intel-openmp              2025.0.0          h57928b3_1168    conda-forge
jxrlib                    1.1                  hcfcfb64_3    conda-forge
krb5                      1.21.3               hdf4eb48_0    conda-forge
lcms2                     2.17                 hbcf6048_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.1.3                h63175ca_0    conda-forge
libarchive                3.7.7                h979ed78_3    conda-forge
libavif16                 1.2.0                h551e529_0    conda-forge
libblas                   3.9.0              18_win64_mkl    conda-forge
libbrotlicommon           1.1.0                h2466b09_2    conda-forge
libbrotlidec              1.1.0                h2466b09_2    conda-forge
libbrotlienc              1.1.0                h2466b09_2    conda-forge
libcblas                  3.9.0              18_win64_mkl    conda-forge
libcurl                   8.12.1               h88aaa65_0    conda-forge
libde265                  1.0.15               h91493d7_0    conda-forge
libdeflate                1.23                 h9062f6e_0    conda-forge
libexpat                  2.6.4                he0c23c2_0    conda-forge
libffi                    3.4.6                h537db12_0    conda-forge
libgdal-core              3.10.2               h095903c_0    conda-forge
libheif                   1.19.7          gpl_h2684147_100    conda-forge
libhwloc                  2.11.2          default_ha69328c_1001    conda-forge
libhwy                    1.1.0                h91493d7_0    conda-forge
libiconv                  1.18                 h135ad9c_1    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
libjxl                    0.11.1               h456c5fc_0    conda-forge
libkml                    1.3.0             h538826c_1021    conda-forge
liblapack                 3.9.0              18_win64_mkl    conda-forge
liblzma                   5.6.4                h2466b09_0    conda-forge
libpng                    1.6.47               had7236b_0    conda-forge
librttopo                 1.1.0               hd4c2148_17    conda-forge
libspatialite             5.1.0               h939089a_12    conda-forge
libsqlite                 3.49.1               h67fdade_1    conda-forge
libssh2                   1.11.1               he619c9f_0    conda-forge
libtiff                   4.7.0                h797046b_3    conda-forge
libwebp-base              1.5.0                h3b0e114_0    conda-forge
libwinpthread             12.0.0.r4.gg4f2fc60ca      h57928b3_9    conda-forge
libxml2                   2.13.6               he286e8c_0    conda-forge
libxslt                   1.1.39               h3df6e99_0    conda-forge
libzlib                   1.3.1                h2466b09_2    conda-forge
libzopfli                 1.0.3                h0e60522_0    conda-forge
lxml                      5.3.1           py312h53bce91_0    conda-forge
lz4-c                     1.10.0               h2466b09_1    conda-forge
lzo                       2.10              hcfcfb64_1001    conda-forge
minizip                   4.0.7                h9fa1bad_3    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
multidict                 6.1.0           py312h31fea79_1    conda-forge
numpy                     2.0.2           py312h49bc9c5_1    conda-forge
openjpeg                  2.5.3                h4d64b90_0    conda-forge
openssl                   3.4.1                ha4e3fda_0    conda-forge
pcre2                     10.44                h3d7b363_2    conda-forge
pip                       25.0.1             pyh8b19718_0    conda-forge
proj                      9.5.1                h4f671f6_0    conda-forge
propcache                 0.2.1           py312h31fea79_1    conda-forge
pycparser                 2.22               pyh29332c3_1    conda-forge
pysocks                   1.7.1              pyh09c184e_7    conda-forge
python                    3.12.9          h3f84c4b_1_cpython    conda-forge
python-dateutil           2.9.0.post0        pyhff2d567_1    conda-forge
python-tzdata             2025.1             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    5_cp312    conda-forge
pytz                      2025.1             pyhd8ed1ab_0    conda-forge
rav1e                     0.6.6                h975169c_2    conda-forge
regex                     2024.11.6       py312h4389bb4_0    conda-forge
remotezip                 0.12.3             pyhd8ed1ab_1    conda-forge
requests                  2.32.3             pyhd8ed1ab_1    conda-forge
setuptools                75.8.2             pyhff2d567_0    conda-forge
shapely                   2.0.7           py312h0c580ee_0    conda-forge
six                       1.17.0             pyhd8ed1ab_0    conda-forge
snappy                    1.2.1                h500f7fa_1    conda-forge
sqlite                    3.49.1               h2466b09_1    conda-forge
svt-av1                   3.0.0                he0c23c2_0    conda-forge
tbb                       2021.13.0            h62715c5_1    conda-forge
tenacity                  8.2.2              pyhd8ed1ab_0    conda-forge
tifffile                  2025.2.18          pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
tzdata                    2025a                h78e105d_0    conda-forge
tzlocal                   5.3             py312h2e8e312_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_1    conda-forge
uriparser                 0.9.8                h5a68840_0    conda-forge
urllib3                   2.3.0              pyhd8ed1ab_0    conda-forge
vc                        14.3                hbf610ac_24    conda-forge
vc14_runtime              14.42.34438         hfd919c2_24    conda-forge
vs2015_runtime            14.42.34438         h7142326_24    conda-forge
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
win_inet_pton             1.1.0              pyh7428d3b_8    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xerces-c                  3.2.5                he0c23c2_2    conda-forge
yarl                      1.18.3          py312h31fea79_1    conda-forge
zfp                       1.0.1                he0c23c2_2    conda-forge
zipp                      3.21.0             pyhd8ed1ab_1    conda-forge
zlib                      1.3.1                h2466b09_2    conda-forge
zlib-ng                   2.2.4                hbb528cf_0    conda-forge
zstandard                 0.23.0          py312h7606c53_1    conda-forge
zstd                      1.5.6                h0ea2cb4_0    conda-forge

**Comment by gillins** [comment]
@joaocarr can you confirm creating a brand new environment with just qgis in also fails?

**Comment by joaocarr** [comment]
@gillins , thanks, so I did this:

conda create --prefix C:\Dev\conda_envs\test
conda activate C:\Dev\conda_envs\test 
conda install -c conda-forge qgis

I don't get an error message when creating the environment or installing qgis, but I also didn't get an error when creating the other environment. It's only when I try to run a specific package (burst2safe), that I get the error above.

**Comment by gillins** [comment]
Sorry @joaocarr, can you give me a little more information about what you are doing to get this error? So QGIS install and runs fine? What is the actual action that causes this error? How are you running burst2safe? Have you installed it via conda?

**Comment by joaocarr** [comment]
@gillins , thanks for getting back at me. So, I did something very similar to above:
conda create --prefix C:\Dev\conda_envs\burst2safe
conda activate C:\Dev\conda_envs\burst2safe
conda install -c conda-forge burst2safe

Then I run burst2safe just to retrieve the help information and got the following error:

(C:\Dev\conda_envs\burst2safe) C:\Dev\code>burst2safe -h
Traceback (most recent call last):
  File "C:\Dev\conda_envs\burst2safe\Lib\site-packages\osgeo\__init__.py", line 30, in swig_import_helper
    return importlib.import_module(mname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\conda_envs\burst2safe\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1293, in create_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Dev\conda_envs\burst2safe\Scripts\burst2safe-script.py", line 5, in <module>
    from burst2safe.burst2safe import main
  File "C:\Dev\conda_envs\burst2safe\Lib\site-packages\burst2safe\burst2safe.py", line 10, in <module>
    from burst2safe import utils
  File "C:\Dev\conda_envs\burst2safe\Lib\site-packages\burst2safe\utils.py", line 14, in <module>
    from osgeo import gdal, ogr, osr
  File "C:\Dev\conda_envs\burst2safe\Lib\site-packages\osgeo\__init__.py", line 35, in <module>
    _gdal = swig_import_helper()
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\conda_envs\burst2safe\Lib\site-packages\osgeo\__init__.py", line 32, in swig_import_helper
    return importlib.import_module('_gdal')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\conda_envs\burst2safe\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_gdal'
